### ISSUE TITLE
Test issue from API

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#10]
I assume **markdown** is OK here...? _Yes_, it `appears so`
# 

| Metadata | Value |
| :-- | :-- |
| Author | Jim Allman |
| Claimed Expertise | No |
| Upvotes | 23 |
| Feedback type | Reporting an error in phylogeny |
| URL | /about/references |
| Target node label | Arachnidae |
| Synthetic tree id | otol.draft.23 |
| Synthetic tree node id | 32423 |
| Source tree id | markey-test2 |
| Source tree node id | node56 |
| Open Tree Taxonomy id | - |
| Intended scope | placement in source tree |

**Comment by jimallman** [comment]
Here's a follow-on comment from someone else!

# 

| Metadata | Value |
| :-- | :-- |
| Author | Dr. Janet Smith |
| Claimed Expertise | Yes |
| Upvotes | 6 |
