### ISSUE TITLE
Pomacea Phylogeny Issues

### ISSUE THREAD

**Issue by ces393** [OpenTreeOfLife/feedback#101]
Awesome work!

But... Pomacea insularum was synonymized with Pomacea maculata (Hayes et al. 2012)

http://onlinelibrary.wiley.com/doi/10.1111/j.1096-3642.2012.00867.x/abstract;jsessionid=EFB0C1573E4E5BA869B0E679F7F3642F.d04t01?deniedAccessCustomisedMessage=&userIsAuthenticated=false'

Also Pomella megastoma is Pomacea megastoma

Cowie R.H. & Thiengo S.C. (2003) The apple snails of the Americas (Mollusca: Gastropoda: Ampullariidae: Asolene, Felipponea, Marisa, Pomacea, Pomella): A nomenclatural and type catalog. Malacologia 45(1): 41-100. [details]

**Comment by ces393** [comment]
Here are the URLs.

https://tree.opentreeoflife.org/opentree/argus/ottol@843053/Pomacea

https://tree.opentreeoflife.org/opentree/opentree3.0@1121901/Pomella

I dont know where to find the DOI

**Comment by ces393** [comment]
Cowie 2003 DOI:

Unavailable but here is the ISSN: 0076-2997

Cowie 2003 link:

https://ia600702.us.archive.org/30/items/cbarchive_126210_theapplesnailsoftheamericasmol1962/theapplesnailsoftheamericasmol1962.pdf

Hayes 2012 DOI:

DOI: 10.1111/j.1096-3642.2012.00867.x

Hayes 2012 link:

http://onlinelibrary.wiley.com/doi/10.1111/j.1096-3642.2012.00867.x/abstract

**Comment by jar398** [comment]
Thanks!

**Comment by ces393** [comment]
Of course! Again, awesome work.

Are you planning on adding more details to make it show relationships between closely related species (grouping into clades, meaningful branch lengths, etc)

**Comment by jar398** [comment]
Where we have added phylogenetic trees to the mix, we do show high
resolution, not just taxonomy.  There are only about 500 of these at
present, so chances are good you won't hit one if you look up a randomly
chosen taxon. The idea is to over time increase this number so we get
better and better phylogenetic coverage of the whole tree.

Branch lengths are much harder as most published trees don't provide them
and they have different meanings among the trees where they are given. We
could try to do time estimates, but apparently this is fraught. But we
would certainly like to get branch lengths into the tree somehow and are
working on the problem.

**Comment by ces393** [comment]
Awesome! Thank you! Keep up the good work! The family Ampullaridae are extremely diverse so it might be a hard one to tackle.

**Comment by jar398** [comment]
If there are particular phylogenetic trees you think we should have, and
they're not already in our study set, feel free to add them using the
curation webapp.

**Comment by ces393** [comment]
Will do if I come across some good ones.
