### ISSUE TITLE
Issue with study pg_2377

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#102]
This URL returns an error: http://api.opentreeoflife.org/v2/study/pg_2377

``` json
{"description": "Study #pg_2377 GET failure", "error": 1}
```

I found this study looking for trees that included S. cervisae using its ottId:

``` bash
curl -X POST http://api.opentreeoflife.org/v2/studies/find_trees \
> -H "content-type:application/json" -d \ '{"property":"ot:ottId","value":"908549"}'
```

**Comment by jar398** [comment]
Thanks for reporting this. This is odd. The study is present in my local clone of the github repo, but the whole pg_2377 directory is missing both from github and from the clone on api.opentreeoflife.org. Maybe it was deleted after the index was last rebuilt?

**Comment by mtholder** [comment]
Yes. thanks for the report. The study was deleted in https://github.com/OpenTreeOfLife/phylesystem-1/commit/f103b27c6dba00f9813500497a475f53aee375e8 which makes this look like a bug in the indexer (OTI) that provides searching.

It could also be a bug in the phylesystem-api tool that is supposed to trigger re-indexing of a study.

Or concievably, I suppose this could be a problem with deployment that causes the initial OTI db to be incorrect. But this sounds like a long shot.

i'll put a linked issue in the OTI issue tracker.

**Comment by jimallman** [comment]
The curation dashboard actually shows **two copies** of this study in the list:
https://tree.opentreeoflife.org/curator/?match=pg_2377

Almost certainly stale information (from oti or our troublesome cache), but I've never seen duplicates with the same id.

**Comment by jar398** [comment]
The dashboard now shows no studies. I'm not sure how to proceed with this issue. Will flag it as software issue and let it stew a while longer, then close if there's no more activity.

**Comment by jimallman** [comment]
I suspect this was all due to oti bugs (or stale index info) and fixed some time ago. Agreed that we should probably close this unless/until we see another, similar report.
