### ISSUE TITLE
Issue with C. elegans

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#106]
I believe that something is wrong when using tnrs/match_names on C. elegans.

The first match is ott_id 5252840 with the unique name "Caenorhabditis elegans (in genus Burkholderia)" which would make it a bacteria. However, I couldn't find any indication that there is a synonymy with C. elegans in the bacterial world and this first match includes [ncbi:6239](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=6239) as a synonym which refers to the round worm in the ncbi taxonomy. In other words, it seems there is a mistake in the Open Tree Taxonomy and C. elegans should only match the round worm (ott_id 395048).

``` bash
curl -X POST http://api.opentreeoflife.org/v2/tnrs/match_names \
 -H "content-type:application/json" \
-d '{"names":["Caenorhabditis elegans"]}'
```

``` json
{
  "governing_code" : "undefined",
  "unambiguous_name_ids" : [ "Caenorhabditis elegans" ],
  "unmatched_name_ids" : [ ],
  "matched_name_ids" : [ "Caenorhabditis elegans" ],
  "context" : "All life",
  "includes_deprecated_taxa" : false,
  "includes_dubious_names" : false,
  "includes_approximate_matches" : true,
  "taxonomy" : {
    "weburl" : "https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy",
    "author" : "open tree of life project",
    "source" : "ott2.8"
  },
  "results" : [ {
    "id" : "Caenorhabditis elegans",
    "matches" : [ {
      "matched_node_id" : 384279,
      "synonyms" : [ "Caenorhabditis elegans", "ncbi:6239" ],
      "flags" : [ ],
      "ot:ottTaxonName" : "Caenorhabditis elegans",
      "search_string" : "caenorhabditis elegans",
      "matched_name" : "Caenorhabditis elegans",
      "is_synonym" : false,
      "score" : 1.0,
      "unique_name" : "Caenorhabditis elegans (in genus Burkholderia)",
      "ot:ottId" : 5252840,
      "is_deprecated" : false,
      "nomenclature_code" : "ICNP",
      "is_approximate_match" : false,
      "rank" : "",
      "is_dubious" : false
    }, {
      "matched_node_id" : 2991251,
      "synonyms" : [ "roundworm", "Rhabditis elegans", "Caenorhabditis elegans" ],
      "flags" : [ ],
      "ot:ottTaxonName" : "Caenorhabditis elegans",
      "search_string" : "caenorhabditis elegans",
      "matched_name" : "Caenorhabditis elegans",
      "is_synonym" : false,
      "score" : 1.0,
      "unique_name" : "Caenorhabditis elegans (species in subfamily Peloderinae)",
      "ot:ottId" : 395048,
      "is_deprecated" : false,
      "nomenclature_code" : "ICZN",
      "is_approximate_match" : false,
      "rank" : "",
      "is_dubious" : false
    } ]
  } ]
```

**Comment by jar398** [comment]
Yes, this is a known error. The reason, I believe, is sample contamination
in a Genbank deposit (JN975069). The bacterial sequence was described as C.
elegans by the depositor, and the NCBI curators associated it with the C.
elegans taxon. But SILVA placed the sequence (correctly I hope) in
bacteria. Since we take SILVA to be higher priority than NCBI, we simply
propagated the error.

I fixed this (and about a dozen similar situations) and it is reflected in
a newer version of the taxonomy, which unfortunately is not yet on the web
site.

Jonathan

**Comment by fmichonneau** [comment]
OK, that sounds good. I'm going to close if it's resolved (even if not released). Thanks!
