### ISSUE TITLE
Fonticulida appears under Discicristoidea while Fonticula is under Opisthoconta

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#107]
samefor nucleariidae and nucleariida
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | jmv2009 |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@702499/Opisthokonta](https://tree.opentreeoflife.org/opentree/opentree3.0@702499/Opisthokonta) |
| Target node label | Opisthokonta |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 702499 |
| Source tree id(s) | silva:D11377/#2,if:90277,ncbi:33154,irmng:183 |
| Open Tree Taxonomy id | 332573 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
I don't think this is a taxonomy problem - everything comes from SILVA and
looks well formed to me. So I will hand this off to someone working on
synthesis. If it turns out the source trees are right and the taxonomy is
wrong, we'll have something to tell the SILVA folks.

**Comment by hyanwong** [comment]
Also see https://github.com/OpenTreeOfLife/feedback/issues/51

**Comment by hyanwong** [comment]
Can this be closed, as with https://github.com/OpenTreeOfLife/feedback/issues/51 ?

**Comment by jar398** [comment]
yes.  ott 2.9 has 
Fonticula   < Fonticulidae  < Fonticulida < Discicristoidea
