### ISSUE TITLE
Cryptomonads are in wrlong place;  doi: 10.1073/pnas.1420657112

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#108]
Cryptomonads are in wrlong place;  [doi: 10.1073/pnas.1420657112](http://dx.doi.org/10.1073/pnas.1420657112)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | JMV2009 |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@3843740/Chloroplastida--Rhodophyceae--](https://tree.opentreeoflife.org/opentree/opentree3.0@3843740/Chloroplastida--Rhodophyceae--) |
| Target node label | [Chloroplastida + Rhodophyceae + ...] |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 3843740 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Intended scope | Re: synthetic tree |

**Comment by mtholder** [comment]
tree queued for next synthesis run
