### ISSUE TITLE
Hide Properties

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#109]
If I hide the properties they should stay hidden until I click show properties. I clicked the "Hide Properties" button. Then I clicked a node, and properties reappeared. Why? If I want to hide the properties, I want them hidden. I most certainly do not want to have to hide them every time I move through the tree. At 
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Nicholas Beeson](mailto:nwbeeson@umich.edu) |
| Upvotes | 0 |
| URL | [/contact](None/contact) |
| Target node label |  |
| Synthetic tree id |  |
| Synthetic tree node id |  |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Intended scope |  |

**Comment by jimallman** [comment]
Good point! The current behavior was chosen out of concern that a new user (esp. in a narrow view like a tablet) should always see meaningful data, beyond just the tree structure. This has come at the expense of other users who want to move through the tree without the clutter. I'm sure we can make this persist once a choice has been made.

I've added this as an [enhancement](https://github.com/OpenTreeOfLife/opentree/issues/778) in our bug-tracking system, in case you want to track its progress.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Jim Allman](https://github.com/jimallman) 
Upvotes   |   0

**Comment by jimallman** [comment]
Good point! The current behavior was chosen to ensure that a new user (esp. in a narrow view like a tablet) would always see meaningful data, beyond just the tree structure. This has come at the expense of other users who want to move through the tree without the clutter. I'm sure we can make this persist, once the user has made a choice.

I've added this as an enhancement request in our bug tracking system, in case you want to track its progress:
https://github.com/OpenTreeOfLife/opentree/issues/778

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jim Allman](https://github.com/jimallman) |
| Upvotes | 0 |

**Comment by opentreeapi** [comment]
Thanks Jim. This is a joy and wonder to me. Your group has done a truly marvelous thing. It is an intellectual triumph.

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Nicholas Beeson](mailto:nwbeeson@umich.edu) |
| Upvotes | 0 |

**Comment by opentreeapi** [comment]
This is fantastic - I've learnt a lot in just a few minutes browsing.

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Alan Fish](mailto:afish@fico.com) |
| Upvotes | 0 |

**Comment by opentreeapi** [comment]
Would be nice if "i" also displayed a brief definition or description of each node

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Alan Fish](mailto:afish@fico.com) |
| Upvotes | 0 |

**Comment by kcranston** [comment]
That's a good idea, Alan. Especially for people who want to keep the properties pan hidden, having a small popup when you hover over a node with some basic info would be helpful.

**Comment by opentreeapi** [comment]
Awesome helpful to learn many things how can i join to this.

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Abhilash](mailto:rabhilashtpt@gmail.con) |
| Upvotes | 0 |

**Comment by opentreeapi** [comment]
Please make a way to download your entire database&site so I can make a home wiki if your page gets taken down. It should show like a MediaWiki or similar.

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [AmbiguousUser](mailto:southpawgenius at the hotmail) |
| Upvotes | 0 |

**Comment by jar398** [comment]
Related to that: https://github.com/OpenTreeOfLife/opentree/issues/403

All the steps for setting up your own copy of the site are documented, and
the data is all public. The problem is that the documentation is spread
over several documents, and the procedure is bespoke (to put it mildly).
