### ISSUE TITLE
Amoebozoa is a unikont

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#110]
doi: 10.1073/pnas.1420657112
Amoebozoa, Collodictyon and Malawimonas appear as the basal unikont clade 
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [jmv2009](mailto:) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@4/Eukaryota](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@4/Eukaryota) |
| Target node label | Eukaryota |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 4 |
| Source tree id(s) | silva:D11377/#1,ncbi:2759 |
| Open Tree Taxonomy id | 304358 |
| Intended scope | Re: synthetic tree |

**Comment by mtholder** [comment]
tree queued for next synthesis run
