### ISSUE TITLE
Myceliophthora thermophila ATCC 42464 belongs in fungal class Sordariomycetes

### ISSUE THREAD

**Issue by WisecaverLab** [OpenTreeOfLife/feedback#112]
I'm not a mycologist, so I can't speak to the other species of Myceliophthora, but this strain belongs with the Chaetomiaceae in class Sordariomycetes. 

See the NCBI Taxonomy http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=573729
And the genome paper https://www.ncbi.nlm.nih.gov/pubmed/21964414 (Supplementary Figure 9 shows a species tree).  
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jen Wisecaver](https://github.com/JenWisecaver) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@3331895/Myceliophthora-thermophila-ATCC-42464](https://tree.opentreeoflife.org/opentree/opentree3.0@3331895/Myceliophthora-thermophila-ATCC-42464) |
| Target node label | Myceliophthora thermophila ATCC 42464 |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 3331895 |
| Source tree id(s) | ncbi:573729 |
| Open Tree Taxonomy id | 842620 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
species tree = http://www.nature.com/nbt/journal/v29/n10/extref/nbt.1976-S1.pdf
(we need Peter Murray-Rust's tool to convert it to Newick! @petermr)

We get our classification of the species from Index Fungorum, which was judged at one point superior to NCBI (but that may not be the case uniformly).
http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=317955

This may be a pretty involved change to the taxonomy. Best route for now would be to submit this species tree using the curator app; then at least the synthetic tree should (eventually) reflect this new information.

**Comment by mtholder** [comment]
taxon now suppressed from the tree due to major rank conflict flag
