### ISSUE TITLE
Cryptomonad position

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#113]
http://rspb.royalsocietypublishing.org/content/279/1736/2246 places cryptophytes next to archaeplastida 
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | jmv2009 |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@3843740/Chloroplastida--Rhodophyceae--](https://tree.opentreeoflife.org/opentree/opentree3.0@3843740/Chloroplastida--Rhodophyceae--) |
| Target node label | [Chloroplastida + Rhodophyceae + ...] |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 3843740 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Intended scope | Re: synthetic tree |

**Comment by mtholder** [comment]
we have a later tree from Burki et al (2016) now included in the synthesis.
