### ISSUE TITLE
Two Artiodactyl branches?

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#116]
Is there a reason that Artiodactyls are located here, as sister to both Prototheria and Monotremata, AND also found as Cetartiodactyls in the Laurasiatheria subtree?
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Tyler Elliott](mailto:tyleraelliott@gmail.com) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@764515/Amniota](https://tree.opentreeoflife.org/opentree/opentree3.0@764515/Amniota) |
| Target node label | Amniota |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 764515 |
| Source tree id(s) | ncbi:32524 |
| Open Tree Taxonomy id | 229560 |
| Intended scope |  |

**Comment by jar398** [comment]
This problem was reported in January and will be fixed the next time we
assemble a synthetic tree (
https://github.com/OpenTreeOfLife/reference-taxonomy/issues/120).

Yes, there is a reason, but it's both complicated and uninteresting.
Suffice to say that it's just an error and a fix is on the way.

**Comment by jar398** [comment]
Looks fixed to me.  Re-open if you see any problem.
