### ISSUE TITLE
Get only immediate descendants

### ISSUE THREAD

**Issue by v0-llc** [OpenTreeOfLife/feedback#117]
Hi,

First of all, thanks so much for making all of these tools available (and all of the data).

I was just wondering - is it possible to use the APIs "subtree" method (or something else I may have missed) and only return the immediate descendants of a given node. For example, to query ott 93302 (cellular organisms) and just get a Newick like "(Eukaryota, Bacteria, Archaea)cellular organisms"

Thanks for your time.

**Comment by jar398** [comment]
I don't see such a feature in the API documentation, and it's a good idea. Not sure when we can get to this.

**Comment by v0-llc** [comment]
Thanks for your response, Jonathan - and for adding the feature request.

**Comment by mtholder** [comment]
moved to api requests years ago.
