### ISSUE TITLE
Aren't all "cellular organisms" descended from some ancestral bacterium?

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#119]
The tree shows "cellular organisms" as the original node, with separate lineages for archaea, bacteria, and eukaryotes. Pardon my ignorance (this isn't remotely my field), but my understanding was some prototypical bacterial cell evolved into more complex forms, first archaea, then eukaryotes. If not, what is the current conjecture as to the "original" cellular organism? (It just seems suspicious to me that there should be three branches to the tree, seemingly not having a "single common ancestor".
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Alec](mailto:smarteralec@gmail.com) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@1/cellular-organisms](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@1/cellular-organisms) |
| Target node label | cellular organisms |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 1 |
| Source tree id(s) | ncbi:131567 |
| Open Tree Taxonomy id | 93302 |
| Intended scope |  |

**Comment by hdliv** [comment]
That is one theory but there is also a group that believes that everything derived from a eukaryote 

Excuse the brevity. Sent by my iPhone.
