### ISSUE TITLE
Fossil spp

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#120]
This is  fossil spp but not marked as such in the synth tree
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@765735/Panthera-gombaszoegensis](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@765735/Panthera-gombaszoegensis) |
| Target node label | Panthera gombaszoegensis |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 765735 |
| Source tree id(s) | gbif:5936082 |
| Open Tree Taxonomy id | 3613227 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
Fixed by
https://github.com/OpenTreeOfLife/reference-taxonomy/commit/057cb290c9dd3bc908d89556d20acd4157201bb4

will be on web site next time we do finish a synthesis.
