### ISSUE TITLE
Ornithischia

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#121]
We seem to be missing predentata here...
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [daniel](mailto:w-e-e-d@live.com) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@788770/Dinosauria](https://tree.opentreeoflife.org/opentree/opentree3.0@788770/Dinosauria) |
| Target node label | Dinosauria |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 788770 |
| Source tree id(s) | ncbi:436486 |
| Open Tree Taxonomy id | 90215 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Found it here:

https://paleobiodb.org/cgi-bin/bridge.pl?a=basicTaxonInfo&taxon_no=52978

We've made no effort to collect extinct taxa. There are some in the system
but generally they are not visible in the synthetic tree. Unlike
Saurischia, which is still alive and kicking, as far as I know, there are
no extant Predentata.

One of these days we hope to bring in extinct taxa. The hard part will be
meshing the taxonomies.
