### ISSUE TITLE
Fossil spp. - Gryphodobatis

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#123]
This is a fossil but not marked as such in the syn tree
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@980932/Gryphodobatis](https://tree.opentreeoflife.org/opentree/opentree3.0@980932/Gryphodobatis) |
| Target node label | Gryphodobatis |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 980932 |
| Source tree id(s) | gbif:4824218,irmng:1149962 |
| Open Tree Taxonomy id | 4139222 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
Note to self: should have been marked extinct by IRMNG.  not fixed yet in
2.9.​

**Comment by jar398** [comment]
OK in OTT 2.10
