### ISSUE TITLE
Fossil sp.

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#124]
This is a fossil sp, but not marked as such in the syn tree. Note that the other sp. in this genus is _not_ extinct.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@980983/Eucrossorhinus-microcuspidatus](https://tree.opentreeoflife.org/opentree/opentree3.0@980983/Eucrossorhinus-microcuspidatus) |
| Target node label | Eucrossorhinus microcuspidatus |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 980983 |
| Source tree id(s) | gbif:4964566 |
| Open Tree Taxonomy id | 3594839 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
fixed in ott 2.9 via paleodb-only-implies-extinct heuristic.

**Comment by jar398** [comment]
3594839 |   274900  |   Eucrossorhinus microcuspidatus  |   species |   gbif:4964566    |       |   extinct |
