### ISSUE TITLE
Various problems with Trygonorrhina

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#125]
In the current OTT, Trygonorrhina fasciata is wrongly synonymised with Trygonorrhina dumerilii. These are considered separate species (e.g. on fishbase). But there are other species in here that should be synonymised. Trygonorrhina gunneries is a synonym of T. fasciata, and Trygonorrhina melaleuca is now considered a synonym of Trygonorrhina dumerilii (http://www.ncbi.nlm.nih.gov/pubmed/26250000).
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@975333/Trygonorrhina](https://tree.opentreeoflife.org/opentree/opentree3.0@975333/Trygonorrhina) |
| Target node label | Trygonorrhina |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 975333 |
| Source tree id(s) | ncbi:117883,gbif:2419094,irmng:1199249 |
| Open Tree Taxonomy id | 1041304 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Trygonorhina guaneria (synonym for Trygonorrhina fasciata)    comes from worms:283064

fishbase: https://github.com/OpenTreeOfLife/reference-taxonomy/issues/172

**Comment by mtholder** [comment]
fixed in some later ott
