### ISSUE TITLE
Sphyrnidae does not include Sphyrna

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#126]
Presumably this should include Sphyrna, which is currently placed as sister
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@980801/Sphyrnidae](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@980801/Sphyrnidae) |
| Target node label | Sphyrnidae |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 980801 |
| Source tree id(s) | ncbi:376648,gbif:2207,irmng:114213 |
| Open Tree Taxonomy id | 561376 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
I suppose it's the type genus for that family, so has no choice but to
belong in the family, but NCBI is quite clear that it thinks Sphyrna is in
_Carcharhinidae_
http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=7805&lvl=3&lin=f&keep=1&srchmode=1&unlock
.
To fix this properly we'd have to get replacement classifications for both
families. Do you have a suggestion for a source taxonomy that would cover
this?

**Comment by hyanwong** [comment]
On 21 Oct 2015, at 20:26, Jonathan A Rees notifications@github.com wrote:

> I suppose it's the type genus for that family, so has no choice but to
> belong in the family, but NCBI is quite clear that it thinks Sphyrna is in
> _Carcharhinidae_
> http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=7805&lvl=3&lin=f&keep=1&srchmode=1&unlock
> .
> To fix this properly we'd have to get replacement classifications for both
> families. Do you have a suggestion for a source taxonomy that would cover
> this?

I generally rely on Fishbase, (http://www.fishbase.org/Summary/FamilySummary.php?Family=Sphyrnidae) but I�m no expert. I�ve just put in another large shark phylogeny, but it doesn�t include family names.

Can we get it corrected on NCBI instead?

Yan

**Comment by pmidford** [comment]
I'd vote for following Fishbase (Phenoscape started doing taxonomies in the first place because of issues of NCBI vs. Fishbase).

**Comment by hyanwong** [comment]
Still an issue in draft version 4.0

**Comment by mtholder** [comment]
we're probably going to move to CoL+ before we add FishBase, so I'll close this.
