### ISSUE TITLE
Contains 2 synonyms [Cestracion]

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#127]
This genus contains 2 labels for the same sp, with different spellings
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@980802/Cestracion](https://tree.opentreeoflife.org/opentree/opentree3.0@980802/Cestracion) |
| Target node label | Cestracion |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 980802 |
| Source tree id(s) | gbif:6786818,irmng:1356091 |
| Open Tree Taxonomy id | 4949781 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
which one is the nomenclaturally correct spelling?​

**Comment by hyanwong** [comment]
Not my area, which is why I didn't suggest which one. But WoRMS and Fishbase have one 'l', and from my reading, both think it should be a synonym of Heterodontus zebra (Gray, 1831) anyway http://www.marinespecies.org/aphia.php?p=taxdetails&id=298295 http://fishbase.org/Nomenclature/SynonymSummary.php?ID=12613&GSID=6559&GenusName=Cestracion&SpeciesName=philippi%20japonicus&SpecCode=746&SynonymsRef=46206

**Comment by jar398** [comment]
I think this has been fixed now. OTT 2.10, NCBI, GBIF, WoRMS, and IRMNG all have Heterodontus zebra and H. japonicus as separate species. OTT 2.10 has Cestracion philippii (two i's) as a synonym for H. zebra, C. philippi japnoicus (one i) as a synonym for H. zebra, and 
no entry for C. philippi at all (neither Fishbase nor any of our sources mention this species except by implication as the parent of C. philippi japonicus).

I think this is good enough. OK to close?
