### ISSUE TITLE
Canis lupus italicus and Canis simensis

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#129]
I think you forgot C. l. italicus, the Italian subpecies http://www.iucnredlist.org/details/3746/1
I'm not sure that the Ethiopian Wolf (Canis simensis) must be in that placement. http://www.ncbi.nlm.nih.gov/pubmed/7921357
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Nicola](mailto:web@empusa.it) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@766318/Canidae](https://tree.opentreeoflife.org/opentree/opentree3.0@766318/Canidae) |
| Target node label | Canidae |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 766318 |
| Source tree id(s) | ncbi:9608,gbif:9701,irmng:104585 |
| Open Tree Taxonomy id | 770319 |
| Intended scope |  |

**Comment by jar398** [comment]
The article is: Gottelli et al. 1994,
Molecular genetics of the most endangered canid: the Ethiopian wolf Canis simensis,
http://dx.doi.org/10.1111/j.1365-294X.1994.tb00070.x

It contains a phylogenetic tree with 9 tips - would not take long to make a Newick out of it and enter it using the curator app.

**Comment by mtholder** [comment]
*Canis simensis* has been added we'll probably have to wait until we start using CoL+ to get more wolf subspecies.
