### ISSUE TITLE
Fossil clade with obsolete name

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#132]
This clade is the old name for Alytidae, which exists elsewhere in the OpenTree. Currently, the only 3 species listed under Discoglossidae in the OpenTree are fossils, which have presumably been picked up from an outdated fossil database. 
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@740302/Discoglossidae](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@740302/Discoglossidae) |
| Target node label | Discoglossidae |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 740302 |
| Source tree id(s) | gbif:3241294,irmng:104231 |
| Open Tree Taxonomy id | 991545 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
This is remedied in OTT 2.9 (we picked up the synonymization somewhere)
