### ISSUE TITLE
Fossil genus in wrong place [Cordicephalus]

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#133]
This should not appear in the tree, as it is an extinct genus. Even if it is in the tree, taxonomy places it in the Pipoidea, not at the root of the Anura.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@740308/Cordicephalus](https://tree.opentreeoflife.org/opentree/opentree3.0@740308/Cordicephalus) |
| Target node label | Cordicephalus |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 740308 |
| Source tree id(s) | gbif:3241310,irmng:1439772 |
| Open Tree Taxonomy id | 4948379 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
This seems to be fixed already in OTT 2.9.
Cordicephalus(4948379)
 genus size:2
(4948379=gbif:3241310+1 Cordicephalus?) << (991547=ncbi:8342+437 Anura) <
(471197=ncbi:41666+2 Batrachia) < (544595=ncbi:8292+755 Amphibia) <
(229562=ncbi:32523+2 Tetrapoda) < (4940726=ncbi:1338369+2
Dipnotetrapodomorpha) < (458402=ncbi:8287+37 Sarcopterygii) <
(114654=ncbi:117571+2 Euteleostomi) < (114656=ncbi:117570+1 Teleostomi) <
(278114=ncbi:7776+4 Gnathostomata) ...
Cordicephalus gracilis(4948380) species
Sources: gbif:3241310,irmng:1439772
Flags: major_rank_conflict

**Comment by jar398** [comment]
Unfixed by later changes. Added test...

**Comment by mtholder** [comment]
fixed before 3.6
