### ISSUE TITLE
Fossil genus [Hemitrypus]

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#134]
This is a fossil genus but not marked as such, and hence accidentally appears in the tree.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@761496/Hemitrypus](https://tree.opentreeoflife.org/opentree/opentree3.0@761496/Hemitrypus) |
| Target node label | Hemitrypus |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 761496 |
| Source tree id(s) | gbif:4816542,irmng:1451155 |
| Open Tree Taxonomy id | 3620678 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Usually IRMNG tells us when a genus it provides is extinct, but this time
it didn't.

**Comment by jar398** [comment]
Looks OK in OTT 2.10
