### ISSUE TITLE
Fossil sp. Cryptobranchus matthewi

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#135]
Not yet flagged as fossil, so mistakenly appears in tree
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@761736/Cryptobranchus-matthewi](https://tree.opentreeoflife.org/opentree/opentree3.0@761736/Cryptobranchus-matthewi) |
| Target node label | Cryptobranchus matthewi |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 761736 |
| Source tree id(s) | gbif:4964853 |
| Open Tree Taxonomy id | 3620512 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Fixed in OTT 2.9
