### ISSUE TITLE
Probable misspelling ['Galeolerdo vouncus']

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#137]
? should be Galeocerdo aduncus (fossil species?)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@980018/Galeolerdo-vouncus](https://tree.opentreeoflife.org/opentree/opentree3.0@980018/Galeolerdo-vouncus) |
| Target node label | Galeolerdo vouncus |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 980018 |
| Source tree id(s) | irmng:11031008 |
| Open Tree Taxonomy id | 5517907 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
I believe you're right, thanks.  Looks like an OCR error to me.  I think a
correction to IRMNG would be in order. IRMNG says the source of the name is
'Museum Victoria KEmu database', and here is what the source's web site
says:

http://collections.museumvictoria.com.au/search?query=Galeocerdo

**Comment by hyanwong** [comment]
On 22 Oct 2015, at 23:22, Jonathan A Rees notifications@github.com wrote:

> I believe you're right, thanks. Looks like an OCR error to me. I think a
> correction to IRMNG would be in order. 

Good - can you drop them a line somehow?

Yan

**Comment by jar398** [comment]
I'll be sending Tony a batch of changes at some point, including this one.
​
