### ISSUE TITLE
Should be only one species in Galeocerdo

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#138]
This is a monotypic genus. Galeocerdo cuvier is the only extant member (see http://www.fishbase.org/identification/SpeciesList.php?genus=Galeocerdo). Are the others listed in the OpenTree fossils, by any chance?
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@980013/Galeocerdo](https://tree.opentreeoflife.org/opentree/opentree3.0@980013/Galeocerdo) |
| Target node label | Galeocerdo |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 980013 |
| Source tree id(s) | ncbi:7818,gbif:2418233,irmng:1027171 |
| Open Tree Taxonomy id | 976353 |
| Intended scope | Re: OTT taxon |

**Comment by pmidford** [comment]
Catalog of Fishes agrees, but IRMNG gives ambiguous results for G.davisi
and G. vouncus.  The rest seem to be fossil.

**Comment by hyanwong** [comment]
On 22 Oct 2015, at 22:31, Peter E. Midford notifications@github.com wrote:

> Catalog of Fishes agrees, but IRMNG gives ambiguous results for G.davisi
> and G. vouncus. The rest seem to be fossil.

I think vouncus is a misspelling: see my comment on that node.

**Comment by jar398** [comment]
As I've said I'm proposing to leave out all IRMNG-only taxa. That would remove vouncus, latidens, and minor. That leaves 'Galeocerdo cf. cuvier GJPN-2012' from NCBI. This is a "bio-material" and doesn't belong in the taxonomy. It would be expecting an awful lot of smasher to be able to figure that out, so I'm just going to prune that one taxon.

**Comment by jar398** [comment]
Looks OK now
