### ISSUE TITLE
Empty non-monophyletic clade [Prasinophyta]

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#139]
Prasinophyta is empty, and should probably be deleted as it is considered non-monophyletic anyway
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@25748/Prasinophyta](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@25748/Prasinophyta) |
| Target node label | Prasinophyta |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 25748 |
| Source tree id(s) | gbif:104 |
| Open Tree Taxonomy id | 4737182 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Without some other story about what the parents of all of its children should be, I think I'm going to leave it as is; the classification comes from NCBI. Indeed it does come out paraphyletic in the synthetic tree.
https://tree.opentreeoflife.org/taxonomy/browse?name=Prasinophyta

**Comment by hyanwong** [comment]
Missing from 12.3 anyway
