### ISSUE TITLE
Family [Ichthyophonae] not in correct order

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#140]
The family Ichthyophonae should be within the Order Ichthyophonida, instead of a sister group.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@702687/Ichthyosporea](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@702687/Ichthyosporea) |
| Target node label | Ichthyosporea |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 702687 |
| Source tree id(s) | silva:L29455/#4,ncbi:127916,gbif:185,irmng:1311 |
| Open Tree Taxonomy id | 623671 |
| Intended scope | Re: OTT taxon |

**Comment by mtholder** [comment]
will be fixed in OTT3.7.2
