### ISSUE TITLE
Misspelling [Aotus azarae]

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#142]
Should be Aotus azarae
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@778090/Aotus-azarai](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@778090/Aotus-azarai) |
| Target node label | Aotus azarai |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 778090 |
| Source tree id(s) | ncbi:30591,gbif:5219596,irmng:10228020 |
| Open Tree Taxonomy id | 1058659 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
The spelling we have comes from NCBI, and NCBI seems pretty sure that it's
azarai... but every other source I checked has azarae, including all of the
linkouts from the NCBI record. So this change should be made.

OTT does have azarae as a synonym; that's how the match was made to GBIF
and IRMNG.
