### ISSUE TITLE
Missing Alouatta nigerrima here

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#143]
or even the other name for it, if a subspp, Alouatta belzebul nigerrima (see http://www.iucnredlist.org/details/136332/0)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@777968/Alouatta-belzebul](https://tree.opentreeoflife.org/opentree/opentree3.0@777968/Alouatta-belzebul) |
| Target node label | Alouatta belzebul |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 777968 |
| Source tree id(s) | ncbi:30590,gbif:2436655,irmng:11032813 |
| Open Tree Taxonomy id | 1058654 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
I poked around the red list site a bit and couldn't find a download link
for the species list or taxonomy. Do you know how to get machine readable
versions of these things?

**Comment by hyanwong** [comment]
On 27 Oct 2015, at 01:29, Jonathan A Rees notifications@github.com wrote:

> I poked around the red list site a bit and couldn't find a download link
> for the species list or taxonomy. Do you know how to get machine readable
> versions of these things?

No, sorry. That would be useful. I�ll ask someone I know, but might take a while for a reply. IUCN can oddly possessive of their data.

**Comment by mtholder** [comment]
will be fixed in ott 3.7.2 with https://www.gbif.org/species/4267236
