### ISSUE TITLE
Spelling mistakes cause multiple versions of a species

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#145]
This node has a number of misspelt 'Cephalorhyncus; (without the extra h), which should all be synonymised with Cephalorhynchus.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@3866703/Cephalorhynchus-commersonii--Cephalorhyncus-hectori--](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@3866703/Cephalorhynchus-commersonii--Cephalorhyncus-hectori--) |
| Target node label | [Cephalorhynchus commersonii + Cephalorhyncus hectori + ...] |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 3866703 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
here is the complete non-h list as of OTT 2.9:

5555452 | 753972 | Cephalorhyncus hectori | species | irmng:10676798 | | |
5555455 | 753972 | Cephalorhyncus commersonii | species | irmng:11398201 | |
|
5555453 | 753972 | Cephalorhyncus eutropia | species | irmng:11018789 | | |
5555451 | 753972 | Cephalorhyncus heavisidii | species | irmng:10674157 | |
|
