### ISSUE TITLE
Minor search issue: cannot get results is search includes apostrophe

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#148]
On the website, try searching, e.g. for "Eumimesis d'almeidai": The species appears as a drop down, but the link is invalid.

**Comment by jimallman** [comment]
Thanks for catching this! It looks like the app is confused by the apostrophe in this URL:
- https://tree.opentreeoflife.org/opentree/argus/ottol@5545324/Eumimesis-d'almeidai

... while it has no trouble with these truncated versions:
- https://tree.opentreeoflife.org/opentree/argus/ottol@5545324/Eumimesis-dalmeidai
- https://tree.opentreeoflife.org/opentree/argus/ottol@5545324/Eumimesis

We clean up taxon names to make them URL-compatible, but obviously this needs more work.

**Comment by jar398** [comment]
In OTT 2.9 this name is a synonym, so the problem will go away.

There's code in the taxonomy build to convert names to a form allowed by
the nomenclatural codes, e.g. umlauts and other decorations are removed.
Apostrophes should also be removed, so this reflects a taxonomy bug.

I find 19 non-synonym binomials like this in 2.9. In the case
of Antodynerus o'neili (one of three that I checked) there is another name,
clearly a synonym, that's the same minus the apostrophe. Some of these are
OCR errors.

Alcide D'Orbigny appears to have been highly esteemed.

5550727 | 4537503 | Odynerus o'neili | species | irmng:11146683 | | |
5550694 | 4535310 | Antodynerus o'neili | species | irmng:10802443 | | |
5557258 | 4276380 | Pseudosoloe n'tebi | species | irmng:10298840 | | |
5560173 | 313066 | Ornithoptera d'urvilliana | species | irmng:10654170 | |
|
5559341 | 3122673 | Perisama d'orbignyi | species | irmng:11123493 | | |
5559438 | 827963 | Arsenura d'orbignyana | species | irmng:11267599 | | |
5557896 | 539861 | Amata n'tebi | species | irmng:10777406 | | |
5557245 | 4244111 | Scalmicauda o'neili | species | irmng:10334702 | | |
5557008 | 680274 | Xyleutes d'urvillei | species | irmng:11052744 | | |
5775623 | 2964955 | Paracytheridea shoa'lriverensis | species | worms:791451
| | sibling_higher,extinct |
5500704 | 2922148 | Rissoina d'orbignyi | species | irmng:11443934 | |
incertae_sedis_inherited |
5500700 | 2922148 | Rissoina d'orbiguyi | species | irmng:10795106 | |
incertae_sedis_inherited |
5499472 | 2912591 | Pisania d'orbignyi | species | irmng:10903224 | | |
5493363 | 406406 | Karkinorhynchus l'hardyi | species | irmng:10816327 | | |
5448472 | 4148286 | Pentremites d'orbignyanus | species | irmng:10537862 | |
major_rank_conflict_inherited,extinct,extinct_inherited |
5353886 | 67598 | Ellipsolagena d'orbignyana | species | irmng:11084160 | |
hidden |
5411436 | 3854689 | Staurastrum o'mearii | species | irmng:11852030 | | |
5406531 | 5267466 | Lenticulina d'orbignii | species | irmng:11751029 | |
hidden |
5406539 | 5267466 | Lenticulina d'orbignyii | species | irmng:11827368 | |
hidden |

**Comment by hyanwong** [comment]
There are loads of other taxa with quotes in, though, especially in the bacteria. E.g. uncultured_archeon_'KTK_9A'_ott5208482, Iranian_Almond_witches'-broom_phytoplasma_ott626297. Are you thinking of removing all the quotes from those too? It doesn't really seem necessary to do so to me.

**Comment by jimallman** [comment]
> Are you thinking of removing all the quotes from those too?

This is not necessary in the taxonomy, just in the client-side code that turns names into URLs. Web2py (our webapp framework) is confused by URLs with some characters in them, and I'd neglected to clean these up. I'm working on a fix now...

**Comment by jar398** [comment]
No, I was only talking about the binomials.
(and I suppose trinomials, and genus names, but I don't think there are any
of these.)

The pattern I was thinking of using is: lower case letter followed by
apostrophe followed by two lower case letters, AND the string 'virus' does
not occur in the name (to deal with things like Norovirus
Hu/GII.4/Xi'an/P154/2010/CHN )

**Comment by hyanwong** [comment]
Yes indeed. FYI `grep -Eo ".{20}''.{20}" OpenTree/draftversion3.tre | wc` gives 4717 hits.

**Comment by jimallman** [comment]
I'm removing single _and_ double quotes from the taxon URLs, to be on the safe side. We can add other problematic characters as needed to `makeSafeForWeb2pyURL()`, [as shown here](https://github.com/OpenTreeOfLife/opentree/pull/799/files).

This is fixed and working now on **devtree**. It will appear in the next push to production.
