### ISSUE TITLE
This node is called 'Afrosoricida"

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#149]
Just a small nomenclature addition
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |

**Comment by hyanwong** [comment]
Link to node is https://tree.opentreeoflife.org/opentree/opentree4.0@3449690. Ref for name is e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC21445/ (e.g. as in http://animaldiversity.org/accounts/Afrosoricida/)

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/963413a91580e40a080358474b600fa4662a5a5f
