### ISSUE TITLE
Taxonomic level ('division') seems to be wrongly incorporated into name

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#150]
This should presumably be just "Dikarya" as in OTT 2.8. Also see e.g. "Phyllum=Entorrhizomycota" (sic)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |

**Comment by jar398** [comment]
already fixed in OTT 2.10

**Comment by hyanwong** [comment]
Thanks. Closing
