### ISSUE TITLE
Node name = Ambulacraria

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#151]
The standard name for the node containing Echinodermata and Hemichordata is Ambulacraria
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |

**Comment by hyanwong** [comment]
Current link is https://tree.opentreeoflife.org/opentree/opentree4.0@3451708/Echinodermata--Hemichordata, ref for name is http://link.springer.com/article/10.1007%2Fs13127-011-0044-4

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/14a6b33fd39461b37b95930cf4c6dd189b8701c7
