### ISSUE TITLE
Grouping of Acoela + Nemertodermatida officially known as Acoelomorpha

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#153]
Acoelomorpha appears in draftversion3 of the OpenTree, but in the wrong place. It should be here.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |

**Comment by hyanwong** [comment]
For reference, see e.g. https://en.wikipedia.org/wiki/Acoelomorpha and references therein (e.g. Nielsen, C. (2012). Animal Evolution (3rd ed.).)

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/11e6c90b70839c4d3ba8303fa93f23c32b551b4c
