### ISSUE TITLE
Castoridae + Geomyidae + Heteromyidae known as Suborder Castorimorpha

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#155]
The node can be labelled 'Castorimorpha'
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |

[  http://animaldiversity.org/accounts/Castorimorpha/classification/ http://www.departments.bucknell.edu/biology/resources/msw3/browse.asp?id=12600001 ]

**Comment by hyanwong** [comment]
e.g. http://animaldiversity.org/accounts/Castorimorpha/classification/ http://www.departments.bucknell.edu/biology/resources/msw3/browse.asp?id=12600001

**Comment by mtholder** [comment]
fixed in newer OTT by NCBI update

**Comment by hyanwong** [comment]
Thanks for following up (and fixing) a whole load of these issues @mtholder
