### ISSUE TITLE
Erinaceidae should be sole family in genus Erinaceomorpha

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#156]
There should probably be another unifurcating node in here for the order 'Erinaceomorpha', although this is more of a taxonomic feature than a phylogenetic one. It would help, however, to be able to search OTT for 'Erinaceomorpha', which is currently not returned via search or TNRS API
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |

**Comment by jar398** [comment]
Erinaceomorpha is "merged,barren" so is covered by
https://github.com/OpenTreeOfLife/taxomachine/pull/110

**Comment by jar398** [comment]
Erinaceomorpha does seem to be found by the TNRS. Looks to me like NCBI and GBIF disagree on how to carve up Insectivora. Currently GBIF [Erinaceomorpha](https://tree.opentreeoflife.org/taxonomy/browse?name=Erinaceomorpha) is considered inconsistent with NCBI. If it should be preserved then we'll need to look very carefully at what's going on as other groups may be affected.

@hyanwong  can I close this issue or do you Insectivora needs this kind of work?

**Comment by hyanwong** [comment]
Ah - more complex than I imagined. So best to just close this, I think, especially now that it is mapped in TNRS. Apologies for the duff issue.
