### ISSUE TITLE
Search for 'Vespadelus' returns no hits

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#157]
Even though several Vespadelus species such as this one appear in the tree. It is not even present as a non-monophyletic taxon (e.g. https://devtree.opentreeoflife.org/opentree/argus/ottol@909559/Squatina)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |

**Comment by jar398** [comment]
Here's what OTT 2.9 has:

3614135 | 10727 | Vespadelus | genus | gbif:4266260,irmng:1452573 | Vespadelus
(merged with Eptesicus) | merged,barren |

Now I'm not sure _why_ it got merged, but I bet it's that some of the
species (maybe from NCBI) were synonymized with Eptesicus species, and
smasher decided there was no way to disentangle the two genera. (The logic
here is sort of complex but it tries hard not to make potentially
paraphyletic groups.) Example:

Vespadelus regulus | 383887 | | Vespadelus regulus (synonym for Eptesicus
regulus) |

I think the only fix is to incorporate a modern, comprehensive mammal list.
I gather the current list is quite old and a new one is preparation.
Another thing to research...

**Comment by hyanwong** [comment]
On 6 Nov 2015, at 02:04, Jonathan A Rees notifications@github.com wrote:

> Now I'm not sure _why_ it got merged, but I bet it's that some of the
> species (maybe from NCBI) were synonymized with Eptesicus species, and
> smasher decided there was no way to disentangle the two genera. (The logic
> here is sort of complex but it tries hard not to make potentially
> paraphyletic groups.) Example:

I�m fine with it not appearing as a genus on the synth tree. But _something_ (even a synonym) should be returned when querying the TNRS for a genus whose species do appear on the tree.

**Comment by jar398** [comment]
Here's the culprit in OTTFlag.java:

BARREN ("barren", false),

I hadn't realized these were turned off - they shouldn't be.  Enabling
'barren' (i.e. species-free) taxa will also expose a ton of extinct taxa,
so this should be a good thing.  I wonder if Cody had a reason to exclude
these?

I've piggybacked a fix onto
https://github.com/OpenTreeOfLife/taxomachine/pull/110.

Thanks for the catch (although I'm not sure what you intend to do with
these identifiers).

**Comment by jar398** [comment]
Now returned by TNRS: https://tree.opentreeoflife.org/taxonomy/browse?name=Vespadelus  Unfortunately it comes from GBIF in a way that doesn't partition NCBI, so it appears as a child of the NCBI taxon it got merged into. (I'm considering turning the 'merged' and 'inconsistent' nodes into things that look a lot more like synonyms; but without a change to the TNRS the reason for loss won't be visible, so I'm reluctant to change the way it works now.)
