### ISSUE TITLE
Obsolete synonym [Galeopithecidae]

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#158]
I think this is an obsolete synonym for a clade containing the Dermoptera plus some fossil taxa (http://fossilworks.org/bridge.pl?a=taxonInfo&taxon_no=40330). It certainly shouldn't be an orphan here.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@3607827/Galeopithecidae](https://tree.opentreeoflife.org/opentree/argus/ottol@3607827/Galeopithecidae) |
| Target node label | Galeopithecidae |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1383850 |
| Source tree id(s) | gbif:4827503,irmng:102430 |
| Open Tree Taxonomy id | 3607827 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Not sure if there's anything I need to do to the taxonomy: https://tree.opentreeoflife.org/taxonomy/browse?name=Galeopithecidae - I'd prefer not to get into detailed study of extinct taxa right now.

It should be gone from the synthetic tree now that the following is in place:
https://github.com/OpenTreeOfLife/peyotl/issues/151

We don't have a place to put a test for something not being in the tree, so we can either close this now, or wait until someone has checked it.

**Comment by hyanwong** [comment]
Correctly missing from 11.4
