### ISSUE TITLE
Node known as 'Atlantogenata'

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#161]
See e.g. https://en.wikipedia.org/wiki/Atlantogenata and references therein.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@3436550/Afrotheria--Xenarthra](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@3436550/Afrotheria--Xenarthra) |
| Target node label | [Afrotheria + Xenarthra] |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 3436550 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Intended scope | Re: OTT taxon |

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/68a7d2206c8809f9b844e85ac04a52bf138be5ad
