### ISSUE TITLE
Fossil taxon [Cephalaspidomorphi]

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#162]
Cephalaspidomorphi is extinct (https://en.wikipedia.org/wiki/Cephalaspidomorphi), or alternatively, another name for lampreys (http://animaldiversity.org/accounts/Cephalaspidomorphi/classification/). Either way, it should not appear as an empty taxon here
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@1549083/Cephalaspidomorphi](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@1549083/Cephalaspidomorphi) |
| Target node label | Cephalaspidomorphi |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1549083 |
| Source tree id(s) | worms:10190,gbif:239,irmng:1371 |
| Open Tree Taxonomy id | 5292392 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Should be gone from synthesis next round via https://github.com/OpenTreeOfLife/peyotl/issues/151 .

There's some funny business with Ateleaspididae (extinct but marked so) which is imported from GBIF and ought also to be imported from IRMNG but isn't. So I'll leave this open for now.

**Comment by mtholder** [comment]
will be fixed with extinct flag from https://github.com/OpenTreeOfLife/edOTTs/commit/0faf0f5a66fb043bb9e27a2d6dde017c9f41a214
