### ISSUE TITLE
Anaua is homonym, species transferred to Uzakia

### ISSUE THREAD

**Issue by pmidford** [OpenTreeOfLife/feedback#163]
IRMNG placement is based on outdated World Spider Catalog via CoL.  Current WSC [shows updated placement](http://www.wsc.nmbe.ch/genus/694). 
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Peter E. Midford](https://github.com/pmidford) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@1799284/Araneae](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@1799284/Araneae) |
| Target node label | Araneae |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1799284 |
| Source tree id(s) | ncbi:6893,worms:150467,gbif:1496,irmng:12065 |
| Open Tree Taxonomy id | 614523 |
| Intended scope | Re: OTT taxon |

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/b22555660e4739f5a97c79a44083fce0fef1955d
