### ISSUE TITLE
This is a deprecated taxon, ['Treptoplax reptans']

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#166]
Usually considered a misidentification. See http://www.marinespecies.org/placozoa/aphia.php?p=taxdetails&id=142020 which states "Validity "Treptoplax" is an artifact rather than an accepted Genus or species."
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@1320333/Treptoplax-reptans](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@1320333/Treptoplax-reptans) |
| Target node label | Treptoplax reptans |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1320333 |
| Source tree id(s) | irmng:10821050 |
| Open Tree Taxonomy id | 5394914 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
IRMNG thinks it's a valid name. Imported to IRMNG from WoRMS in 2013. But not in our harvest of WoRMS. So probably corrected recently by WoRMS and IRMNG is stale.

**Comment by mtholder** [comment]
hidden in previous OTT
