### ISSUE TITLE
This and P. altus are probably spelling variants

### ISSUE THREAD

**Issue by pmidford** [OpenTreeOfLife/feedback#167]
Original description used P. alta, which WSC seems to have emended to P. altus.  IRMNG has both (http://www.marine.csiro.au/mirrorsearch/ir_search.list_species?gen_id=1198061).
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Peter E. Midford](https://github.com/pmidford) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree4.0@1800551/Plectophanes-alta](https://tree.opentreeoflife.org/opentree/opentree4.0@1800551/Plectophanes-alta) |
| Target node label | Plectophanes alta |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1800551 |
| Source tree id(s) | irmng:10740634 |
| Open Tree Taxonomy id | 4696001 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
ok in OTT 2.10 (although unfortunately there's no forwarding id for alta's old OTT id)
