### ISSUE TITLE
Taxon concept correction: Arachnides

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#168]
curl -X POST http://api.opentreeoflife.org/v2/tnrs/contexts : 'Arachnides' is presumably a misspelling for 'Arachnids' (unless you are French).

**Comment by pmidford** [comment]
I wondered about that when I added it.  It seems to be gone in the current
build.

**Comment by hyanwong** [comment]
"current build"? I get it using both api.opentreeoflife.org/v2/tnrs and devapi.opentreeoflife.org/v2/tnrs

**Comment by pmidford** [comment]
Misread, +1 to fixing this.

**Comment by mtholder** [comment]
fixed in previous OTT
