### ISSUE TITLE
'Apusozoa' should either include more taxa, or should not exist in the tree

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#170]
refs therein, e.g. http://www.sciencedirect.com/science/article/pii/S1434461008000424. These seem to be missing from the v4 synth tree. Note however that Apusozoa is probably non-monophyletic, so there is an argument for nixing the label entirely.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree4.0@352887/Apusozoa](https://tree.opentreeoflife.org/opentree/opentree4.0@352887/Apusozoa) |
| Target node label | Apusozoa |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 352887 |
| Source tree id(s) | ncbi:554296,worms:582162,irmng:129 |
| Open Tree Taxonomy id | 671092 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Apusozoa is now merged into Apusomonadidae.
https://devtree.opentreeoflife.org/taxonomy/browse?id=575898
