### ISSUE TITLE
Apparently synonymized with Indicoblemma

### ISSUE THREAD

**Issue by pmidford** [OpenTreeOfLife/feedback#171]
Another IRMNG taxon based on 2006 WSC.  Current WSC shows merge (http://www.wsc.nmbe.ch/genus/3251)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Peter E. Midford](https://github.com/pmidford) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree4.0@1799971/Chavia](https://tree.opentreeoflife.org/opentree/opentree4.0@1799971/Chavia) |
| Target node label | Chavia |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1799971 |
| Source tree id(s) | gbif:4658166,irmng:1321296 |
| Open Tree Taxonomy id | 4696261 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Is WSC something we could import?​

**Comment by pmidford** [comment]
Sadly, the homepage (http://www.wsc.nmbe.ch/) doesn't look very
promising.  It may have been different when it was hosted at AMNH, as
IRMNG sees to have a lot of material from a 2006 version.

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/037776d68229259f270bc4a81380e0d7978b1f1e
