### ISSUE TITLE
Compsospiza should be reinstated

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#173]
At the moment OpenTree has Compsospiza as a synonym of Poospiza, but it should be in its own genus, according to http://www.iucnredlist.org/details/22723269/0. Also in this genus, Compsospiza baeri is missing from the taxonomy.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |

**Comment by jar398** [comment]
If I've read the IOC site correctly, this will be fixed by
https://github.com/OpenTreeOfLife/reference-taxonomy/issues/173

**Comment by mtholder** [comment]
seems like in the intervening 9 years this issue has been open, the consensus has shifted back to making *Compsospiza* a jr. syn. of *Poospiza*
