### ISSUE TITLE
the first organism

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#175]
The first organism was Primisima uniata (prvnička jediná) DOKOUPIL.

Dokoupil Martin Ing.: Linguistic.

Thanks for write of this to Your tree.

Martin
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Dokoupil Martin Ing.](mailto:M.Dokoupil@email.cz) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@1](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@1) |
| Target node label | cellular organisms |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1 |
| Source tree id(s) | ncbi:131567 |
| Open Tree Taxonomy id | 93302 |
| Intended scope |  |

**Comment by jar398** [comment]
This project only covers cellular organisms, so any earlier organisms would be out of scope. Also we require some kind of citation for any information provided, and I am not aware of any empirical phylogenetic or taxonomic studies covering pre-cellular life.
