### ISSUE TITLE
Amia fasciata is a 'doubtful species'

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#177]
Probably based on 'Amia fasciata stevensi McCulloch, 1915' which is a synonym for Ostorhinchus taeniophorus (http://www.marinespecies.org/aphia.php?p=taxdetails&id=298228) and NOT a bowfin. There is generally only one accepted species of extant bowfin, Amia calva: http://www.fishbase.org/summary/FamilySummary.php?ID=35
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@1548746/Amia-fasciata](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@1548746/Amia-fasciata) |
| Target node label | Amia fasciata |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1548746 |
| Source tree id(s) | gbif:5723000,irmng:10753298 |
| Open Tree Taxonomy id | 3644062 |
| Intended scope | Re: OTT taxon |

**Comment by hyanwong** [comment]
Also see https://github.com/OpenTreeOfLife/feedback/issues/43

**Comment by jar398** [comment]
What's your pleasure - prune it from the taxonomy, or make it a synonym for Ostorhinchus taeniophorus ?

**Comment by hyanwong** [comment]
Since it's a synonym in fishbase (http://www.fishbase.org/Nomenclature/SynonymsList.php?ID=5767&SynCode=165242&GenusName=Ostorhinchus&SpeciesName=taeniophorus), it's probably more than a simple mistake, so I guess make it a synonym (although it seems to be an outdated, invalid one - not sure if OToL make that distinction?)

**Comment by mtholder** [comment]
fixed in previous OTT
