### ISSUE TITLE
Hylobates alibarbis is a typo

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#184]
This should be removed. It is a typo for Hylobates albibarbis, which appears close by in the tree. https://tree.opentreeoflife.org/opentree/opentree4.0@1384818/Hylobates-albibarbis
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree4.0@1384831/Hylobates-alibarbis](https://tree.opentreeoflife.org/opentree/opentree4.0@1384831/Hylobates-alibarbis) |
| Target node label | Hylobates alibarbis |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1384831 |
| Source tree id(s) | ncbi:716691 |
| Open Tree Taxonomy id | 96942 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
unusual case where GBIF gets it right and NCBI gets it wrong.​
