### ISSUE TITLE
Korarchaeota is empty

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#185]
Presumably there should be NCBI samples in here, as well as Candidatus Korarchaeum cryptofilum, e.g. as in http://www.ncbi.nlm.nih.gov/pubmed/22574130
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree4.0@352879/Korarchaeota](https://tree.opentreeoflife.org/opentree/opentree4.0@352879/Korarchaeota) |
| Target node label | Korarchaeota |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 352879 |
| Source tree id(s) | silva:AB301892/#2,ncbi:51967,worms:559427,irmng:220 |
| Open Tree Taxonomy id | 266344 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
I don't think so. All of the children (in OTT 2.9 at least) are in
categories that we currently suppress for synthesis: incertae sedis,
uncultured, and so on.  There are no direct children that pass muster.

**Comment by jar398** [comment]
There's a bug that has been noted elsewhere: if a taxon has only one child and that child has a name of the form *incertae sedis, then we should elide the *incertae sedis from the tree.
Fixing that might help. https://github.com/OpenTreeOfLife/reference-taxonomy/issues/210

**Comment by hyanwong** [comment]
This is now on the devtree https://devtree.opentreeoflife.org/opentree/argus/ottol@266344/Korarchaeota, so this issue can be closed
