### ISSUE TITLE
Taxonomically inaccurate spp. [Raphus solitarius]

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#186]
This is not a dodo / pigeon relative, but now placed as an ibis (https://en.wikipedia.org/wiki/Réunion_ibis). And extinct, of course.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@1415083/Raphus-solitarius](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@1415083/Raphus-solitarius) |
| Target node label | Raphus solitarius |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1415083 |
| Source tree id(s) | gbif:2496197,irmng:11355059 |
| Open Tree Taxonomy id | 3596700 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
I think this is fixed: https://tree.opentreeoflife.org/taxonomy/browse?name=Raphus+solitarius
