### ISSUE TITLE
Craniata + Tunicata is known as Olfactores

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#188]
This node is probably well accepted enough now to be given a name on the OpenTree, which is conventionally 'Olfactores ': see e.g. http://www.nature.com/nature/journal/v439/n7079/full/nature04336.html
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@3448421](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@3448421) |
| Target node label | [Craniata + Tunicata] |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 3448421 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Intended scope | Re: OTT taxon |

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/f217eab5d3aedb93a9d231862d893255aba9e2f3
