### ISSUE TITLE
Crenarchaeota duplicated

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#189]
This node is a synonym of https://tree.opentreeoflife.org/opentree/argus/ottol@114216/Crenarchaeota-phylum-silva-D14053
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@5574956/Crenarchaeota-in-phylum-Thaumarchaeota-](https://tree.opentreeoflife.org/opentree/argus/ottol@5574956/Crenarchaeota-in-phylum-Thaumarchaeota-) |
| Target node label | Crenarchaeota |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 352803 |
| Source tree id(s) | ncbi:28889,silva:CQ786497 |
| Open Tree Taxonomy id | 5574956 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
This node (OTT 5574956 = NCBI 28889) seems to gone from the taxonomy now (OTT 2.10), but there remains 820306 (= NCBI 183924), which is called Thermoprotei but has 'Crenarcheota' as a synonym. The synonym comes from NCBI. Someone needs to investigate whether this is a correct homonym, and if NCBI is in error, someone should send email to NCBI...

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/97a0f5bf55f077416745b0612e37c5eee396f366
