### ISSUE TITLE
Rhizobium leguminosarum duplicated

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#190]
also at https://tree.opentreeoflife.org/opentree/argus/ottol@5283395/Rhizobium-leguminosarum-ncbi-754774-
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@5283396/Rhizobium-leguminosarum-ncbi-385-](https://tree.opentreeoflife.org/opentree/argus/ottol@5283396/Rhizobium-leguminosarum-ncbi-385-) |
| Target node label | Rhizobium leguminosarum |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 90030 |
| Source tree id(s) | ncbi:385,silva:U29388 |
| Open Tree Taxonomy id | 5283396 |
| Intended scope | Re: source tree |

**Comment by mtholder** [comment]
fixed in previous OTT
