### ISSUE TITLE
Example d3 visualizations broken

### ISSUE THREAD

**Issue by jrbotros** [OpenTreeOfLife/feedback#193]
Looks like the example d3 visualizations aren't working (e.g., http://files.opentreeoflife.org/other/taxa_viz_dyn.html?ottolID=805080).

<img width="821" alt="screen shot 2016-01-30 at 11 35 23 am" src="https://cloud.githubusercontent.com/assets/2992765/12696993/18826aec-c746-11e5-8290-3264c7698476.png">

**Comment by mtholder** [comment]
thanks for pointing that out. That is deprecated. We should note it as such. 
If you want to browse the taxonomy (not with d3) you can check out: https://tree.opentreeoflife.org/taxonomy/browse?id=805080

**Comment by jrbotros** [comment]
Ah, got it—thanks for the quick response!
