### ISSUE TITLE
Taxon search fails for 'sparkly unicorn'

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/feedback#2]
I think all xenomorphs should be included here.

**Comment by opentreeapi** [comment]
foo test
None

**Comment by opentreeapi** [comment]
one more time
None

**Comment by opentreeapi** [comment]
one more time
None

**Comment by opentreeapi** [comment]
one more time
None

**Comment by opentreeapi** [comment]
another footer test

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | <Row {'first_name': 'Jim', 'last_name': 'Allman', 'registration_id': u'https://www.google.com/profiles/114097318788057975256', 'email': u'jim@ibang.com', 'reset_password_key': '', 'registration_key': '', 'id': 11L}> |
| Upvotes | 0 |
