### ISSUE TITLE
TEST of new new

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/feedback#208]
Adding another (to existing page)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jim Allman](https://github.com/jimallman) |
| Upvotes | 0 |
| URL | [devtree.opentreeoflife.org/opentree/argus/opentree4.0@270704/Caldisericia](https://devtree.opentreeoflife.org/opentree/argus/opentree4.0@270704/Caldisericia) |
| Target node label | Caldisericia |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 270704 |
| Source tree id(s) | silva:AB252429/#3,ncbi:693071,worms:564159,irmng:1551 |
| Open Tree Taxonomy id | 859183 |
| Intended scope | Re: synthetic tree |
| Supporting reference | None |

**Comment by jar398** [comment]
Weird! If you look at this issue in gmail, you see

URL devtreeopentreeoflifeorg/opentree/argus/opentree40@270704/Caldisericia

and the hyperlink is unfollowable, but in github it's fine:

URL devtree.opentreeoflife.org/opentree/argus/opentree4.0@270704/Caldisericia

**Comment by jimallman** [comment]
Hm, I'm not getting these in Gmail (or they're being clobbered by a spam filter).

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jim Allman](https://github.com/jimallman) |
| Upvotes | 0 |
