### ISSUE TITLE
Duplicate taxon in taxonomy [Glomerella rufomaculansvaccinii]

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#219]
https://devtree.opentreeoflife.org/taxonomy/browse?id=1085557
https://devtree.opentreeoflife.org/taxonomy/browse?id=5709621
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Emily Jane McTavish](https://github.com/snacktavish) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree4.0@1298814/Glomerella-rufomaculansvaccinii](https://tree.opentreeoflife.org/opentree/opentree4.0@1298814/Glomerella-rufomaculansvaccinii) |
| Target node label | Glomerella rufomaculansvaccinii |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1298814 |
| Source tree id(s) | irmng:10403525 |
| Open Tree Taxonomy id | 5709621 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Note to self: need to add a synonym directive.

```
1085557 |   1021711 |   Glomerella rufomaculans-vaccinii    |   species |   if:534673,gbif:5486619  |       |       |   
5709621 |   1021711 |   Glomerella rufomaculansvaccinii |   species |   irmng:10403525  |       |   hidden  |   
```

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/bee774c0cac20c097e988d57422d29b9d31bccb9
