### ISSUE TITLE
Duplicate taxon in taxonomy ['Phaeosphaeria sp. S93-48']

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#220]
Almost certainly should be one taxon, but it looks like this is actually an ncbi problem.
https://devtree.opentreeoflife.org/taxonomy/browse?id=100025
https://devtree.opentreeoflife.org/taxonomy/browse?id=882832
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Emily Jane McTavish](https://github.com/snacktavish) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@1169639/Phaeosphaeria-sp-S93-48](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@1169639/Phaeosphaeria-sp-S93-48) |
| Target node label | Phaeosphaeria sp. S93-48 |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1169639 |
| Source tree id(s) | ncbi:478524 |
| Open Tree Taxonomy id | 100025 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Yes, but I think the only way to know for sure would be to study the corresponding Genbank accession records and follow the references to see what they say about the origin of the samples.

I'm not too keen on fixing Genbank errors. Maybe you could send email to NCBI (there's a feedback address)? What happens if I take no action?

**Comment by snacktavish** [comment]
I emailed ncbi about this case. Are we planning a pathway for feedback to the original taxonomy resources? I thought this came up in the context of adding taxonomy amendments.

**Comment by jar398** [comment]
Hmm... pathways to sources is a big and somewhat delicate question, maybe a
subject for a Monday hangout.

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/8c8c0a8aaf235f82123b758c748d844e9070e7d1
