### ISSUE TITLE
Auto choose examplar for monophyletic duplicates

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#232]
Would it be possible to randomly/automatically select and exemplar in cases where the tips with the same mapping are monophyletic? A curator asked, and it seems like the curator doesn't have anything to add in that situation.

**Comment by jimallman** [comment]
I thought we already ignore these as trivial in the curation UI. Are they even highlighted as unresolved (red text) in the tree view?

**Comment by snacktavish** [comment]
https://devtree.opentreeoflife.org/curator/study/view/tt_106/?tab=trees&tree=Tr76459 Yes, they did. in this tree (accidentally curated on devtree). They showed up in red and were counted. (I'll try to find an example where they haven't already been picked.)

**Comment by snacktavish** [comment]
Found one! https://devtree.opentreeoflife.org/curator/study/edit/tt_103/?tab=trees&tree=tree3 (changed link - had forgotten to save!) Gelasinospora tetrasperma

**Comment by jimallman** [comment]
Thanks, I'll check it out.

**Comment by jar398** [comment]
Personally I think the exemplar ought to be chosen to be the sample that's
most closely related to the type series for the species name. But I'm not a
biologist...

**Comment by snacktavish** [comment]
When they are picking they have mapped all the tips, so information about the sample itself isn't there, I think.

**Comment by jimallman** [comment]
You're correct, @snacktavish. We automatically resolve sibling-only sets, but anything more complex is simply presented to the curator for an explicit choice. I should be able to add a pretty-fast test for monophyly and treat these in the same way.

Here's my understanding of the issues here (**please confirm or clarify**):
- By "monophyly" here, we mean that a given set of OTUs-with-conflicting-mapping also constitutes a complete clade in the current tree (i.e., there are no other OTUs hanging around to muddy the waters). So this would be a monophyletic set that should be resolved automatically:
  
  ![screen shot 2016-02-21 at 9 48 43 am](https://cloud.githubusercontent.com/assets/446375/13203193/7478a942-d880-11e5-9b94-e1a71ed44571.png)
  
  ...but this would require a choice by the curator:
  
  ![screen shot 2016-02-21 at 9 48 52 am](https://cloud.githubusercontent.com/assets/446375/13203195/799167fc-d880-11e5-9d43-d92424245aca.png)
- In the case of siblings-only sets, we choose an arbitrary exemplar. For other monophyletic sets, it's tempting to map the "ancestral" node that contains them all. But we don't currently try to map those, only tips, right? So an arbitrary choice among the conflicting tips seems like a safer choice.

**Comment by snacktavish** [comment]
I agree! That all sounds like a good plan. Arbitrary selection from monophyletic sets preserves branch lengths, (which we don't use, but could sometime.)

**Comment by jimallman** [comment]
> I think the exemplar ought to be chosen to be the sample that's most closely related to the type series for the species name.

I don't understand this, or if it can be known in the app. But if it's the right thing to do, I'm pretty sure we can tweak the exemplar-selection logic in a second pass. (For now, I'll focus on a fast-enough test for monophyly with an arbitrary exemplar.)

**Comment by snacktavish** [comment]
I agree that it can't be known in the app, and as Mark reminded me, it doesn't actually matter, as synthesis will choose one anyhow. Curators just get nervous because they show up red :)

**Comment by jimallman** [comment]
FYI - You can see a preview of this feature on **devtree**. It slows things down a bit, since the conflict-gathering code is called many times when displaying a large tree. I'm planning to add a per-tree cache for this conflict information, which should speed up large-tree display in all cases.

**Comment by jimallman** [comment]
The latest code (running on **devtree**) includes the per-tree cache, so the performance hit for this is negligible. It seems this conflict info, which was being calculated _many_ times during display, was the main reason for the slow loading of big trees. Much faster now!

**Comment by bredelings** [comment]
Great!  The cache should make it much faster to example conflict cases 
on pg_2448.

**Comment by mtholder** [comment]
closed as this seems fixed.
