### ISSUE TITLE
Extraneous level in name "Division=Dikarya"

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#235]
This should just be "Dikarya"
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@888271/Division=Dikarya](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@888271/Division=Dikarya) |
| Target node label | Division=Dikarya |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 888271 |
| Source tree id(s) | h2007:27 |
| Open Tree Taxonomy id | 5602101 |
| Supporting reference | NA |

**Comment by jar398** [comment]
This will be fixed on OTT 2.10 (is fixed in draft)
