### ISSUE TITLE
More current view of Nemertea phylogeny

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#236]
Anopla and Enopla no longer have standing. Heteronemertea plus Hubrecthella (maybe Hubrechtidae) = Pilidiophora; Pilidiophora + Hoplonemertea = Neonemertea; Bdellonemertini is family within Monostilifera Distromatonemertea.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jon Norenburg](mailto:norenburgj@si.edu) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@445195/Nemertea](https://tree.opentreeoflife.org/opentree/argus/ottol@445195/Nemertea) |
| Target node label | Nemertea |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1589944 |
| Source tree id(s) | ncbi:6217,worms:152391,gbif:63,gbif:7194177,irmng:178 |
| Open Tree Taxonomy id | 445195 |
| Supporting reference | DOI 10.1098/rspb.2002.2254; DOI 10.1111/j.1096-0031.2011.00376.x; http://dx.doi.org/10.1071/IS13061 |

**Comment by jar398** [comment]
Thanks!  I wanted to check the article to see what it has in the way of
taxonomic revision and/or phylogeny, but it's not open access and the Duke
library doesn't subscribe to the journal.

CoL seems to just import WoRMS for this group, so ideally we would update
WoRMS with this change. The most recent change to the Anopla record
http://www.marinespecies.org/aphia.php?p=taxdetails&id=1293 was by Jon
Norenburg of NMNH in 2013. His email address is on the WoRMS site.

I can just take the particular changes given and add them as ad hoc patches.

**Comment by mtholder** [comment]
tree now queued for next synthesis.

**Comment by mtholder** [comment]
the higher level names are coming to OTT until NCBI, so we'll probably need to get them to change them, if we want to fix all of them.
