### ISSUE TITLE
Oecanthinae additions

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#239]
Hello. There are three species of Oecanthus that should be added:  Oecanthus bakeri, Oecanthus belti and Oecanthus symesi.  There are two species of Neoxabea that should be updated:  Neoxabea cerrojesusensis is currently showing on the tree as Neoxabea sp. 1 LC-2014; Neoxabea ottei is currently showing as Neoxabea sp. 2 LC-2014.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Nancy](mailto:oecanthinae@gmail.com) |
| Upvotes | 0 |
| URL | [/contact](None/contact) |
| Target node label |  |
| Synthetic tree id |  |
| Synthetic tree node id |  |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | https://www.researchgate.net/publication/276420127_Two_New_Species_of_Neoxabea__Three_New_Species_of_Oecanthus__and_Documentation_of_Two_Other_Species_in_Nicaragua_(Orthoptera_Gryllidae_Oecanthinae) |

**Comment by mtholder** [comment]
fixed. thanks.
