### ISSUE TITLE
Error response from /tnrs/match_names API

### ISSUE THREAD

**Issue by abusalehmdtayeen** [OpenTreeOfLife/feedback#242]
I get this error response "**The proxy server received an invalid response from an upstream server. The proxy server could not handle the request. Reason: Error reading from remote server**" after around 200s for the following API request:

curl -X POST "https://api.opentreeoflife.org/v2/tnrs/match_names" -H "content-type:application/json" -d '{"names": ["Felidae", "Linnaeus", "Felis silvestris catus", "Felis catus domestica", "Felis catus", "Felis silvestris", "Felis silvestris lybica", "Felis catus", "Felis chaus", "F. silvestris silvestris", "F. bieti", "Felis catus", "Linnaeus", "F. silvestris", "Felis silvestris", "F. catus", "F. silvestris", "Felis catus", "Felis domesticus", "Felis domestica", "Felis daemon", "Felidae", "Felis silvestris bieti", "Felis catus", "Felidae", "Actinidia polygama", "Philodendron", "Lilium longiflorum", "Panthera", "Felis silvestris lybica", "Felis margarita", "Romanum", "Australasia", "Erithacus rubecula", "Prunella modularis", "Felis catus", "Felis catus", "Systema naturae", "Felis catus domestica", "Prionailurus bengalensis", "Felidae", "Felis silvestris", "Felis domestica", "Felidae", "Felidae", "Niini", "Felidae", "Felis catus", "Felis silvestris silvestris", "Felis silvestris", "Patricia", "Carnivora", "Acinonyx", "Jubatus", "Zaghini", "Lucidum", "Canis familiaris", "Felis catus", "Potera", "Melaleuca alternifolia", "Pontius", "Pontius", "Felis catus", "Felis catus", "Felis silvestris catus", "Panthera", "Felis catus", "Felis catus", "Catriona", "Patricia", "Felis catus", "Nogales", "Acharya", "Traversia lyalli", "Notornis", "Ikuma", "Daruma", "Edda", "Felis catus", "Bicolor cat", "Toxoplasmosis", "Ailurophobia", "Felina", "Singapura", "Sphynx", "Carnivora", "Animalia", "Chordata", "Mammalia", "Eutheria", "Laurasiatheria", "Feliformia", "Nandiniidae", "Nandinia", "N. binotata", "Herpestidae", "Atilax", "A. paludinosus", "Bdeogale", "B. crassicauda", "B. jacksoni", "B. nigripes", "Crossarchus", "C. alexandri", "C. ansorgei", "C. obscurus", "C. platycephalus", "Cynictis", "C. penicillata", "Dologale", "D. dybowskii", "Galerella", "G. flavescens", "G. nigrata", "G. ochracea", "G. pulverulenta", "G. sanguinea", "Helogale", "H. hirtula", "H. parvula", "Herpestes", "H. brachyurus", "H. edwardsii", "H. fuscus", "H. ichneumon", "H. javanicus", "H. naso", "H. semitorquatus", "H. smithii", "H. urva", "H. vitticollis", "Ichneumia", "I. albicauda", "Liberiictus", "L. kuhni", "Mungos", "M. gambianus", "M. mungo", "Paracynictis", "P. selousi", "Rhynchogale", "R. melleri", "Suricata", "S. suricatta", "Hyaenidae", "Crocuta", "C. crocuta", "Hyaena", "H. brunnea", "Proteles", "P. cristatus", "Felidae", "Viverridae", "Eupleridae", "Felidae", "Felinae", "Acinonyx", "A. jubatus", "Caracal", "Caracal", "C. caracal", "C. aurata", "Catopuma", "C. badia", "C. temminckii", "F. bieti", "F. catus", "F. chaus", "F. nigripes", "F. silvestris", "Leopardus", "L. braccatus", "Colocolo", "L. colocolo", "L. geoffroyi", "L. guigna", "L. guttulus", "L. jacobita", "L. pajeros", "L. pardalis", "Oncilla", "L. tigrinus", "L. wiedii", "Leptailurus", "Serval", "L. serval", "L. canadensis", "L. pardinus", "L. rufus", "Otocolobus", "O. manul", "Pardofelis", "P. marmorata", "Prionailurus", "P. bengalensis", "P. planiceps", "P. rubiginosus", "P. viverrinus", "P. concolor", "P. yagouaroundi", "Pantherinae", "Panthera", "P. leo", "P. onca", "P. pardus", "P. tigris", "P. uncia", "Neofelis", "N. nebulosa", "N. diardi", "Viverridae", "Paradoxurinae", "Arctictis", "A. binturong", "Arctogalidia", "A. trivirgata", "Macrogalidia", "M. musschenbroekii", "Paguma", "P. larvata", "Paradoxurus", "P. aureus", "P. hermaphroditus", "P. jerdoni", "P. zeylonensis", "Hemigalinae", "Chrotogale", "C. owstoni", "Cynogale", "C. bennettii", "Diplogale", "D. hosei", "Hemigalus", "H. derbyanus", "Prionodontinae", "Prionodon", "P. linsang", "P. pardicolor", "Viverrinae", "Civettictis", "C. civetta", "Genetta", "G. abyssinica", "G. angolensis", "G. bourloni", "G. cristata", "G. genetta", "G. johnstoni", "G. maculata", "G. pardina", "G. piscivora", "G. poensis", "G. servalina", "Haussa", "G. thierryi", "G. tigrina", "G. victoriae", "Poiana", "P. richardsonii", "P. leightoni", "Viverra", "V. civettina", "V. megaspila", "V. tangalunga", "V. zibetha", "Viverricula", "V. indica", "Eupleridae", "Euplerinae", "Cryptoprocta", "C. ferox", "Eupleres", "E. goudotii", "E. major", "F. fossana", "Galidiinae", "Galidia", "G. elegans", "Galidictis", "G. fasciata", "G. grandidieri", "Mungotictis", "M. decemlineata", "Salanoia", "S. concolor", "S. durrelli", "Caniformia", "Ursidae", "Ailuropoda", "A. melanoleuca", "Helarctos", "H. malayanus", "Melursus", "M. ursinus", "Tremarctos", "T. ornatus", "Ursus", "U. americanus", "U. arctos", "U. maritimus", "U. thibetanus", "Mephitidae", "Conepatus", "C. chinga", "C. humboldtii", "C. leuconotus", "C. semistriatus", "Mephitis", "M. macroura", "M. mephitis", "Mydaus", "M. javanensis", "M. marchei", "Spilogale", "S. angustifrons", "S. gracilis", "S. putorius", "S. pygmaea", "Procyonidae", "Bassaricyon", "B. alleni", "B. gabbii", "B. medius", "B. neblina", "Bassariscus", "B. astutus", "B. sumichrasti", "Nasua", "N. narica", "N. nasua", "Nasuella", "N. olivacea", "N. meridensis", "Potos", "Kinkajou", "P. flavus", "P. cancrivorus", "P. lotor", "P. pygmaeus", "Ailuridae", "Ailurus", "A. fulgens", "Caniformia", "Otariidae", "Arctocephalus", "A. australis", "A. forsteri", "A. galapagoensis", "A. gazella", "A. philippii", "A. pusillus", "A. townsendi", "A. tropicalis", "Callorhinus", "C. ursinus", "Eumetopias", "E. jubatus", "Neophoca", "N. cinerea", "Otaria", "O. flavescens", "Phocarctos", "P. hookeri", "Zalophus", "Z. californianus", "Z. wollebaeki", "Odobenidae", "Odobenus", "O. rosmarus", "Phocidae", "Cystophora", "C. cristata", "Erignathus", "E. barbatus", "Halichoerus", "H. grypus", "Histriophoca", "H. fasciata", "Hydrurga", "H. leptonyx", "Leptonychotes", "L. weddellii", "Lobodon", "L. carcinophagus", "Mirounga", "M. angustirostris", "M. leonina", "Monachus", "M. monachus", "M. schauinslandi", "Ommatophoca", "O. rossi", "Pagophilus", "P. groenlandicus", "Phoca", "P. largha", "P. vitulina", "P. caspica", "P. hispida", "P. sibirica", "Canidae", "Mustelidae", "Canidae", "Atelocynus", "A. microtis", "C. adustus", "C. anthus", "C. aureus", "C. latrans", "C. mesomelas", "C. rufus", "C. simensis", "Cerdocyon", "C. thous", "Chrysocyon", "C. brachyurus", "Cuon", "C. alpinus", "Lycalopex", "L. culpaeus", "L. fulvipes", "L. griseus", "L. gymnocercus", "L. sechurae", "L. vetulus", "Lycaon", "L. pictus", "Nyctereutes", "N. procyonoides", "Otocyon", "O. megalotis", "Speothos", "S. venaticus", "Urocyon", "U. cinereoargenteus", "U. littoralis", "Vulpes", "V. bengalensis", "V. cana", "V. chama", "V. corsac", "V. ferrilata", "V. lagopus", "V. macrotis", "V. pallida", "V. rueppelli", "V. velox", "V. vulpes", "V. zerda", "Mustelidae", "Lutrinae", "Aonyx", "A. capensis", "A. cinerea", "Enhydra", "E. lutris", "Hydrictis", "H. maculicollis", "Lontra", "L. canadensis", "L. felina", "L. longicaudis", "L. provocax", "Lutra", "L. lutra", "L. sumatrana", "Lutrogale", "L. perspicillata", "Pteronura", "P. brasiliensis", "Mustelinae", "Arctonyx", "A. collaris", "Eira", "Tayra", "E. barbara", "Galictis", "G. cuja", "G. vittata", "Gulo", "G. gulo", "Ictonyx", "I. libyca", "I. striatus", "Lyncodon", "L. patagonicus", "Martes (Martens)", "M. americana", "M. flavigula", "M. foina", "M. gwatkinsii", "M. martes", "M. melampus", "M. pennanti", "M. zibellina", "Meles", "M. anakuma", "M. leucurus", "M. meles", "Mellivora", "M. capensis", "Melogale", "M. everetti", "M. moschata", "M. orientalis", "M. personata", "Mustela", "M. africana", "M. altaica", "M. erminea", "M. eversmannii", "M. felipei", "M. frenata", "M. itatsi", "M. kathiah", "M. lutreola", "M. lutreolina", "M. nigripes", "M. nivalis", "M. nudipes", "M. putorius", "M. sibirica", "M. strigidorsa", "M. subpalmata", "Neovison", "N. vison", "Poecilogale", "P. albinucha", "Taxidea", "T. taxus", "Vormela", "V. peregusna", "Basa", "Latina", "Basa"]}'

**Comment by jimallman** [comment]
It looks like you submitted 535 names, well under the documented limit of 1000. Maybe the server bogged down trying to determine what search context to use, since this wasn't specified?

For what it's worth, I got a sensible result for this shortened version of your request, after just a few seconds:

``` bash
curl -X POST "https://api.opentreeoflife.org/v2/tnrs/match_names" -H "content-type:application/json" -d '{"names": ["Felidae", "Linnaeus", "Felis silvestris catus", "Felis catus domestica", "elis catus", "Felis silvestris", "Felis silvestris lybica", "Felis catus", "Felis chaus", "F. silvestris silvestris", "F. bieti", "Felis catus", "Linnaeus", "F. silvestris", "Felis silvestris", "F. catus", "F. silvestris", "Felis catus", "Felis domesticus", "Felis domestica", "Felis daemon", "Felidae", "Felis silvestris bieti", "Felis catus", "Felidae", "Actinidia polygama", "Philodendron", "Lilium longiflorum", "Panthera", "Felis silvestris lybica", "Felis margarita", "Romanum", "Australasia", "Erithacus rubecula", "Prunella modularis", "Felis catus", "Felis catus", "Systema naturae", "Felis catus domestica", "Prionailurus bengalensis", "Felidae", "Felis silvestris", "Felis domestica", "Felidae", "Felidae", "Niini", "Fe lidae", "Felis catus", "Felis silvestris silvestris", "Felis silvestris", "Patricia", "Carnivora", "Acinonyx", "Jubatus", "Zaghini", "Lucidum", "Canis familiaris", "Felis catus", "Potera", "Melaleuca alternifolia", "Pontius"]}'
```

(For the record, that's just 61 names.)

**Comment by jar398** [comment]
Just to be clear: I asked @abusalehmdtayeen to submit this report.  This is pretty clearly a reasonable request, and the API should either satisfy it within a reasonable time (say, 30 seconds) or generate a reasonable error message in a timely manner.

In addition, this request is the best suspect I have seen so far regarding the intermittent nagios complaints we've been seeing, so I am hoping this information will prove helpful in diagnosing that problem.

**Comment by jar398** [comment]
I don't think it was context determination. Doing infer_context on all 500+ names took less than a second. My measurements show TNRS takes about .3 second per name, so a 3-minute timeout (in Apache perhaps, or maybe neo4j) would be hit somewhere around 600 names, and that's what we observed.

We should either set a lower limit (250 is a nice round number) or else figure out how to make TNRS faster (hints @chinchliff ?).

Why a long-running request should lock out other parallel requests remains a mystery. match_names is in taxomachine, but nagios was complaining that treemachine didn't respond.

**Comment by abusalehmdtayeen** [comment]
@jimallman , I also tried using context_name="ANIMALS" as the request parameter. But it gave me the same error response. I am working with the phylotastic team of Dr. Arlin on a project where we use a work flow to first extract scientific names from a web page, resolve the extracted names through Open Tree TNRS, and then get the tree from Open Tree. 500+ names list is a common request in our work flow and according to the Open Tree API documentation it is within the limit. So Open Tree API should be able to satisfy the request. It would be very useful for us if this problem is diagnosed and resolved.

**Comment by jar398** [comment]
The fix I have implemented for the short run is to lower the limit from 1000 to 250. Not sure when this will be live, but probably soon. While this is not ideal, it is easy enough for an application to do multiple requests, I would think, and it will at least guarantee reasonable responses because the three minute timeout won't be reached. Later maybe we can write a TNRS service that's faster than three names per second.

**Comment by chinchliff** [comment]
iirc, the TNRS is much slower when doing fuzzy matching (and I think most
of that cost is happening under the hood inside of Lucene, so I'm not sure
how much improvement there is to be had there). I imagine there are quite a
few use cases where the fuzzy matches are not necessary (and maybe not even
helpful). So I would encourage users to deactivate that feature unless they
need it. It seems like it might also make sense to support a higher limit
for non-fuzzy queries.

**Comment by mtholder** [comment]
Perhaps when fuzzy matching is requested, the backend could perform an exact search first, and then a fuzzy match on the unmatched names.

**Comment by chinchliff** [comment]
i am pretty sure that is how it currently works.

**Comment by jar398** [comment]
I see from the source code that fuzziness on is the default, so that is
what abusalehmdtayeen's API call was doing.

Since we are doing an API version advance, maybe we should change the
default to false for the new version. Having different limits seems like a
good idea, and I can do some measurements to figure out what the non-fuzzy
limit should be.

Thanks Cody!

**Comment by jar398** [comment]
For non-fuzzy matching the rate is one per .0016 second.  I'll set the
limit for non-fuzzy at 10,000 which would be about 16 seconds.. We can
always increase it later.

**Comment by jar398** [comment]
@abusalehmdtayeen I hope this resolution is OK for you, both the limit changes (10000 / 250) and the change in default (fuzzy to nonfuzzy). I'd like to close this issue.

**Comment by abusalehmdtayeen** [comment]
@jar398 : Does that mean I have to make multiple requests from the application with a limit of 250 scientific names?

**Comment by jar398** [comment]
Yes, if you want to look up more than 250 names with fuzzy matching, you have to issue multiple requests.

**Comment by abusalehmdtayeen** [comment]
OK, for now I will do that.
