### ISSUE TITLE
find_trees using ot:ottId property yields no results for taxa for which trees exist

### ISSUE THREAD

**Issue by bbrunet** [OpenTreeOfLife/feedback#243]
We're trying to integrate the find_trees api into our web site to allow users to query published trees for taxa that match taxa in our own database. However, we've been unsuccessful at getting matches to taxa in OTOL indexed trees using either the ot:ottID or ot:ottTaxonName properties as input.

For example: "Bembidion versicolor" occurs in the ott2.9 taxonomy as well as tree2 of study 624, but when we query this species using ottID or ottTaxonName we get no matches. Curiously, querying "Bembidion" results in a match and lists only "Bembidion tetracolum" under matched trees, but this is the same tree that also contains "Bembidion versicolor".

Some instruction on how to use this webservice to query trees for taxa such as "Bembidion versicolor" that occur in trees but for some reason are not matched would be greatly appreciated.

Thanks,
Bryan

**Comment by jar398** [comment]
Very sorry. The service is not acting as it should. This is a known problem
( https://github.com/OpenTreeOfLife/oti/issues/41 ). A complete rewrite of
that service is in progress and we hope to have some improvement to report
soon.

**Comment by chinchliff** [comment]
@jar398 do you have any idea what the timeline is for releasing the new (rewritten) service?

**Comment by kcranston** [comment]
Sometime this summer. It is on hold for some higher-priority feature
requests stemming from workshops we've run (and because of conference
season).

**Comment by mtholder** [comment]
fixed by otindex impl.
