### ISSUE TITLE
Mesotardigrada is 'of dubious status'

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#244]
http://icb.oxfordjournals.org/content/42/3/652.full: "A third class, Mesotardigrada, based on a single species, Thermozodium esakii Rahm, is of dubious status. (The type specimens of T. esakii no longer exist and the type locality, a hot spring in Japan, was destroyed in an earthquake. Subsequent searches for the species have been fruitless.)"
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree5.0@ott2943024/Mesotardigrada](https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott2943024/Mesotardigrada) |
| Target node label | Mesotardigrada |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott2943024 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://icb.oxfordjournals.org/content/42/3/652.full |

**Comment by jar398** [comment]
I always like to drill down on these. Understanding the path from original
description to OTT better can sometimes help improve the assembly method
and the way other taxa are handled. However, in this case I don't think it
does.

OTT 2943024 = worms:342484,gbif:133,irmng:1512

WoRMS got it from ISIS
GBIF got it from CoL (which probably got it from ISIS)
   ISIS got it from a checklist published in Zootaxa which got it from
another checklist
IRMNG got it from SN2000/D.R. Nelson, 2002; Nomenclator Zoologicus
  SN2000 is probably 'Systema Naturae 2000' http://sn2000.taxonomy.nl/
which I had never heard of before. Its source is Brusca 1990 ...

**Comment by jar398** [comment]
Should just be deleted.  All the databases just parrot it from [SN2000](http://sn2000.taxonomy.nl/), which itself says all the names involved are "nom. dub.". (Apparently SN2000 has been updated since last I checked, since it now lists post-2000 references, and doesn't mention Brusca.)

**Comment by mtholder** [comment]
oof. I've heard of type specimens being destroyed, but type localities... that's rough.
will be fixed (made barren) by https://github.com/OpenTreeOfLife/edOTTs/commit/acc4899f4b4baa634b1c34ff2d19b6c8eded02c6
