### ISSUE TITLE
Missing subspecies

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#245]
Ducula_spilorrhoa,Ducula_luctuosa, Ducula_subflavescens are missing as subspecies of this node (or potentially sister species, depending on taxonomy)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@449659/Ducula-bicolor](https://tree.opentreeoflife.org/opentree/argus/ottol@449659/Ducula-bicolor) |
| Target node label | Ducula bicolor |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott449659 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | Gill, F., M. Wright, & D. Donsker (2009). IOC World Bird Names. Version 2.1. Accessed 03-07-2009 |

**Comment by jar398** [comment]
https://github.com/OpenTreeOfLife/reference-taxonomy/issues/173

**Comment by mtholder** [comment]
fixed by previous updates of NCBI and taxon additions.
