### ISSUE TITLE
Missing sister species

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#248]
Acomys cahirinus is incorrectly synonymised with Acomys airensis. Acomys airensis should be a separate sister sp.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree5.0@ott816259/Acomys-cahirinus](https://tree.opentreeoflife.org/opentree/opentree5.0@ott816259/Acomys-cahirinus) |
| Target node label | Acomys cahirinus |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott816259 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://www.iucnredlist.org/details/44936/0 |

**Comment by jar398** [comment]
Thanks. Too bad we can't just import the whole red list.

**Comment by jar398** [comment]
Looks OK in OTT 2.10 https://tree.opentreeoflife.org/taxonomy/browse?id=816257
