### ISSUE TITLE
I suspect Heteropholis genneus is a misspelt synonym

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#249]
for https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott276091/Naultinus-gemmeus
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree5.0@ott4945797/Heteropholis-genneus](https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott4945797/Heteropholis-genneus) |
| Target node label | Heteropholis genneus |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott4945797 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://reptile-database.reptarium.cz/species?genus=Naultinus&species=gemmeus |

**Comment by jar398** [comment]
this is an irmng-only taxon.  irmng:10735439
