### ISSUE TITLE
Crenarchaeota is a dup

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#251]
This node is an error. The real one is at https://tree.opentreeoflife.org/opentree/argus/ottol@114216/Crenarchaeota-phylum-silva-D14053
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@5574956/Crenarchaeota-in-phylum-Thaumarchaeota-](https://tree.opentreeoflife.org/opentree/argus/ottol@5574956/Crenarchaeota-in-phylum-Thaumarchaeota-) |
| Target node label | Crenarchaeota |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott5574956 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | https://tree.opentreeoflife.org/opentree/argus/ottol@114216/Crenarchaeota-phylum-silva-D14053 |

**Comment by jar398** [comment]
duplicate of #189

**Comment by hyanwong** [comment]
oops sorry. Forgot I already submitted this
