### ISSUE TITLE
Typo? ['Hippopotamus madgascariensis']

### ISSUE THREAD

**Issue by eltabo** [OpenTreeOfLife/feedback#258]
Maybe a typo for _Hippopotamus madagascariensis_
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/eltabo) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree5.0@ott3612014/Hippopotamus-madgascariensis](https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott3612014/Hippopotamus-madgascariensis) |
| Target node label | Hippopotamus madgascariensis |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott3612014 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | https://tree.opentreeoflife.org/opentree/opentree5.0@ott3612011/Hippopotamus-madagascariensis |

**Comment by mtholder** [comment]
looks like it. Thanks.

**Comment by jar398** [comment]
The misspelling is now a synonym.
