### ISSUE TITLE
'Turbellaria' should not be a terminal node

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#259]
This belongs elsewhere on the tree.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree5.0@ott580670/Turbellaria](https://tree.opentreeoflife.org/opentree/opentree5.0@ott580670/Turbellaria) |
| Target node label | Turbellaria |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott580670 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | NA |

**Comment by jar398** [comment]
In OTT 2.10 it is a direct child of Platyhelminthes. Wikipedia concurs. Does that seem right to you?

**Comment by jar398** [comment]
Actually in 2.9 as well. https://tree.opentreeoflife.org/taxonomy/browse?name=Turbellaria
I'll look to see if there's some small change that can cause many of those 'major_rank_conflict' genera to surface. Not that most (not all) will go away if we decide to suppress irmng-only taxa.

**Comment by hyanwong** [comment]
Yes, child of Platyhelminthes is correct.

**Comment by hyanwong** [comment]
Returning to this issue, I think the problem is that Turbellaria as usually defined is paraphyletic, so should probably be excluded from the tree

**Comment by jar398** [comment]
Can't remove a higher taxon unless we have an alternative classification of its children to swap in. (unless all the children are to be treated as 'incertae sedis'.)

I'm going to close this for now. Feel free to reopen if you have details on how to remove it.

**Comment by hyanwong** [comment]
Oh, yuck. Yes, I can see this is a problem, and unlikely to be easy to resolve. Probably needs further thought.
