### ISSUE TITLE
missing species

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#265]
missing Vaselea floribunda, which forms a polytomy with Vesalea coriacea var. coriacea and Vesalea grandifolia 
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Praveen](mailto:pramaswamy13@gmail.com) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree5.0@ott5507430/Vesalea](https://tree.opentreeoflife.org/opentree/opentree5.0@ott5507430/Vesalea) |
| Target node label | Vesalea |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott5507430 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | None |

**Comment by mtholder** [comment]
present as synonym: https://tree.opentreeoflife.org/taxonomy/browse?id=1002205
