### ISSUE TITLE
Eunicemorpha seems to be a dead-end node

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#270]
Presumably this should be filled out somehow
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree5.0@ott5297941/Eunicemorpha](https://tree.opentreeoflife.org/opentree/opentree5.0@ott5297941/Eunicemorpha) |
| Target node label | Eunicemorpha |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott5297941 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | A/A |

**Comment by jar398** [comment]
If you want to see what's in it, follow the ott: link from the properties
panel

(I have a feeling the bug here - failing to propagate extinctness as far as
possible - has already been reported, but can't find the issue)

**Comment by mtholder** [comment]
https://github.com/OpenTreeOfLife/feedback/issues/241

**Comment by jar398** [comment]
no, #241 is a different problem.  the one I'm talking about is: if all
children of X are extinct, then X should be inferred extinct.  there is
code to do this and it worked at one time, so I don't know why it's not
kicking in in this instance.

**Comment by jar398** [comment]
https://github.com/OpenTreeOfLife/peyotl/issues/151  should take care of this.

**Comment by mtholder** [comment]
now flagged as barren
