### ISSUE TITLE
Coniferophyta exists with no children. Conifers presumably in Pinales

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#278]
Some mix up here with https://tree.opentreeoflife.org/opentree/opentree5.0@ott4736806/Pinales
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree5.0@ott994093/Coniferophyta](https://tree.opentreeoflife.org/opentree/opentree5.0@ott994093/Coniferophyta) |
| Target node label | Coniferophyta |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott994093 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | N/A |

**Comment by jar398** [comment]
I think we can just delete Coniferophyta. It is NCBI-only, contains no species, and seems to be based mainly on a single environmental sequence.

**Comment by hyanwong** [comment]
Agreed

**Comment by jar398** [comment]
It looks like Pinales is an order under subclass Pinidae = Coniferophyta.  https://tree.opentreeoflife.org/taxonomy/browse?name=Coniferophyta

(odd name for a subclass.)

I think this will work, but let me know if I've got it wrong.
