### ISSUE TITLE
Charites is a fossil genus

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#280]
But appears in the synthetic tree
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree5.0@ott3855124/Charites](https://tree.opentreeoflife.org/opentree/opentree5.0@ott3855124/Charites) |
| Target node label | Charites |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott3855124 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://www.algaebase.org/search/genus/detail/?genus_id=45254 |

**Comment by jar398** [comment]
Previously reported at
https://github.com/OpenTreeOfLife/reference-taxonomy/issues/194
