### ISSUE TITLE
News species of Chalcocopris [Scarabaeidae]

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#284]
The new species Chalcocopris inexpectatus was published in 2015.

ROSSINI, M., VAZ-DE-MELLO, F.Z. 2015. A review of the genus Chalcocopris Burmeister, 1846 (Coleoptera: Scarabaeidae: Scarabaeinae), with description of a new species. Zootaxa 3920 (2): 291–300.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Wallace Beiroz](mailto:wbeiroz@gmail.com) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@3340685/Chalcocopris](https://tree.opentreeoflife.org/opentree/argus/ottol@3340685/Chalcocopris) |
| Target node label | Chalcocopris |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott3340685 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://dx.doi.org/10.11646/zootaxa.3920.2.5 |

**Comment by mtholder** [comment]
fixed in previous OTT
