### ISSUE TITLE
Notochelys platynota is not extinct

### ISSUE THREAD

**Issue by uyedaj** [OpenTreeOfLife/feedback#285]
Neither the listed gbif or ncbi taxonomy says it is extinct, so not sure where that information is coming from. http://www.iucnredlist.org/details/14856/0
Inclusion of the ott_id (711698) causes requests for the induced subtree to fail.

Query:
`$ curl -X POST https://api.opentreeoflife.org/v3/tnrs/match_names -H "content-type:application/json" -d '{"names":["Notochelys platynota"]}'`

Result:
`{
  "governing_code" : "ICZN",
  "unambiguous_names" : [ "Notochelys platynota" ],
  "unmatched_names" : [ ],
  "matched_names" : [ "Notochelys platynota" ],
  "context" : "Tetrapods",
  "includes_deprecated_taxa" : false,
  "includes_suppressed_names" : false,
  "includes_approximate_matches" : false,
  "taxonomy" : {
    "weburl" : "https://tree.opentreeoflife.org/about/taxonomy-version/ott2.9",
    "author" : "open tree of life project",
    "name" : "ott",
    "source" : "ott2.9draft12",
    "version" : "2.9"
  },
  "results" : [ {
    "name" : "Notochelys platynota",
    "matches" : [ {
      "is_synonym" : false,
      "score" : 1.0,
      "nomenclature_code" : "ICZN",
      "is_approximate_match" : false,
      "taxon" : {
        "is_suppressed" : false,
        "tax_sources" : [ "ncbi:204958", "gbif:2443474", "irmng:10636344" ],
        "unique_name" : "Notochelys platynota",
        "synonyms" : [ "Cyclemys giebelii", "Cistudo bankanensis", "Notochelys platynota", "Cyclemys platynota", "Emys platynota" ],
        "name" : "Notochelys platynota",
        "flags" : [ "EXTINCT_INHERITED" ],
        "ott_id" : 711698,
        "rank" : "species"
      },
      "search_string" : "notochelys platynota",
      "matched_name" : "Notochelys platynota"
    } ]
  } ]
}`

**Comment by jar398** [comment]
The information comes from
http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1193361.
But IRMNG also has
http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1335337
saying a genus of the same name is extant.

Looks like a logic bug - thanks for pointing this out!

**Comment by jar398** [comment]
Fixed in 2.10 draft.  I believe it was a beneficiary of https://github.com/OpenTreeOfLife/reference-taxonomy/commit/b46a5809583c377ab0c1090f0113fa8eeaeba880#diff-8a1e516742dcd41631edfb13e9da2a5c
