### ISSUE TITLE
Newick format from Mammalia not correct?

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#290]
Hello. I've been trying to download the subtree for the Mammalia branch to prune using the R package ape.  However, the downloaded .tre file seems to be off in some way - when I try to use other tree visualizers I get error messages about not having a valid Newick format.  Is there a way to get a link to a working newick file for this branch? I'm happy to send over the file I have if that helps.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Amy](mailto:klegarth@uw.edu) |
| Upvotes | 0 |
| URL | [/contact](https://tree.opentreeoflife.org/contact) |
| Target node label |  |
| Synthetic tree id |  |
| Synthetic tree node id |  |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | None |

**Comment by kcranston** [comment]
Hi Amy,
I suspect this has something to do with ape, rather than the newick string. Assuming that the file came from our [Mammalia page](https://tree.opentreeoflife.org/opentree/argus/ottol@244265/Mammalia), I can open this with Dendroscope, with the DendroPy python package, and with the R phytools package, but ape does give me an error. I am not an ape expert, but I believe that we have found the tree importer from ape to problematic in the past - refusing to open files that are indeed valid newick. The cause might be monotypic nodes - nodes that correspond to taxa that only have one descendant. 

So, my first suggestion might be to try phytools instead of ape. Let us know how this goes.

**Comment by opentreeapi** [comment]
Noted - thanks for checking this out - I'll look at in phytools later this week --> do you happen to know if you write a newick from Dendroscope or phytools if it will then open in ape (just curious) since phylogeny.fr conversion was having trouble with it as well - super odd!

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Amy](mailto:klegarth@uw.edu) |
| Upvotes | 0 |

**Comment by opentreeapi** [comment]
So I was able to load the tree into phytools and then write the tree as a nexus to read into ape - phytools drop.tip command was giving me problems and I had a working code in ape. I'm curious if you've ever encountered using the drop.tip command and having it fail to drop any? I'm using testtree <- drop.tip(OTOLTree, OTOLTree$tip.label[-match(testtips, OTOLTree$tip.label)]) to retain only the taxa in the object testtips defined as: testtips <- c("Ateles_geoffroyi_azuerensis_ott5857438", "Bos_taurus_ott490099", "Camelus_dromedarius_ott510752", "Cavia_porcellus_ott744000") which is the truncated example I used.  But instead of returning a tree with 4 tips as it has done with other trees, the same tree with thousands of tips remains.  Thoughts? I do think there is something funky in the nexus that was written out to begin with... the taxa towards the top are quite funky before getting to the expected taxa designations in the very last line pasted below:

#NEXUS
[R-package PHYTOOLS, Tue Aug 16 07:50:02 2016]

BEGIN TAXA;
    DIMENSIONS NTAX = 8698;
    TAXLABELS
        'Artibeus sp. BOLD
        'Artibeus sp. BOLD
        'Artibeus sp. BOLD
        'Canis sp. Belgium/36
        'Canis sp. Russia/33
        'Choeroniscus sp. BOLD
        'Erinaceus sp. ''Ito
        'Erinaceus sp. ''Odawara
        'Hipposideros bicolor ''131 KHz''_ott619171'
        'Hipposideros bicolor ''142 KHz''_ott619159'
        'Hipposideros cf. pomona BOLD
        'Marmota sp. BOLD
        'Microcebus sp. d''Ambre_ott4117711'
        'Microtus cf. arvalis BOLD
        'Microtus sp. BOLD
        'Molossus sp. BOLD
        'Murina cf. cyclotis BOLD
        'Mustela sp. BOLD
        'Myotis cf. ater BOLD
        'Myotis cf. muricola BOLD
        'Myotis cf. muricola BOLD
        'Neacomys sp. BOLD
        'Nectomys sp. BOLD
        'Nectomys sp. BOLD
        'Neusticomys sp. BOLD
        'Niviventer cf. confucianus BOLD
        'Oecomys cf. rex BOLD
        'Oecomys sp. BOLD
        'Oecomys sp. BOLD
        'Oryzomys sp. BOLD
        'Oryzomys sp. BOLD
        'Oryzomys sp. BOLD
        'Oryzomys sp. BOLD
        'Oryzomys sp. BOLD
        'Otomys sp. ABTC
        'Peromyscus sp. BOLD
        'Peromyscus sp. BOLD
        'Peropteryx sp. BOLD
        'Pipistrellus cf. tenuis BOLD
        'Proechimys sp. BOLD
        'Proechimys sp. BOLD
        'Rhinolophus cf. chaseni BOLD
        'Rhinolophus cf. pusillus BOLD
        'Rhinolophus sp. BOLD
        'Sorex sp. BOLD
        'Tupaia sp. BOLD
        'undetermined Sciuridae ''chipmunks''_ott357544'
         Kanagawa''_ott348328'
         Shizuoka''_ott348324'
        000_ott5338951'
        500_ott5338950'
        Abditomys_latidens_ott3610454

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Amy](mailto:klegarth@uw.edu) |
| Upvotes | 0 |

**Comment by mtholder** [comment]
see https://github.com/OpenTreeOfLife/feedback/issues/579
