### ISSUE TITLE
Uncia panthera

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/feedback#291]
Adding issue to repository to facilitate discovery and tracking.
https://groups.google.com/forum/#!searchin/opentreeoflife/uncia/opentreeoflife/Wz80w26QKZ4/overview

I believe Uncia uncia is called Panthera uncia in the OTT 2.10 draft.

**Comment by hyanwong** [comment]
Yes, it has changed to Panthera in NBCI after I emailed them, so I suspect this has been picked up by OToL
