### ISSUE TITLE
Heterodon platirhinos (Eastern hognose snake) wrongly marked as extinct_inherited

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#294]
According to the taxonomy browser, the reason this isn't in the synthetic tree is that it is marked as "extinct_inherited": https://tree.opentreeoflife.org/taxonomy/browse?id=405958

also I found about 30 or 40 other extant snake/lizard species that fall into this category, e.g.

https://tree.opentreeoflife.org/taxonomy/browse?id=1000515
https://tree.opentreeoflife.org/taxonomy/browse?id=460140
https://tree.opentreeoflife.org/taxonomy/browse?id=4123498
https://tree.opentreeoflife.org/taxonomy/browse?id=4123487

**Comment by jar398** [comment]
This was already fixed in the OTT 2.10 draft, I think due to the changes I made to the IRMNG import script.

**Comment by hyanwong** [comment]
Ah great. When do these taxa start to make it through to the synth tree then? I guess for OToL_v6 - but not sure on the ETA for this.
