### ISSUE TITLE
Inconsistencies in the Educational Tree of Life Timeline

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#298]
Hello, congratulations for the website.
In the Educational Tree of Life Timeline, however, there some mistakes.
The audio of the entry "Domain Archea is Born" distinctly says: "Archea branched off the domain Archea about one point seven billion years ago". However, it should be "two point seven billion years ago". Indeed, in a much subsequent segment, the entry "Domain Eukarya is born" says "the first discovered eukaryotic fossil was dated at about 1.8 billion years ago", which is clearly incompatible with Archea branching off later (!)
Also, in the segment before, the entry "Genetic Drift" is really a copy of "Domain Eukarya is born".
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Luca](mailto:Luca.argenti@gmail.com) |
| Upvotes | 0 |
| URL | [/contact](https://tree.opentreeoflife.org/contact) |
| Target node label |  |
| Synthetic tree id |  |
| Synthetic tree node id |  |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | None |

**Comment by mtholder** [comment]
the educational site is no longer maintained. sorry about that.
