### ISSUE TITLE
Saccharomycetes apparently an orphan

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#301]
This should contain Saccharomycetales, currently a sister: https://tree.opentreeoflife.org/opentree/argus/ottol@989996/Saccharomycetales
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree6.1@ott989999/Saccharomycetes](https://tree.opentreeoflife.org/opentree/opentree6.1@ott989999/Saccharomycetes) |
| Target node label | Saccharomycetes |
| Synthetic tree id | opentree6.1 |
| Synthetic tree node id | ott989999 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://tolweb.org/Saccharomycetales/29043 |

**Comment by hyanwong** [comment]
Still a problem in 12.3

**Comment by hyanwong** [comment]
It may be worth revisiting this line in the amendments file, once 12.3 has bedded in: https://github.com/OpenTreeOfLife/reference-taxonomy/blob/c1d36a0d1728c7dd223a45d8f02a9d770f78e3b1/curation/amendments.py#L417

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/41a96cff1f276a2d31dd717dbafe82502bbdc793
