### ISSUE TITLE
Neolepas not extinct

### ISSUE THREAD

**Issue by EwersAquaGenomics** [OpenTreeOfLife/feedback#303]
Neolepas ncbi:479177, worms:534843, gbif:4805442, irmng:1370268 extinct_inherited, extinct (OTT id 631697) is not an extinct genus.

See, for example, the following reference:
Jones, D. S. (1993). A New Neolepas (Cirripedia: Thoracica: Scalpellidae) from an Abyssal Hydrothermal Vent, Southeast Pacific. Bulletin of Marine Science, 52(3), 937-948. 

Thank you,
Christine

**Comment by jar398** [comment]
Misannotated in IRMNG.  Will fix.  Thanks for the reports.

**Comment by jar398** [comment]
fixed in ott 2.10
