### ISSUE TITLE
Notobalanus not extinct

### ISSUE THREAD

**Issue by EwersAquaGenomics** [OpenTreeOfLife/feedback#304]
The genus Notobalanus worms:733062, gbif:5166495, irmng:1058561 sibling_higher, extinct_inherited, extinct, unplaced (OTT id 5093036)
is not extinct. 

See, for example, 
Venerus, L. A., Calcagno, J. A., Lovrich, G. A., & Nahabedian, D. E. (2005). Differential growth of the barnacle Notobalanus flosculus (Archaeobalanidae) onto artificial and live substrates in the Beagle Channel, Argentina. Helgoland Marine Research, 59(3), 196-205. doi:10.1007/s10152-005-0219-5

Thank you,
Christine

**Comment by jar398** [comment]
Misannotated in IRMNG.​ Will fix.

**Comment by jar398** [comment]
fixed in ott 2.10
