### ISSUE TITLE
Spadella cephaloptera not extinct

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#306]
https://tree.opentreeoflife.org/taxonomy/browse?id=1003020 is marked as extinct_inherited (OTT id 1003020), but it is not extinct: http://www.marinespecies.org/aphia.php?p=taxdetails&id=105468

**Comment by jar398** [comment]
Good catch. This seems to be a confusion between an order and genus with the same name-string. Ordinarily these would be separated the same way plants and animals are, but they're too close in the taxonomy to permit that. The easiest fix would be to remove the (extinct) genus, for which don't have any species recorded. If we want to keep both, I don't currently have any easy way to separate them, but I'll think about it.

tax/worms/taxonomy.tsv:5951 |   5949    |   Phragmophora    |   order   |  
tax/ncbi/taxonomy.tsv:33513 |   1421718 |   Phragmophora    |   order   |  
tax/gbif/taxonomy.tsv:5430295   |   3251957 |   Phragmophora    |   genus   |  
tax/irmng/taxonomy.tsv:1331332  |   100037  |   Phragmophora    |   genus   |   extinct |  
tax/irmng/taxonomy.tsv:10496    |   1244    |   Phragmophora    |   order   |       |

**Comment by jar398** [comment]
Looks OK in OTT 2.10
