### ISSUE TITLE
Green Plants (plants s.s.) is wrongly associated with 'plants s.l.' in WoRMS/GBIF/IRMNG

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#307]
This node ("Green Plants", Chloroplastida, or Viridiplantae) is correctly identified as NCBI node 33090, but wrongly associated with WoRMs  ID 3 (http://www.marinespecies.org/aphia.php?p=taxdetails&id=3), id 6 in GBIF (http://www.gbif.org/species/6/), and id 15 in IRMNG (http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=15). The WoRMS, GBIF, & IRMNG ids all designate the clade Archaeplastida  (https://en.wikipedia.org/wiki/Archaeplastida) that includes rhodophyta & glaucophyta, and corresponds to this clade in the OpenTree: https://tree.opentreeoflife.org/opentree/argus/opentree6.1@mrcaott2ott142555. 

I'm not sure how this sort of thing is corrected. It seems to me like it might require a hand-crafted intervention
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@361838/Chloroplastida](https://tree.opentreeoflife.org/opentree/argus/ottol@361838/Chloroplastida) |
| Target node label | Chloroplastida |
| Synthetic tree id | opentree6.1 |
| Synthetic tree node id | ott361838 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | None |

**Comment by jar398** [comment]
I agree the current situation is not great. I suspect that if I just removed the cross-references for that node everything would be fine. Would that be acceptable, do you think?

Fixing this properly will require quite a bit of research. I'll have to check the WoRMS, GBIF, and IRMNG groups and, in each case, find the congruent node in NCBI (maybe Archaeplastida, maybe not), if any - it wouldn't surprise me at all if one or more of the Plantaes were paraphyletic. Chloroplastida is at the center of the polysemy separation logic for OTT so getting anything wrong in its vicinity could have pretty bad effects. If we switch to Archaeplastida for polysemy separation, I'll have to look very carefully at the effects on polysemies - I spent a lot of time on this years ago and I have bad memories of it.

**Comment by jar398** [comment]
Archaeplastida is already in OTT (via SILVA):
https://devtree.opentreeoflife.org/taxonomy/browse?name=archaeplastida

So we'll also have to figure out why synthesis thinks that it's not supported.

**Comment by hyanwong** [comment]
For me, simply removing the  WoRMS, GBIF, and IRMNG entries from OTT361838 (but leaving NCBI, which is correct) would be enough, as long as that doesn't screw anything else up for you: as you say, this is a rather key node. Note that an accepted synonym is Viridiplantae, which NCBI uses. I'm rather surprised that there is not an equivalent node in WoRMS/GBIF/IRMNG, but I can't find one either under Chloroplastida, or Viridiplantae. PaleoDB supposedly has one, though: http://www.gbif.org/species/121304350. 

You may have difficulty finding a congruent node in NCBI for WoRMS:3, GBIF:6, and IRMNG:15, since NCBI (at least looking at http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=2759) doesn't seem to resolve the higher level photosynthetic taxa: it keeps Rhodophyta and Glaucophyta (which it calls by the alternative and less common name of glaucocystophytes) as separate children of Eukaryota, rather than uniting them (as is now generally accepted) into Archaeplastida.

**Comment by jar398** [comment]
Sorry about that, I meant find the right group for Plantae in NCBI _or SILVA_ (i.e. in the higher priority taxonomies).

**Comment by jar398** [comment]
WoRMS Plantae does seem to coincide with Archaeplastida; I checked all the phyla and they're all in Archaeplastida. I didn't check the incertae sedis children.

2013 GBIF wrongly puts Bacillariophyta in Plantae, but 2016 GBIF doesn't. Otherwise both have Plantae agreeing with Archaeplastida.

IRMNG has Plantae = Archaeplastida except possibly for Vendophyceae, a small group of microfossils, whose placement I can't discern; could just as easily be in SAR as in Archaeplastida. I vote for not being too concerned about these.

**Comment by jar398** [comment]
This appears to be fixed in 2.10draft5.

```
 361838 |   5268475 |   Chloroplastida  |   kingdom |   silva:D13324/#3,study713:361838,ncbi:33090  |       |   edited  |   
5268475 |   304358  |   Archaeplastida  |   kingdom |   silva:D13324/#2,worms:3,gbif:6,irmng:15 |       |       |   
```

A side effect was to somehow move Cyanidioschyzon merolae to its correct location, which is a good thing. (But Desertella californica moved _away_ from its correct location and is now in Fungi. I'll have to look into that.)

**Comment by hyanwong** [comment]
Perfect. Thanks so much. Hope it hasn't messed with polysemy resolution.

Any likelihood that a synth tree based on 2.10 will be released this week or next?

**Comment by jar398** [comment]
@kcranston is currently the release czar, so I suggest you talk to her, maybe on gitter.
I think 2.10 is in pretty good shape; it incorporates taxa newly added via the addition feature in the curator app. The last step is making it use the new taxon addition service to obtain ids for new taxa. (And maybe we should refresh NCBI, but that was routine last time we did it.) But it's very close. As usual it's possible the 2.9/2.10 changes could lead to synthesis problems, but I have no particular reason to think they will.
