### ISSUE TITLE
Solenodon not extinct

### ISSUE THREAD

**Issue by OneZoomDeveloper** [OpenTreeOfLife/feedback#308]
https://tree.opentreeoflife.org/taxonomy/browse?id=469472 claims the genus is extinct_inherited, extinct. But it contains 2 extant species, _Solenodon cubanus_ & _Solenodon paradoxus_. This could be a repeat of https://github.com/OpenTreeOfLife/feedback/issues/306

**Comment by jar398** [comment]
fixed in the current 2.10 draft
