### ISSUE TITLE
Pseudomonas genus nested deeply within Pseudomonas species

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#309]
Something's wrong at this node. A single name "Pseudomonas" is nested deep within a large set of Pseudomonas species
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree6.1@ott5621146/Pseudomonas](https://tree.opentreeoflife.org/opentree/argus/opentree6.1@ott5621146/Pseudomonas) |
| Target node label | Pseudomonas |
| Synthetic tree id | opentree6.1 |
| Synthetic tree node id | ott5621146 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | N/A |

**Comment by jar398** [comment]
Well that's what NCBI calls it: http://www.ncbi.nlm.nih.gov/nuccore/HC510467

I guess I can rename this one to "cluster HC510467" or "Pseudomonas
cluster HC510467". Or just delete it - I don't think patent-related
sequences belong in OTT (or SILVA either, for that matter).
