### ISSUE TITLE
No "Magnoliophyta", nor "ott99252" can't be fond on the Open Tree of Life synthetic tree version 6.1

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#311]
Hi, I found the open tree has updated to version 6.1, so I have download whole tar archive file, and unzip it, trying to extract a subtree of angiosperm from "opentree6.1_tree\opentree6.1_tree\labelled_supertree\labelled_supertree_ottnames.tre". Based on the readme, this tree should be full synthetic tree with name_ottid labels, however, I can find any strings (Open it notepad++, simple search) that match "Magnoliophyta", nor "ott99252". Anybody help me what's wrong with this tree or this version? Or did do something wrong with my search?
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Miao Sun](mailto:cactusresponsible@gmail.com) |
| Upvotes | 0 |
| URL | [/contact](https://tree.opentreeoflife.org/contact) |
| Target node label |  |
| Synthetic tree id |  |
| Synthetic tree node id |  |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | None |

**Comment by kcranston** [comment]
This node is definitely in the tree: https://tree.opentreeoflife.org/opentree/argus/ottol@99252/Magnoliophyta 

Using `grep` I find 'ott99252'  in `labelled_supertree_ottnames.tre` and other files (e.g. `annotations.json`. Opening these huge tree files in most text editors is problematic, given their size and the fact the tree is all on one line. 

Many phylogeny programs won't be able to handle a tree of >270,000 tips. Do you need the entire clade? We can help find a solution if you let us know a little more about what data you need.

**Comment by opentreeapi** [comment]
Thank you Karen!!!You are so right!!!

My problem solved: 
[cactus@gator3]$ grep "ott99252" labelled_supertree_ottnames.tre|wc -l
1
[cactus@gator3]$ nw_labels -I 99252.nwk|wc -l
270354

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Miao Sun](mailto:cactusresponsible@gmail.com) |
| Upvotes | 0 |

**Comment by kcranston** [comment]
Glad to hear it! Let us know if we can help with anything else.
