### ISSUE TITLE
Berberis/Mahonia issue: should possibly prefer Mahonia repens

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#312]
A OneZoom user suggests that this species (and presumably some other Berberis species) should be in Mahonia. I.e. Berberis repens should be a synonym for Mahonia repens, rather than the other way round. This is indeed how wikipedia have it. I'm not sure of the procedure OpenTree uses for choosing between synonyms, or of this particular taxonomic argument.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@517548](https://tree.opentreeoflife.org/opentree/argus/ottol@517548) |
| Target node label | Berberis repens |
| Synthetic tree id | opentree6.1 |
| Synthetic tree node id | ott517548 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | https://en.wikipedia.org/wiki/Mahonia_repens |

**Comment by nealmcb** [comment]
Another supporting reference for choosing "Mahonia repens": EoL: http://eol.org/pages/46323006/overview

**Comment by jar398** [comment]
Re "the procedure for choosing between synonyms", the Open Tree taxonomy is basically the NCBI taxonomy with material from other sources added. Names and relationships are from NCBI when NCBI gives them (or more generally: from the highest priority source, see https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/doc/ott2.9.md for priority order). The NCBI update used in OTT 2.10 already reflects the merger of Mahonia and Berberis, so it should be reflected in the system in a week or two.

**Comment by nealmcb** [comment]
@jar398 Thanks for the information on choosing synonyms.  But I'm puzzled.  It sounds like you think something will change soon.  But since it seems that the NCBI entry (e.g. the latest I see is http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=559508) lists Mahonia repens as a synomym for Beberis repens, like OneZoom does now, I would expect the system to not change. It is EoL and Wikipedia that have the synonym the other way around.
At any rate, I hear that the place to pursue this (if warranted) is with NCBI and the authorities they recognize.  So thank you!

**Comment by jar398** [comment]
I'm sorry, I guess I got it backwards.

So the request is to split off the would-be Mahonias currently in NCBI
Berberis to make a separate genus.

I see they are already separate in GBIF, so perhaps I could use GBIF as the
authority for the two genera with NCBI secondary. But some species that are
in NCBI won't exist in GBIF, so their placement would have to be determined
by some other means, e.g. 'Berberis sp. BOP010073' (a chloroplast barcode?
grounded in a voucher code, voucher presumably in China somewhere - we
could try to get a photo and send to a specialist for id to genus).

I'm sorry but this would be a lot of work in a situation where "botanists
disagree on the acceptability of the genus name Mahonia" and no strict
topology improvement results. And maintaining it looks to me like no end of
trouble...

If you could send a comment to NCBI I'd appreciate it.

Jonathan

**Comment by jar398** [comment]
I'm going to mark this 'wontfix' because if NCBI doesn't fix it, maintaining the genus split is going to be h---.
