### ISSUE TITLE
Megalopyge opercilaris probably a synonym of opercularis

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#313]
Probably an orthographic mistake in ITIS, see URL
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree7.0@ott3041117/Megalopyge-opercilaris](https://tree.opentreeoflife.org/opentree/argus/opentree7.0@ott3041117/Megalopyge-opercilaris) |
| Target node label | Megalopyge opercilaris |
| Synthetic tree id | opentree7.0 |
| Synthetic tree node id | ott3041117 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://naturewatch.org.nz/flags/1899 |

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/742c140e6a3ac49a7c7bd2905d8bd340e18dec90
