### ISSUE TITLE
All the Nautilidae genera ending in -ceras are fossils

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#317]
There are only 2 extant nautilus relatives, the Allonautilus species listed here. The genera here ending in -ceras are fossils (as well as many of the Nautilus species (see https://github.com/OpenTreeOfLife/feedback/issues/288)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [devtree.opentreeoflife.org/opentree/argus/opentree5.0@ott616361/Nautilidae](https://devtree.opentreeoflife.org/opentree/argus/opentree5.0@ott616361/Nautilidae) |
| Target node label | Nautilidae |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott616361 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://www.marinespecies.org/aphia.php?p=taxdetails&id=153112 |

**Comment by jar398** [comment]
The -ceras genera seem to have been cleaned up.  _Nautilus_ itself still seems to contain many invalid names. I'm thinking about how to fix it.

**Comment by hyanwong** [comment]
There are a two fossil genera still on this node which have either reappeared or never went away: https://devtree.opentreeoflife.org/opentree/argus/opentree10.0@ott2870657/Kummelonautilus and https://devtree.opentreeoflife.org/opentree/opentree10.0@ott4153698/Westonoceras. Both are GBIF-only, and are flagged up as fossil species on the GBIF site, so I presume it should be possible to identify them as such on OpenTree, although I'm not sure if extinctness status is saved in the GBIF dump files, @jar398?

**Comment by hyanwong** [comment]
@jar398 : for my suggestion about cleaning up *Nautilus*, see https://github.com/OpenTreeOfLife/reference-taxonomy/issues/206#issuecomment-301030849

**Comment by jar398** [comment]
Right: unlike IRMNG, the GBIF dumps don't have extinct status as a column. (Nor do they have nomenclatural status, which would also be very useful.)

**Comment by hyanwong** [comment]
How annoying. That rings a bell now. I don't quite understand, however, why the GBIF pages (e.g. http://www.gbif.org/species/4624729/) list IRMNG and PaleoDB as "checklists" for the taxon, but there is no IRMNG entry in OpenTree (which would presumably allow OT to recognise fossil status). Perhaps GBIF is using an older IRMNG dataset, and it has since been deleted? Or there is something up with the GBIF<->IRMNG mapping on OpenTree?

**Comment by hyanwong** [comment]
If there is a way of knowing that these genera are in PaleoDB, then I assume this is a good heuristic for flagging them as extinct (if they are only known via GBIF, that is). Either way, this is a very minor issue for me personally, since I cull genera with no descendant species from the OneZoom tree. But I thought it worth adding to the issue.

**Comment by hyanwong** [comment]
Fossil genera are gone from 11.3 and 12.3. The issue of excess number of species in _Nautilus_ (should only be 2 or 4 spp.) is flagged in https://github.com/OpenTreeOfLife/feedback/issues/288
