### ISSUE TITLE
Spelling error for Syntexis

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#318]
Should be synonymised with https://tree.opentreeoflife.org/opentree/opentree6.1@ott893510/Syntexis
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree6.1@ott3244917/Syntexix](https://tree.opentreeoflife.org/opentree/argus/opentree6.1@ott3244917/Syntexix) |
| Target node label | Syntexix |
| Synthetic tree id | opentree6.1 |
| Synthetic tree node id | ott3244917 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | any, e.g. https://en.wikipedia.org/wiki/Syntexis_libocedrii |

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/b7adea1570344b12a6f009bcd216ddd13788e034
