### ISSUE TITLE
Change in default value returned by the TNRS

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#319]
I noticed that some of the TNRS tests for [rotl](https://github.com/ropensci/rotl) were broken. They broke because the taxon being returned in a case of synonymy has changed. Specifically, in the rotl tests, I include a lookup for the name "Diadema". It's a sea urchin, a fungus, and a (deprecated) butterfly genus name.

When we first started working on rotl, the search would return the fungus by default, in a later release it used to return the sea urchin, and now it's back on the fungus. 

It's easy to fix the tests, but I worry on the effects this might have on users who might be relying on the default values being returned in their scripts, and the API changing the default.

**Comment by jar398** [comment]
Currently the order is pretty much random, dependent on implementation
details of taxomachine and neo4j. The taxonomy is changing all the time and
a test that depends on the order seems very fragile. Even if we sorted the
list just before returning it, which would help you out most of the time, a
synonym or homonym could be added or removed in any taxonomy release,
changing what appears first in the list.

What if the tests sorted the list before checking it? Or checked that
certain names were in the list, without comparing to the list itself?

Not categorically opposed, just reluctant.

**Comment by fmichonneau** [comment]
OK, that makes sense. I'm not too worried about changing my tests to make them less strict. I'm mostly worried about users that will take for granted the default output of the function in their scripts, which could lead to very different results depending on when they run them. I'll see what I can do on the R client side of things to limit the impact of these changes, or at least make sure users are aware that the output from `tnrs_match_names` can change through time.
