### ISSUE TITLE
A whole load of fossils at the root of the primates

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#320]
Looking at this node, the following are almost certainly mislabelled fossil species:

Galeopithecidae
Guangxilemur
Rencunius
Sivaladapidae
Sarnacius
Toliapina
Toliapinidae
Kyitchaungia
Myanmarpithecus
Paukkaungia
Amphipithecidae
Bahinia
Eosimias
Phenacopithecus
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree7.0@ott913935/Primates](https://tree.opentreeoflife.org/opentree/argus/opentree7.0@ott913935/Primates) |
| Target node label | Primates |
| Synthetic tree id | opentree7.0 |
| Synthetic tree node id | ott913935 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | N/A |

**Comment by jar398** [comment]
I've tracked this down; silly bug, very sorry. We'll get all of these
except Galeopithecidae from IRMNG next time around. Will have to fix
Galeopithecidae
separately since IRMNG thinks it might be extant (granted it does have an
annotation '_Descriptive info_ SN2000 has genera flagged fossil (need to
confirm)' saying it's on the to-do list).

**Comment by jar398** [comment]
Hmm, wikipedia suggests that Galeopteridae is extant: "The names _Colugidae_,
_Galeopithecidae_, and _Galeopteridae_ are synonyms for Cynocephalidae."
... "Just two extant https://en.wikipedia.org/wiki/Extant_taxon species
https://en.wikipedia.org/wiki/Species make up the entire family
https://en.wikipedia.org/wiki/Family_%28biology%29 _Cynocephalidae_ and
order https://en.wikipedia.org/wiki/Order_%28biology%29 _Dermoptera"_

but as constituted in IRMNG (and SN2000) (and OTT), it is extinct.

It should be fixed automatically by
https://github.com/OpenTreeOfLife/peyotl/issues/151

**Comment by hyanwong** [comment]
Thanks for tracking down the bug. It doesn't surprise me that Galeopteridae is defined in two different ways, one being only the stem group, the other including extant forms too. Glad to hear both issues will be fixed.

**Comment by mtholder** [comment]
fixed in https://github.com/mtholder/otcetera/pull/6/commits/6c1a386246c0ac5c006387746d6b85c7336f3920 but we won't see the difference until a new tree is made using a synthesis run that uses that version of otcetera.

**Comment by jar398** [comment]
Synthetic tree looks quite clean now. Can we close this issue?

**Comment by hyanwong** [comment]
Yes, looks fine to me
