### ISSUE TITLE
Synonym of Ctenosaura quinquecarinata

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#321]
https://tree.opentreeoflife.org/opentree/opentree7.0@ott972731/Ctenosaura-quinquecarinata
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree7.0@ott4125444/Ctenosaura-quinquecariniata](https://tree.opentreeoflife.org/opentree/argus/opentree7.0@ott4125444/Ctenosaura-quinquecariniata) |
| Target node label | Ctenosaura quinquecariniata |
| Synthetic tree id | opentree7.0 |
| Synthetic tree node id | ott4125444 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://www.iucnredlist.org/details/44193/0 |

**Comment by jar398** [comment]
The misspelling isn't present in OTT 3.0.  I think we can close this?

**Comment by hyanwong** [comment]
Great
