### ISSUE TITLE
 Eptatretus lophehliae is a misspelling of Eptatretus lopheliae

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#322]
And should probably be named Rubicundus lopheliae
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree7.0@ott5223802/Eptatretus-lophehliae](https://tree.opentreeoflife.org/opentree/opentree7.0@ott5223802/Eptatretus-lophehliae) |
| Target node label | Eptatretus lophehliae |
| Synthetic tree id | opentree7.0 |
| Synthetic tree node id | ott5223802 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://onlinelibrary.wiley.com/doi/10.1111/jzs.12035/abstract |

**Comment by jar398** [comment]
Seems to be OK now (OTT 3.0).
