### ISSUE TITLE
Torquarator bullock originally described as an acorn worm

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#323]
Unless there has been some change I am unaware of, this taxon should be under Hemichordata: Enteropneusta (GBIF has it there, and the original paper (linked in this git issue) places it there). I'm not sure how it has turned up in the Chaetognaths on OpenTree. Is this a bug?
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree7.0@ott3660648/Torquarator-bullocki](https://tree.opentreeoflife.org/opentree/argus/opentree7.0@ott3660648/Torquarator-bullocki) |
| Target node label | Torquarator bullocki |
| Synthetic tree id | opentree7.0 |
| Synthetic tree node id | ott3660648 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://db.coml.org/comlrefbase/filefolder/holland/2005/46_Holland_etal2005.pdf |

**Comment by jar398** [comment]
I think this has been fixed?  @hyanwong can you check https://tree.opentreeoflife.org/taxonomy/browse?name=3660648 and close the issue? Thanks

**Comment by hyanwong** [comment]
Yes. OK now.
