### ISSUE TITLE
several typos in epithets should be synonyms

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/feedback#327]
Within Cyanea... See citrae vs citrea ki vs kii in a couple spots....
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Mark T. Holder](https://github.com/mtholder) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@152136/Cyanea-genus-in-Opisthokonta-](https://tree.opentreeoflife.org/opentree/argus/ottol@152136/Cyanea-genus-in-Opisthokonta-) |
| Target node label | Cyanea |
| Synthetic tree id | opentree7.0 |
| Synthetic tree node id | ott152136 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | pers. comm. |

**Comment by jar398** [comment]
I only found the one typo (citrea for citrae).  Rosella and rosea are distinct.

**Comment by mtholder** [comment]
nozaki vs nozakii and lamarckii vs lamarcki were the ki issues I was referring to. I think postelsi is correct rather than posteli, but I'm getting that just from inclusion of only the former in http://www.marinespecies.org/aphia.php?p=taxdetails&id=135259

**Comment by jar398** [comment]
ok, will fix.  (I was looking at the unalphabetized list in the taxonomy browser - didn't think I would miss such obvious duplications, sorry)
