### ISSUE TITLE
WoRMS Taxonomy for Cnidaria

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#328]
WoRMS taxonomy should be used for Cnidaria.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Allen Collins](mailto:tesserazoa@gmail.com) |
| Upvotes | 0 |
| URL | [/contact](https://tree.opentreeoflife.org/contact) |
| Target node label |  |
| Synthetic tree id |  |
| Synthetic tree node id |  |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | d |

**Comment by kcranston** [comment]
Thanks, Allen! 

@jar398 : I am going to attempt to make this change. I see the [place in the code where you split out Malacostraca](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/assemble_ott.py#L77). Will almost certainly have some questions.

**Comment by jar398** [comment]
Seems to be working
