### ISSUE TITLE
need to edit parent of taxon addition

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/feedback#330]
The parent of:
    https://github.com/OpenTreeOfLife/amendments-1/blob/master/amendments/additions-5991550-5991550.json
was supposed to be:
    https://tree.opentreeoflife.org/taxonomy/browse?name=Paraconopora
instead of:
   https://tree.opentreeoflife.org/taxonomy/browse?name=3349432

I'm not sure of the correct way to make that fix such that taxomachine knows about it.

**Comment by jar398** [comment]
I think the best way is to edit the addition file in the amendments-1 repo.  Then taxomachine will pick it up next time its neo4j database is built.
