### ISSUE TITLE
Information about the hidden species

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#331]
Greetings,

I am wondering if you can explain to me how the hidden taxa have been choose.

Thank you,
JD

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Jean-David Grattepanche](mailto:jgrattepanche@smith.edu) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree7.0@ott5246039/SAR](https://tree.opentreeoflife.org/opentree/opentree7.0@ott5246039/SAR) 
Target node label   |   SAR 
Synthetic tree id   |   opentree7.0 
Synthetic tree node id   |   ott5246039 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by jar398** [comment]
If you're talking about the `hidden` flag, most hidden taxa are from IRMNG, see https://github.com/OpenTreeOfLife/feedback/issues/302 . At that time we weren't processing all of the information IRMNG gave us so couldn't distinguish invalid from valid names. This decision should be reviewed.

If you're talking about taxa "suppressed" from synthesis, that is a decision made by whoever is making the synthetic tree, on the basis of flags coming from the taxonomy. Most of the suppressed taxa are either 'incertae sedis' or a descendant of an 'incertae sedis' taxon. This too is currently being reviewed. The flags are discussed [here](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/doc/taxon-flags.md).
