### ISSUE TITLE
Alethinophidia is a widely-used, more descriptive name

### ISSUE THREAD

**Issue by amdurso** [OpenTreeOfLife/feedback#334]
Alethinophidia is a widely-used, more descriptive name for this node (all snakes except blindsnakes and threadsnakes). See also:

http://eol.org/pages/2816351/overview
http://palaeos.com/vertebrates/squamata/alethinophidia.html

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Andrew Durso](https://github.com/amdurso) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree8.0@mrcaott1662ott35603/Aniliidae--Rhinechis](https://tree.opentreeoflife.org/opentree/argus/opentree8.0@mrcaott1662ott35603/Aniliidae--Rhinechis) 
Target node label   |   [Aniliidae + Rhinechis] 
Synthetic tree id   |   opentree8.0 
Synthetic tree node id   |   mrcaott1662ott35603 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=634390#null

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/d465160c5d0fabc52d576285ca56acea5063b56b thanks
