### ISSUE TITLE
Caenophidia is a widely-used, more descriptive name

### ISSUE THREAD

**Issue by amdurso** [OpenTreeOfLife/feedback#335]
Caenophidia is a widely-used, more descriptive name for this node (all snakes except blindsnakes and threadsnakes). See also:

http://eol.org/pages/42339747/overview

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Andrew Durso](https://github.com/amdurso) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree8.0@mrcaott1662ott106872/Acrochordus--Rhinechis](https://tree.opentreeoflife.org/opentree/opentree8.0@mrcaott1662ott106872/Acrochordus--Rhinechis) 
Target node label   |   [Acrochordus + Rhinechis] 
Synthetic tree id   |   opentree8.0 
Synthetic tree node id   |   mrcaott1662ott106872 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://palaeos.com/vertebrates/squamata/macrostomata.html#Caenophidia

**Comment by jar398** [comment]
If we imported paleodb (or paleobiodb now, I guess) we would pick up this
taxon. See also
https://github.com/OpenTreeOfLife/reference-taxonomy/issues/206 .

I think the commenter's description of the taxon isn't right - seems to be
a copy/paste from a different issue. But the idea is clear, as are the
references.

**Comment by amdurso** [comment]
Agreed, this snake taxon and many others that would be useful are supported in paleobiodb. And, my description of the taxon isn't copy-pasted; but, it's possible I've made a mistake with the definition of the clade with respect to extinct species, with which I'm less familiar.

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/7b145b5470116053e7073c7ae16000bd73711a82
