### ISSUE TITLE
Miliaria calandra is synonym for Emberiza calandra

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#336]
Correct name is here: https://tree.opentreeoflife.org/opentree/argus/ottol@972939/Emberiza-calandra

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree8.0@ott324663/Miliaria-calandra](https://tree.opentreeoflife.org/opentree/argus/opentree8.0@ott324663/Miliaria-calandra) 
Target node label   |   Miliaria calandra 
Synthetic tree id   |   opentree8.0 
Synthetic tree node id   |   ott324663 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://www.iucnredlist.org/details/22721020/0

**Comment by jar398** [comment]
related: https://github.com/OpenTreeOfLife/reference-taxonomy/issues/173​

**Comment by jar398** [comment]
Funny, GBIF seems to have it the other way around.

Best fix for this problem: bring in IOC bird list at higher priority than NCBI.
https://github.com/OpenTreeOfLife/reference-taxonomy/issues/173

Second best: add an alignment directive to force GBIF E.c. to map to NCBI M.c.

**Comment by hyanwong** [comment]
Both _Miliaria calandra_ and _Emberiza calandra_ are now entirely missing from the OpenTree Taxonomy file (and therefore also the synth tree), v 11.4 and also in nexttree (v 12.3). I wonder if the correction for this issue has dropped the species out?

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/ed45c4843bd0e61b34ce55993f422e3acfe60c31
