### ISSUE TITLE
New 100+ year old intractable snake specimens paper

### ISSUE THREAD

**Issue by amdurso** [OpenTreeOfLife/feedback#339]
Includes the first genetic data for genus Xylophis, among several other newly sequenced taxa:

https://sararuane.files.wordpress.com/2013/12/ruaneaustin2017_mer.pdf

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Andrew Durso](https://github.com/amdurso) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/ottol@4122277/Xylophis](https://tree.opentreeoflife.org/opentree/argus/ottol@4122277/Xylophis) 
Target node label   |   Xylophis 
Synthetic tree id   |   opentree8.0 
Synthetic tree node id   |   ott4122277 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://onlinelibrary.wiley.com/doi/10.1111/1755-0998.12655/pdf

**Comment by mtholder** [comment]
Thanks. I added that study as https://tree.opentreeoflife.org/curator/study/edit/ot_1042 It should be included in the big tree the next time we build it.
