### ISSUE TITLE
Myomorpha incorrectly synonymised with Sciurognathi

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#340]
If you type in "myomorpha" to the search box, it thinks you are looking for squirrels (Sciurognathi), not the same at all 

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Myomorpha

**Comment by mtholder** [comment]
yeah. This is not optimal, but when NCBI's classification does not recognize some subgroups (Myomorpha and Sciuromorpha in this case) of a higher taxon (sciurognathi), it lists the subgroups as synonyms. See https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=33553
which is why OTT treats these as synonyms). I'm not sure that we have an easy fix for this.  
Ideally the name Myomorpha would be stored with a taxon concept definition, so that searching for it could return a meaningful message. It would probably still dump the user to the same part of the tree (the parent taxon), but it would be less confusing.  But we are pretty far from having taxon concepts under our names/IDs in OTT.

**Comment by hyanwong** [comment]
Hmm, this is worse in this instance, because (and I quote for wikipedia) "most researchers do not consider Sciurognathi as an equally valid group. In particular, gundis are thought to be more closely related to the hystricognathous rodents than to other sciurognaths. In spite of this, most texts continue to use these two suborders due primarily to a lack of a viable alternative. Alternatively, some texts group rodents into three suborders on the basis of the shape of the infraorbital canal. According to this taxonomy the rodents are divided into the suborders Sciuromorpha, Hystricomorpha, and Myomorpha."

So it may be that NCBI is not using a monophyletic taxon, which will (presumably) vanish if a correct phylogeny is incorporated.

**Comment by hyanwong** [comment]
@mtholder in fact, myomorphs *does* exist on the OpenTree, it is simply not named. It is at https://tree.opentreeoflife.org/opentree/opentree8.0@mrcaott42ott55949/Dipodidae--Muroidea. What happens in this case?

**Comment by mtholder** [comment]
If we had this taxon, it would get the name. The trouble is that the only thing that we know about the name is that NCBI lists it as a synonym.
We could fix this with a "patch" to the reference taxonomy. @jar398 would probably need to help in authoring what that would look like. Then the names would not be synonymized in future versions of the tree, and this node would get its label.

**Comment by hyanwong** [comment]
Well, for this particular case, Myomorpha is named in e.g. Fabre (2012) which is referenced in OpenTree as a study that resolves this node. So can it simply to be added as a clade name to https://tree.opentreeoflife.org/curator/study/view/pg_2688 or one of those other trees? Or do you not take clade names from phylogenetic studies?

**Comment by mtholder** [comment]
No. Currently the taxonomy creation is quite separate from the phylogenetic study curation. But thanks for pointing out that study. We have one _ad hoc_ tree provided by taxonomic experts as a taxonomic input. That tree that is used a a source of names and structure. So having a study is helpful.

**Comment by jar398** [comment]
NCBI distinguishes pro parte synonyms from others, so there is the possibility of being smarter. This happens to be the same question as #341, and I've created https://github.com/OpenTreeOfLife/reference-taxonomy/issues/316 to track it.

**Comment by hyanwong** [comment]
@mtholder this seems low down on the radar, but has been picked up again by one of our users. Is there likely to be any resolution for this in the foreseeable future. Or could I author a patch in some way?

**Comment by hyanwong** [comment]
This is fixed in the latest tree. Or at least Myomorpha is there, and the (probably polyphyletic) Sciurognathi is not, which is IMO correct. Can I close?

**Comment by mtholder** [comment]
great. Thanks for checking. I'll close this

**Comment by hyanwong** [comment]
Right. A general solution is suggested in https://github.com/OpenTreeOfLife/reference-taxonomy/issues/316 so this specific issue can be closed.
