### ISSUE TITLE
duplicate source and incorrect id for Asterales

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#341]
At https://tree.opentreeoflife.org/taxonomy/browse?id=1042120

I see irmng:10011, irmng:12186 listed. It seems that the later shouldn't be there.

**Comment by jar398** [comment]
irmng:12186 is Campanulales, and according to NCBI, Campanulales is a synonym pro parte for Asterales.

The code is doing what it was meant to do, but it might be better if pro parte synonyms were not treated the same as other synonyms. I've been meaning to give this a try to see how badly things break if we do it; it could make a large number of taxa _incertae sedis_. I'll make an issue for this.

**Comment by mtholder** [comment]
closing this because of the issue created in ref-taxonomy repo
