### ISSUE TITLE
opentreeoflife vs. onezoom

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#344]
I am writing a book about evolution and I see there is two life trees, opentreeoflife and onezoom. They differ in many places. Is there a reason why? - or is one of them not updated with the latest news? Please answer.
Kind regards
Aage Nicolaisen
Silkeborg, Denmark
aage.nic@mail.dk

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Aage Nicolaisen 
Upvotes   |   0 
URL   |   [/about/open-tree-of-life](https://tree.opentreeoflife.org/about/open-tree-of-life) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by hyanwong** [comment]
Yes. We got that email too. I'll answer and post here too.

**Comment by hyanwong** [comment]
This is what I've replied to Aage. Do add other comments if you have any.

> At OneZoom we essentially rely on the OpenTree 'phylogeny' for most of the tree of life, after pruning away subspecies and a few inappropriate taxa like those with ‘.cf’ in their names. The current version of OneZoom uses OpenTree 7, but we are upgrading to OpenTree 9.1 in a few weeks.
> 
> The OneZoom tree, however, does differ from the OpenTree in two major respects: 
> 
> (1) the current OneZoom view only displays bifurcations, so where the OpenTree has a multifurcation ('polytomy'), we split the branches at random. Note that in a month or two we will have other views of the tree that retain these polytomies, so this will cease to be a major difference. Also note that the polytomies in the OpenTree are not polytomies in the same sense as those shown in (e.g.) a consensus phylogeny. There has been a recent discussion about this on the OpenTree discussion group (see also https://github.com/OpenTreeOfLife/opentree/issues/260)
> 
> (2) In some areas of the tree, particularly on the branches that lead to humans, we have used alternative phylogenies culled mostly from single studies and grafted as replacements onto the OpenTree. We have done this so that we can produce dates for influential nodes, and also make informed decisions about resolving polytomies and about some contentious areas of the tree. As an example of the branches that lead to humans, almost all the mammals are taken from the Bininda-Emonds et al. 2007 paper, apart from the marsupials, the base of the afrothere/laurasiathere/xenarthra divergence, some stuff in the laurasiatheres (notorious for polytomies) and the primates (which are from the comprehensive Springer paper). Similarly, I have used bespoke hand-crafted backbones for some of the squamates, the sharks and rays (which are pretty messed up in OpenTree), among the Lophotrochozoa, and at the higher level at the base of the Eukaryotes. I have also gone with the (increasingly supported) ‘2 domain’ hypothesis which puts some Archaea as closer relatives of Eukaryotes than others. This is not yet something that has been incorporated into the OpenTree.
> 
> Mostly, the bespoke studies used by OneZoom are represented in the OpenTree, but may conflict with other studies, so our choice to go with one particular phylogeny implies that we place more scientific trust in that study than in others. For example, there have been a number of studies which claim that ctenophores are the basal animal group, and this is reflected in the OpenTree. However, most experts in deep animal evolution still disagree with this (as do I, and as is also shown by some studies just published this year). So after consultation with various experts I have decided to ignore the studies which show the earliest animal divergence being between the ctenophores and everything else. This is purely a matter of which data you choose to believe (I think that the ctenophore studies suffer from extensive LBA artifacts).
> 
> For more details, the (extensive) list of studies I have used to resolve OpenTree polytomies can be found by selecting "data sources" from within the OneZoom viewer.
> 
> I’d be interested to know which areas of the tree you think are most divergent between OneZoom and the OpenTree - if you would like to point some out, I can explain why this might be in each case.
>

**Comment by hyanwong** [comment]
@opentreeapi you might want to comment on what OpenTree is likely to do about potential Archaeal paraphyly?

**Comment by hyanwong** [comment]
After a bit of email discussion, it seems like Aage is particularly interested in carnivores. So I'm wondering why the trees in https://tree.opentreeoflife.org/curator/study/view/ot_328/?tab=trees have not been included in synthesis.

**Comment by hyanwong** [comment]
I have pointed Aage at the carnivore super tree study, and that seemed to be satisfactory, so this can be closed
