### ISSUE TITLE
It's the other way round

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#349]
It should be Dinosauria -> Saurischia (or maybe rather Ornithoscelia (Baron 2017)) -> Theropoda -> Coelurosauria -> Aves. Now, given that you prune extinct taxa, Aves and Dinosauria and everything in between are the same thing, but I think it would still be nice to produce the conventional order in these cases.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Florian](mailto:fh+opentreeoflife@hars.de) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree9.1@ott664350/Theropoda](https://tree.opentreeoflife.org/opentree/argus/opentree9.1@ott664350/Theropoda) 
Target node label   |   Theropoda 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott664350 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   Everything published on theropods, ever.

**Comment by mtholder** [comment]
fixed in a previous OTT build
