### ISSUE TITLE
Not a plant! 

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#352]
This is a mite, not a plant.  

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Chelsea Specht](mailto:cdspecht@berkeley.edu) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott730916/Heliconiaceae](https://tree.opentreeoflife.org/opentree/opentree9.1@ott730916/Heliconiaceae) 
Target node label   |   Heliconiaceae 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott730916 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://doi.org/10.11646/zootaxa.4112.1.1

**Comment by opentreeapi** [comment]
Lasioseisus chenpengi and Rhynacadicrus asperulus are the taxa i'm referring to.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Chelsea Specht](mailto:cdspecht@berkeley.edu) 
Upvotes   |   0

**Comment by mtholder** [comment]
Thanks it looks like those are both GBIF errors, if they get it fixed then we can get the fix "for free", but if they are slow to fix it, we could suppress them.

**Comment by TonyRees** [comment]
Lasioseisus chenpengi and Rhynacadicrus asperulus are both spelling errors, the generic names should read Lasioseius and Rhyncadicrus, respectively, both genera of mites - in case this helps... (picked up with Taxamatch search on IRMNG genera)

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/48fb9019d7c012c9fa59734e0be2cd42e23f7393 thanks
