### ISSUE TITLE
misplaced family

### ISSUE THREAD

**Issue by meganlinnay** [OpenTreeOfLife/feedback#353]
this family (Christmaplacidae) is a family within the Brachyura

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Megan Porter](https://github.com/meganlinnay) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree9.1@ott6184281/Christmaplacidae](https://tree.opentreeoflife.org/opentree/argus/opentree9.1@ott6184281/Christmaplacidae) 
Target node label   |   Christmaplacidae 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott6184281 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://www.gbif.org/species/8675404/

**Comment by jar398** [comment]
I see (via GBIF) Brachyura in Mammalia and in Aves, but not in Arthropods, and the supporting reference does not mention any Brachyura. More research required...

**Comment by TonyRees** [comment]
Brachura is an infraorder (crabs etc.) in Decapoda - see WoRMS full hierarchy for this family at http://www.marinespecies.org/aphia.php?p=taxdetails&id=877536, also https://en.wikipedia.org/wiki/Crab

**Comment by mtholder** [comment]
fixed in previous OTT
