### ISSUE TITLE
misplaced family within the Decapoda

### ISSUE THREAD

**Issue by meganlinnay** [OpenTreeOfLife/feedback#354]
this family should be in the Thalassinidea

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Megan Porter](https://github.com/meganlinnay) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott6184687/Kuwaitupogebiidae](https://tree.opentreeoflife.org/opentree/opentree9.1@ott6184687/Kuwaitupogebiidae) 
Target node label   |   Kuwaitupogebiidae 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott6184687 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://www.gbif.org/species/7615133/

**Comment by mtholder** [comment]
agreed. This might be a fixed if we pull a new version of WoRMS, because that taxonomy has a higher ranking in our assembly than GBIF, and WoRMS now has this as a child of Gebiidea (with Thalassinida as a junior synonym of Gebbiidea)  http://www.marinespecies.org/aphia.php?p=taxdetails&id=477323

**Comment by mtholder** [comment]
fixed in previous OTT
