### ISSUE TITLE
Extinct and unplaced extant names joining Diptera root node

### ISSUE THREAD

**Issue by bwiegman22** [OpenTreeOfLife/feedback#355]
A large number of extinct taxon names and lineages are placed at the root node of Diptera.. seems to be due to fossil names provided by IRMNG database;  Some extant taxa also erroneuously placed at the base (Gobryidae = Cyclorrhapha: Diosoidea), (Homalocnemidae = Empidoidea)

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [None](https://github.com/bwiegman22) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott661378/Diptera](https://tree.opentreeoflife.org/opentree/opentree9.1@ott661378/Diptera) 
Target node label   |   Diptera 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott661378 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   Pape, T., Blagoderov, V. & Mostovski, M.B. 2011. Order Diptera Linnaeus, 1758. In: Zhang, Z.-Q., ed., Animal biodiversity: an outline of higher-level classification and survey of taxonomic richness. Zootaxa 3148: 222–229.

**Comment by jar398** [comment]
Thanks for reporting this. I'll look into it.

**Comment by TonyRees** [comment]
@bwiegman22 @jar398 Thanks also for reporting this. The names originate from www.diptera.org via an upload to the 2006 Catalogue of Life (from which IRMNG obtained them) from which they were inferred to be extant. I will change the extant/fossil status of the offending items in IRMNG and then you can decide how and when to address this in OTT - e.g. by a patch until the next IRMNG dump is available, re-crawl just those families from the IRMNG website, or wait for the next complete IRMNG release (which might however be a while away e.g. 12 months...)

**Comment by TonyRees** [comment]
OK, I have made the relevant changes in the master (web) version of IRMNG for affected families, genera and species. A few of the families on your list notably Chiropteromyzidae, Pseudopomyzidae Gobryidae and Homalocnemiidae are extant so were not changed; Valeseguyidae is both extant and fossil (V. disjuncta is fossil, V. rieki is Recent). Also a family not sorting here, Ansorgiidae, previously listed as extant, is fossil. Conceivably there may be some subset of other dipteran genera/species in IRMNG presently listed as extant (within extant+fossil families) that could be possibly fossil for the same reasons (fossil taxa included as extant in CoL 2006) but I do not really have the resources to look for these at this time unfortunately.

Also to note, some of the family allocations are no longer valid: Alinkidae is now subsumed into Procramptonomyiidae, Mesothaumaleidae is now within Thaumaleidae, Parapleciidae is within Paraxymyiidae and Limnorhyphidae is now within Perissommatidae; Protobrachycerontidae is now treated as a variant spelling of Protobrachyceridae (new IRMNG entry).

**Comment by mtholder** [comment]
seems to have been resolved in previous OTT. closing this for now.
