### ISSUE TITLE
Coelacanthidae contains 5 fossil genera in the synth tree

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#356]
As of open tree 10 (but not in 9.1), there are 5 genera in Coelacanthidae which are fossil-only and which have no phylogenetic studies, so should not be shown. They are Chinlea
Diplurus
Graphiurichthys
Moenkopia
Quayia

NB, Tony Rees says "I checked Coelacanthidae in IRMNG, the family is marked fossil but synonymized with Latimeriidae (extant + fossil) following the present treatment in WoRMS which claims to follow the treatment in Eschmeyer's Catalog of [Recent] Fishes. However I cannot find the basis of this statement and it is probably incorrect; Van der Laan (collaborator of Eschmeyer) 2016 gives the 2 families as separate, in different suborders, as does PaleoBioDB. I think the error arises from extant Latimeria being referred to Coelacanthidae by some authors while others have it correctly in Latimeriidae. So, Coelacanthidae should be reinstated as a valid taxon in IRMNG (I will do this on the live version, however it will not be in the April 2017 snapshot now available as a data dump) which will put it out of step with WoRMS but I will advise them of the error. Don't know if this is the source of the problem you have in OTT but is is useful to me to discover at least."

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [devtree.opentreeoflife.org/opentree/argus/opentree10.0@ott773497/Coelacanthidae](https://devtree.opentreeoflife.org/opentree/argus/opentree10.0@ott773497/Coelacanthidae) 
Target node label   |   Coelacanthidae 
Synthetic tree id   |   opentree10.0 
Synthetic tree node id   |   ott773497 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://www.fishbase.org/summary/FamilySummary.php?ID=30

**Comment by hyanwong** [comment]
Additionally Tony says (on gitter):

> RE Coelacanthidae in IRMNG: since the family was marked as a synonym in the 2014 and Apr 2017 IRMNG releases, all its original children would have been transferred elsewhere (by default to Latimeriidae as that was the incorrectly stated valid family name). I am busy moving them back for the next version... RE Diplurus (and its proposed replacement name Holophagoides): these were in IRMNG with no extant/fossil flag because they came in from Nomenclator Zoologicus without any fossil indicator (i.e. notionally extant) but from experience I know that does not always mean they are not fossil. They still have no flag in the April 2017 release on the IRMNG site but I have updated them to "fossil" on the current live version since we started this conversation and I have looked into them further. Present stats on IRMNG genera are 413,000 with cited extant/fossil status, 74,000 presently unknown (including Diplurus and Holophagoides till this last week, only 73,998 to go...). Let me know if this helps at all.

**Comment by hyanwong** [comment]
Note that the genera I flagged up above do have the "gen. extant flag" set to fossil in IRMNG (e.g. [here](http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1268003)) or GBIF (e.g. [here](http://www.gbif.org/species/4836613/)), so I'm a bit puzzled as to why they have made it into the synth tree.

**Comment by mtholder** [comment]
fixed in previous versions, but extant were still listed as extinct. that'll be fixed in https://github.com/OpenTreeOfLife/edOTTs/commit/48fb9019d7c012c9fa59734e0be2cd42e23f7393
