### ISSUE TITLE
New synthesis for Thecostraca?

### ISSUE THREAD

**Issue by EwersAquaGenomics** [OpenTreeOfLife/feedback#357]
I realized that I had left some trees unrooted in the tree collection for barnacles. I fixed this issue, and would really like to know if it improved the synthesis tree. As of now, the placement of some taxa is incorrect, e.g. Tetraclita and Tetraclitella should be close relatives, but Tetraclita has been removed from the synthesis. Any chance you can re-run the synthesis, at least for the Thecostraca? Sorry I didnt catch this earlier, I only saw it when I started using the tree in depth.

Thank you,
Christine

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Christine Ewers-Saucedo](https://github.com/ewersSaucedo) 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://tree.opentreeoflife.org/curator/study/view/pg_2923/?tab=trees&tree=tree6751

**Comment by mtholder** [comment]
this tree has been added to the synth
