### ISSUE TITLE
pictures

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#359]
I think graphic illustrations and information should be cooperate in this project. I know this would yield an extremely heavy data, but this will encourage children to study the tree of life

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Jackson](mailto:trietminh12@gmail.com) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott1041457/Chelicerata](https://tree.opentreeoflife.org/opentree/opentree9.1@ott1041457/Chelicerata) 
Target node label   |   Chelicerata 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott1041457 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by mtholder** [comment]
this is a good suggestion, but out of scope for our project.

**Comment by mtholder** [comment]
"out of scope" in the sense that we don't have plans to do this because of the resources that it would require.
