### ISSUE TITLE
Some suggestion for other taxa to constrain search for OTU mapping

### ISSUE THREAD

**Issue by Katzlab** [OpenTreeOfLife/feedback#36]
Would be good to get more comments but here is starting list:

Amoebozoa
Archaeplastida, plus nested clades rhodophyceae, glaucophyta, chloroplastida
Excavata
Opisthokonta, plus nested clades Fungi and Metazoa
SAR: plus nested clades Alveolata, Stramenopila, Rhizaria (Each of which could be nested but this may be sufficient, for now)

Archaea: might not need subnesting but here are some major clades
Crenarchaeota
Euryarchaeota
Korarchaeota
Nanoarchaeota
Thaumarchaeota

Bacteria: might not need subnesting but here are some major clades
Acidobacteria
Actinobacteria
Aquificae
Armatimonadetes
Bacteroidetes
Candidate divisions
Chlamydiae
Chlorobi
Chloroflexi
Chrysiogenetes
Cyanobacteria
Deferribacteres
Deinococcus-Thermus
Dictyoglomi
Elusimicrobia
Fibrobacteres
Firmicutes
Fusobacteria
Gemmatimonadetes
Lentisphaerae
Nitrospirae
Planctomycetes
Proteobacteria
Spirochaetae
Synergistetes
TA06
Tenericutes
Thermodesulfobacteria
Thermotogae
Verrucomicrobia

**Comment by jar398** [comment]
This is a TNRS issue so will route this to taxomachine and close it here.
Continued at https://github.com/OpenTreeOfLife/taxomachine/issues/new
