### ISSUE TITLE
Add the number of studies to the intro sentence at https://tree.opentreeoflife.org/about/references 

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#360]
It would be nice to provide the number of studies listed at https://tree.opentreeoflife.org/about/references, perhaps as "The following XXX studies (listed alphabetically by first author) have contributed to the current synthetic tree.", where XXX is generated automatically.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [/about/references](https://tree.opentreeoflife.org/about/references) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by mtholder** [comment]
moved to opentree repo
