### ISSUE TITLE
Makaira coftata probably not a real species

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#361]
This seems to be an IRMNG-only invention from Museum Victoria KEmu database - at least, I can't find any references to the species anywhere else other than the link below. It could possibly be a fossil.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/ottol@3638542/Makaira-coftata](https://tree.opentreeoflife.org/opentree/argus/ottol@3638542/Makaira-coftata) 
Target node label   |   Makaira coftata 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott3638542 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://www.gbif.org/species/107807121/verbatim

**Comment by TonyRees** [comment]
Hi Yan, I am inclined to agree as I cannot find it anywhere else and do not think it is fossil. I will suppress it in IRMNG as of now, will not appear in the next version.... Regards - Tony

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/4351b236ac586e3648bf9100c1e254806566fad9
