### ISSUE TITLE
Dileptus is a ciliate genus, definitely not a spider

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#364]
Dileptus has been wrongly placed here, because of the similarity between Trachelidae, a family of spiders, and Tracheliidae, a family in Ciliophora in which some workers have placed the ciliate genus Dileptus (although more recent work places Dileptus in the family Dileptidae).  All the species listed here are ciliates and should be removed from this portion of the tree.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Bruce Taylor](mailto:bdstaylor@gmail.com) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott6173961/Dileptus](https://tree.opentreeoflife.org/opentree/opentree9.1@ott6173961/Dileptus) 
Target node label   |   Dileptus 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott6173961 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://www.zobodat.at/pdf/DENISIA_0031_0001-0529.pdf

**Comment by mtholder** [comment]
fixed in previous OTT
