### ISSUE TITLE
Allow the search for known familiar animals

### ISSUE THREAD

**Issue by Programmer96** [OpenTreeOfLife/feedback#365]
Like chicken, dog, horse, etc.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [None](https://github.com/Programmer96) 
Upvotes   |   0 
URL   |   [/contact](None/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by jar398** [comment]
related: https://github.com/OpenTreeOfLife/reference-taxonomy/issues/160

**Comment by mtholder** [comment]
closed as duplicate of https://github.com/OpenTreeOfLife/reference-taxonomy/issues/160
