### ISSUE TITLE
This species name includes the author

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#368]
Perhaps because this is a hemihomonym (_Centropogon australis_ is also a fish: https://tree.opentreeoflife.org/opentree/argus/ottol@1087012)

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree9.1@ott419478/Centropogon-australis-E-Wimm-Gleason-1925](https://tree.opentreeoflife.org/opentree/argus/opentree9.1@ott419478/Centropogon-australis-E-Wimm-Gleason-1925) 
Target node label   |   Centropogon australis (E.Wimm.) Gleason, 1925 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott419478 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://species.wikimedia.org/wiki/Category:Species-level_hemihomonyms

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/febf8bf02f1dbea648f3281fb966581a185ee1f6
