### ISSUE TITLE
Canis hyaena is not a valid species

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#369]
Synonym for  Hyaena hyaena

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/ottol@3612505/Canis-hyaena](https://tree.opentreeoflife.org/opentree/argus/ottol@3612505/Canis-hyaena) 
Target node label   |   Canis hyaena 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott3612505 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://www.iucnredlist.org/details/10274/0

**Comment by jar398** [comment]
I can’t tell from the current GBIF page for that name whether GBIF now knows about the change of genus (about 50% of Linnaeus’s names still in use have been moved to different genera). If it does, then the next GBIF update to OTT should take care of this.

But I think it doesn’t. The reference seems to say something about the genus change, and wikipedia certainly knows, but there’s no mention of the current genus on the GBIF page.

EUNIS (one of the GBIF data sets) seems to be ignorant of the change, which occurred in 1762. A bit out of date.

This suggests possibly a large number of systematic import errors in GBIF. I will file an issue...

https://www.gbif.org/species/5936121

**Comment by hyanwong** [comment]
Thanks a lot. Filing issues much appreciated. As you gathered, I suspect this is a wider issue than a single taxon, but wasn't going to file separate issues for each.

**Comment by hyanwong** [comment]
@jar398 apologies, as I know you don't work on this any more, but as the GBIF backbone version now lists this as a synonym (https://www.gbif.org/species/5936121), does that mean that when OpenTree does the next GBIF import this will be fixed? Or is it more complicated than that? It's still appearing in 10.4, FWIW.

**Comment by jar398** [comment]
Yes, the GBIF repair should be enough to make this right.  (Exception: if the problem occurs in some other source as well - something you could probably check for in the taxonomy browser.)  I think that applies to some of the others you're seeing as well.

The newer synthetic tree builds still use OTT 3.0, from February 2017. I know it's on the to-do list to make a new OTT version and that there are good reasons it hasn't happened yet, but I have no information beyond that.

**Comment by jar398** [comment]
My general impression is that the GBIF taxonomy is vastly improved since Feb 2017. This should help OTT enormously.

**Comment by hyanwong** [comment]
Great, thanks a lot for the quick response. It's really helpful.

**Comment by mtholder** [comment]
fixed in previous OTT
