### ISSUE TITLE
Lost structure

### ISSUE THREAD

**Issue by Katzlab** [OpenTreeOfLife/feedback#37]
What happened to the parents of Heleopera, Hyalosphenia, and the arcellinida in general?  They are disconnected from the rest of the tree.

How can we help sort this out?
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Katzlab](https://github.com/Katzlab) |
| Upvotes | 0 |
| URL | [dev.opentreeoflife.org/opentree/argus/ottol@61621/Heleopera](http://dev.opentreeoflife.org/opentree/argus/ottol@61621/Heleopera) |
| Target node label | Heleopera |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 3187842 |
| Source tree id(s) | ncbi:318525,gbif:4900471,irmng:1269695 |
| Open Tree Taxonomy id | 61621 |
| Intended scope | Re: synthetic tree |

**Comment by mtholder** [comment]
I think that this was an issue mentioned on an email thread at: https://groups.google.com/forum/#!topic/opentreeoflife-software/raWZ7hSfUpI

@jar398 , do you know if the treemachine and webapp issues that you mentioned in that email thread were created? I did a quick scan and did not see them.

**Comment by Katzlab** [comment]
Thanks for this link also Mark.

The requirement for monophyly of genera/species is a real problem in our world as many, many, many microbial genera/species/clades that were originally defined by morphology turn out to be non-monophyletic.  (Obviously, these species/genera ultimately need to be re-described... but the molecular data are, at this point, ahead of the taxonomic redescription process....).

Removing/unlinking non-monophyletic names from our synthetic tree may make it more difficult for community to see the nature of the data (i.e. our current understanding of biodiversity on Earth).  Also, how will studies be 'mappable' with this criterion in place?

I know Dail has raised this issue in the past and I see that Mark has presented some suggestions available on the link below....  I hope we can come up with some workable solution that captures our current understanding of biodiversity (i.e. the many cases where taxonomy and phylogeny present discordant patterns of monophyly).  Looking for your favorite taxon (e.g. try Hyalosphenia here dev.opentreeoflife.org/opentree) and finding a floating dot is discouraging.

Laura

**Comment by jar398** [comment]
Forgot to file the issues, sorry. Will do so this morning.

**Comment by Katzlab** [comment]
Hi Laura
Mapping taxonomy into a tree that has things not monophyletic is doable
(you may end up mapping multiple names to the same node but it is doable).
That is just a different procedure than what we do with synthesis where the
trees can suggest something to not be monophyletic.

It is possible that we could map names that have no trees that support it
(by not being nonmonophyletic) after the fact and they would show at the
MRCA of the names. However, my guess is that would not necessarily make
sense for many groups. That might help though. Otherwise, we would simply
need a tree that supports the existence of the group (other than taxonomy).

Take care,
Stephen

**Comment by jar398** [comment]
Now tracked as
https://github.com/OpenTreeOfLife/opentree/issues/310
and
https://github.com/OpenTreeOfLife/treemachine/issues/98

**Comment by Katzlab** [comment]
Stephen,

To be clear... many molecular trees fail to support the monophyly of many genera and species that were originally named based on morphology.... 

Can you tell me (or tell me how i can figure out) what happened to:
Arcellinida 
Hyalosphenia
Heleopera
Nebela
(all lone dots in synthesis)

These taxa should all be nested within Tubulinea, which is now a mess with many species falling to root of clade (e.g. all of the Hartmanella species).

Also, I notice that our molecular study (Study 2484) pulled some but not all Nolandella species into a nested clade ... but the Nolandella species that weren't pulled appear to be placed only by taxonomy....  SHould the molecular phylogeny have pulled the 'unsampled' species?  This likely reflects problem with starting taxonomy but how can I tell?  I obviously am still struggling to understand mechanics of synthesis.

How can I, or a community member, figure out the source of problems here?

Laura

On Jun 12, 2014, at 11:19 AM, Stephen Smith wrote:

> Hi Laura
> Mapping taxonomy into a tree that has things not monophyletic is doable (you may end up mapping multiple names to the same node but it is doable). That is just a different procedure than what we do with synthesis where the trees can suggest something to not be monophyletic. 
> 
> It is possible that we could map names that have no trees that support it (by not being nonmonophyletic) after the fact and they would show at the MRCA of the names. However, my guess is that would not necessarily make sense for many groups. That might help though. Otherwise, we would simply need a tree that supports the existence of the group (other than taxonomy).
> 
> Take care,
> Stephen 
> 
> On Thu, Jun 12, 2014 at 8:31 AM, Laura A. Katz lkatz@smith.edu wrote:
> Thanks for this link also Mark.
> 
> The requirement for monophyly of genera/species is a real problem in our world as many, many, many microbial genera/species/clades that were originally defined by morphology turn out to be non-monophyletic.  (Obviously, these species/genera ultimately need to be re-described... but the molecular data are, at this point, ahead of the taxonomic redescription process....).
> 
> Removing/unlinking non-monophyletic names from our synthetic tree may make it more difficult for community to see the nature of the data (i.e. our current understanding of biodiversity on Earth).  Also, how will studies be 'mappable' with this criterion in place?
> 
> I know Dail has raised this issue in the past and I see that Mark has presented some suggestions available on the link below....  I hope we can come up with some workable solution that captures our current understanding of biodiversity (i.e. the many cases where taxonomy and phylogeny present discordant patterns of monophyly).  Looking for your favorite taxon (e.g. try Hyalosphenia here dev.opentreeoflife.org/opentree) and finding a floating dot is discouraging.
> 
> Laura
> 
> On Jun 12, 2014, at 7:05 AM, Mark T. Holder wrote:
> 
> > I think that this was an issue mentioned on an email thread at: https://groups.google.com/forum/#!topic/opentreeoflife-software/raWZ7hSfUpI
> 
> ## 
> 
> You received this message because you are subscribed to the Google Groups "Open Tree of Life" group.
> To unsubscribe from this group and stop receiving emails from it, send an email to opentreeoflife+unsubscribe@googlegroups.com.
> To post to this group, send email to opentreeoflife@googlegroups.com.
> Visit this group at http://groups.google.com/group/opentreeoflife.
> For more options, visit https://groups.google.com/d/optout.
> 
> ## 
> 
> You received this message because you are subscribed to the Google Groups "Open Tree of Life" group.
> To unsubscribe from this group and stop receiving emails from it, send an email to opentreeoflife+unsubscribe@googlegroups.com.
> To post to this group, send email to opentreeoflife@googlegroups.com.
> Visit this group at http://groups.google.com/group/opentreeoflife.
> For more options, visit https://groups.google.com/d/optout.

+++++++++++++++++++++++++++++++++++++++++++++
Laura A. Katz, Elsie Damon Simonds Professor
Department of Biological Sciences
lkatz@smith.edu
44 College Lane
Smith College
Northampton, MA 01063
Phone:  413-585-3825 (office)
            413-585-3750 (lab)
Fax:    413-585-3786
http://www.science.smith.edu/departments/Biology/lkatz/
++++++++++++++++++++++++++++++++++++++++++++

Looking to meet?  Either stop by my office hours Wednesdays 2-3 in SR331, or use the link below to sign up for an appointment slot
by replacing "no title" with your name: http://www.science.smith.edu/departments/Biology/lkatz/appointments

**Comment by josephwb** [comment]
Hi Laura.

I think I might not understand the question, so please bear with me.

The taxa you list have source trees that disprove monophyly. For example,
for "Nebela", the only tree that involves this taxon is this one
http://www.reelab.net/phylografter/stree/svgView/6607 (one of your own),
which does not recover it as monophyletic. Since "Nebela" is not
monophyletic, it is not a taxon, and cannot appear in the synthetic tree.
This part is clear, yes? For example, you would not be able to label any
node in the Lahr tree
http://www.reelab.net/phylografter/stree/svgView/6607 as "Nebela". Or do
you think we can? Again, I think I am misunderstanding something here.

However, "Nebela" _was_ present in the the original taxonomy, so there _is_
a node called "Nebela" in the graph database, the synthetic tree just
doesn't pass through that node. That is why when you search for "Nebela" in
the browser tree that you find a hit. Unfortunately, it is a hit to the
isolated node in the data base that the synthetic tree doesn't pass
through. This will happen for any nonmonophyletic "taxon". I agree that
this should be fixed; rather than present the isolated node as a search
hit, present its descendant taxa (although this might only work at the
genus level).

Or, is the issue instead "where are the descendant taxa of Nebela"? They
are in the tree here
http://dev.opentreeoflife.org/opentree/otol.draft.22@3595955.

HTH.
Joseph.

**Comment by Katzlab** [comment]
Joseph,

Thanks for your thoughtful comments.

1) The story about Nebela is not clear... Hartmanella and Nebela species appear in multiple places on the tree so these genera are not monophyletic.  Again, many, many, many, many microbial lineages first defined by morphology turn out not to be monophyletic and we need to capture them.  As constructed, a researcher interested in finding the genus Hartmanella or Nebela will end up a dead-end circle.  One partial solution here is to have species names appear in search box when you type in genus name.

The current situation will suggest that many, many species are not in the tree because they cannot be found by searching for genus name.

2) I appreciate your doing the work to see that our molecular data (Lahr et al -- study 6607) provide the evidence in this case to support the non-monophyly of the genus.  But this information is not currently accessible to the general user.  If I want to find Nebela, i search for genus, land on dead end circle, and find no information as to why genus name appears parentless/childless.  IF i happen to know that Nebela carinata is in the synthetic tree, i can search for it.  Then once I find it, I have to know to click on red circle to find conflict.  How would I know this if I was not part of the project?

3) If I happened to search for a different Nebela, such as Nebella flabellum, I get taken to a different part of the tree where I see a big comb of Nebela species sunk inappropriately to a deep level (this is because we don't currently allow non-monophyletic genera).  If I click on any one of these, I see only taxonomy for evidence, and I'd have no way of knowing that it is the Lahr study that has confounded things.

I hope you appreciate that I am pushing here because our goal is to create a product that can be used by the community to understand biodiversity.

So, I'd recommend three things:
1) allowing non-monophyletic genera to exist.  Otherwise, we lose TONS of power in representing what we know about microbial (and likely other) diversity (right now, nodes get collapsed in cases where genera are non-monophyletic and this has led to a mess in parts of the tree -- see big combs at Tubulinea and Amoeoboza, for example).  Non-monophyletic genera could be marked somehow to 'warn' people that these are taxa waiting redescription.

2) show species names when searching for generic names 

3) think a bit more about how users can understand sources of conflict in our synthetic tree.  In the case above, searching for Nebela carinata would give a clue but searching for Nebela flabellum would not..... Of course, marking non-monophyletic genera with 'offending' study would help.

Thanks,

Laura

On Jun 13, 2014, at 11:42 AM, Joseph W. Brown wrote:

> Hi Laura. 
> 
> I think I might not understand the question, so please bear with me. 
> 
> The taxa you list have source trees that disprove monophyly. For example, 
> for "Nebela", the only tree that involves this taxon is this one 
> http://www.reelab.net/phylografter/stree/svgView/6607 (one of your own), 
> which does not recover it as monophyletic. Since "Nebela" is not 
> monophyletic, it is not a taxon, and cannot appear in the synthetic tree. 
> This part is clear, yes? For example, you would not be able to label any 
> node in the Lahr tree 
> http://www.reelab.net/phylografter/stree/svgView/6607 as "Nebela". Or do 
> you think we can? Again, I think I am misunderstanding something here. 
> 
> However, "Nebela" _was_ present in the the original taxonomy, so there _is_ 
> a node called "Nebela" in the graph database, the synthetic tree just 
> doesn't pass through that node. That is why when you search for "Nebela" in 
> the browser tree that you find a hit. Unfortunately, it is a hit to the 
> isolated node in the data base that the synthetic tree doesn't pass 
> through. This will happen for any nonmonophyletic "taxon". I agree that 
> this should be fixed; rather than present the isolated node as a search 
> hit, present its descendant taxa (although this might only work at the 
> genus level). 
> 
> Or, is the issue instead "where are the descendant taxa of Nebela"? They 
> are in the tree here 
> http://dev.opentreeoflife.org/opentree/otol.draft.22@3595955. 
> 
> HTH. 
> Joseph. 
> 
> On 12 June 2014 17:43, Katzlab notifications@github.com wrote: 
> 
> > Stephen, 
> > 
> > To be clear... many molecular trees fail to support the monophyly of many 
> > genera and species that were originally named based on morphology.... 
> > 
> > Can you tell me (or tell me how i can figure out) what happened to: 
> > Arcellinida 
> > Hyalosphenia 
> > Heleopera 
> > Nebela 
> > (all lone dots in synthesis) 
> > 
> > These taxa should all be nested within Tubulinea, which is now a mess with 
> > many species falling to root of clade (e.g. all of the Hartmanella 
> > species). 
> > 
> > Also, I notice that our molecular study (Study 2484) pulled some but not 
> > all Nolandella species into a nested clade ... but the Nolandella species 
> > that weren't pulled appear to be placed only by taxonomy.... SHould the 
> > molecular phylogeny have pulled the 'unsampled' species? This likely 
> > reflects problem with starting taxonomy but how can I tell? I obviously am 
> > still struggling to understand mechanics of synthesis. 
> > 
> > How can I, or a community member, figure out the source of problems here? 
> > 
> > Laura 
> > 
> > On Jun 12, 2014, at 11:19 AM, Stephen Smith wrote: 
> > 
> > > Hi Laura 
> > > Mapping taxonomy into a tree that has things not monophyletic is doable 
> > > (you may end up mapping multiple names to the same node but it is doable). 
> > > That is just a different procedure than what we do with synthesis where the 
> > > trees can suggest something to not be monophyletic. 
> > > 
> > > It is possible that we could map names that have no trees that support 
> > > it (by not being nonmonophyletic) after the fact and they would show at the 
> > > MRCA of the names. However, my guess is that would not necessarily make 
> > > sense for many groups. That might help though. Otherwise, we would simply 
> > > need a tree that supports the existence of the group (other than taxonomy). 
> > > 
> > > Take care, 
> > > Stephen 
> > > 
> > > On Thu, Jun 12, 2014 at 8:31 AM, Laura A. Katz lkatz@smith.edu wrote: 
> > > Thanks for this link also Mark. 
> > > 
> > > The requirement for monophyly of genera/species is a real problem in our 
> > > world as many, many, many microbial genera/species/clades that were 
> > > originally defined by morphology turn out to be non-monophyletic. 
> > > (Obviously, these species/genera ultimately need to be re-described... but 
> > > the molecular data are, at this point, ahead of the taxonomic redescription 
> > > process....). 
> > > 
> > > Removing/unlinking non-monophyletic names from our synthetic tree may 
> > > make it more difficult for community to see the nature of the data (i.e. 
> > > our current understanding of biodiversity on Earth). Also, how will studies 
> > > be 'mappable' with this criterion in place? 
> > > 
> > > I know Dail has raised this issue in the past and I see that Mark has 
> > > presented some suggestions available on the link below.... I hope we can 
> > > come up with some workable solution that captures our current understanding 
> > > of biodiversity (i.e. the many cases where taxonomy and phylogeny present 
> > > discordant patterns of monophyly). Looking for your favorite taxon (e.g. 
> > > try Hyalosphenia here dev.opentreeoflife.org/opentree) and finding a 
> > > floating dot is discouraging. 
> > > 
> > > Laura 
> > > 
> > > On Jun 12, 2014, at 7:05 AM, Mark T. Holder wrote: 
> > > 
> > > > I think that this was an issue mentioned on an email thread at: 
> > > > https://groups.google.com/forum/#!topic/opentreeoflife-software/raWZ7hSfUpI 
> > > 
> > > ## 
> > > 
> > > You received this message because you are subscribed to the Google 
> > > Groups "Open Tree of Life" group. 
> > > To unsubscribe from this group and stop receiving emails from it, send 
> > > an email to opentreeoflife+unsubscribe@googlegroups.com. 
> > > To post to this group, send email to opentreeoflife@googlegroups.com. 
> > > Visit this group at http://groups.google.com/group/opentreeoflife. 
> > > For more options, visit https://groups.google.com/d/optout. 
> > > 
> > > ## 
> > > 
> > > You received this message because you are subscribed to the Google 
> > > Groups "Open Tree of Life" group. 
> > > To unsubscribe from this group and stop receiving emails from it, send 
> > > an email to opentreeoflife+unsubscribe@googlegroups.com. 
> > > To post to this group, send email to opentreeoflife@googlegroups.com. 
> > > Visit this group at http://groups.google.com/group/opentreeoflife. 
> > > For more options, visit https://groups.google.com/d/optout. 
> > 
> > +++++++++++++++++++++++++++++++++++++++++++++ 
> > Laura A. Katz, Elsie Damon Simonds Professor 
> > Department of Biological Sciences 
> > lkatz@smith.edu 
> > 44 College Lane 
> > Smith College 
> > Northampton, MA 01063 
> > Phone: 413-585-3825 (office) 
> > 413-585-3750 (lab) 
> > Fax: 413-585-3786 
> > http://www.science.smith.edu/departments/Biology/lkatz/ 
> > ++++++++++++++++++++++++++++++++++++++++++++ 
> > 
> > Looking to meet? Either stop by my office hours Wednesdays 2-3 in SR331, 
> > or use the link below to sign up for an appointment slot 
> > by replacing "no title" with your name: 
> > http://www.science.smith.edu/departments/Biology/lkatz/appointments 
> > 
> >  
> > Reply to this email directly or view it on GitHub 
> > https://github.com/OpenTreeOfLife/feedback/issues/37#issuecomment-45951949 
> > . 
> > 
> > 
> > Reply to this email directly or view it on GitHub.

+++++++++++++++++++++++++++++++++++++++++++++
Laura A. Katz, Elsie Damon Simonds Professor
Department of Biological Sciences
lkatz@smith.edu
44 College Lane
Smith College
Northampton, MA 01063
Phone:  413-585-3825 (office)
            413-585-3750 (lab)
Fax:    413-585-3786
http://www.science.smith.edu/departments/Biology/lkatz/
+++++++++++++++++++++++++++++++++++++++++++++

**Comment by blackrim** [comment]
Just to keep short I will just respond to the one that I feel more strongly
about. I don't think we should allow non-monophyletic genera to exist
except in the taxonomy (where it hasn't been updated to reflect phylogeny).
Of course people can see those things in the taxonomy and we could
potentially mark in the taxonomy where taxa are found to be nonmonophyletic
so maybe that would help (I am talking about the taxonomy browser now not
the tree browser). I think allowing non-monophyletic genera in the
evolutionary tree would be out of step with the rest of the field and I
don't really know what a non-monophyletic genus means. That said, it is
possible to map where a particular set of names most recent common ancestor
would be. Otherwise, these are just areas that need more data or better
trees or something like that.

**Comment by hdliv** [comment]
I wanted to put my few cents in since I have commented before on this and sent a tree about Leptolyngbya and even Anabaena.  The tree (both taxonomy - which in microbial case is actually based on molecular data since SILVA has precedence, then NCBi..another molecular source).  However, as these 'entities' are small...we have a series of problems from the person that sequences it to naming them wrong to non-monophyly which is the case in all 'older' cyanobacterial names I can think of.  just cutting them out...I don't believe is correct.  I had talked to Cody about a way to move some while keeping the others, since this is something that we want to see in our community and is common to see in our trees.  I even sent a bunch of papers about this on another thread.  

When we incorporate microbial studies... this (non-monophyly) will happen, until one day in the future things are perfect.  We are still in the 'grand' age of discovery in the microbial world.

**Comment by Katzlab** [comment]
Stephen,

Mapping to a mrca is a fine solution, especially if mrca allows user to see source of conflict.

Waiting for better trees or more data is NOT the issue... the waiting is on taxonomic revision, which (as you well know) can be a very slow process.  So we need a structure/process that recognizes that molecular data are often ahead of taxonomic revision....  collapsing nodes seems sub optimal.

L

On Jun 13, 2014, at 1:59 PM, Stephen Smith wrote:

> Just to keep short I will just respond to the one that I feel more strongly 
> about. I don't think we should allow non-monophyletic genera to exist 
> except in the taxonomy (where it hasn't been updated to reflect phylogeny). 
> Of course people can see those things in the taxonomy and we could 
> potentially mark in the taxonomy where taxa are found to be nonmonophyletic 
> so maybe that would help (I am talking about the taxonomy browser now not 
> the tree browser). I think allowing non-monophyletic genera in the 
> evolutionary tree would be out of step with the rest of the field and I 
> don't really know what a non-monophyletic genus means. That said, it is 
> possible to map where a particular set of names most recent common ancestor 
> would be. Otherwise, these are just areas that need more data or better 
> trees or something like that. 
> 
> On Fri, Jun 13, 2014 at 1:19 PM, Katzlab notifications@github.com wrote: 
> 
> > Joseph, 
> > 
> > Thanks for your thoughtful comments. 
> > 
> > 1) The story about Nebela is not clear... Hartmanella and Nebela species 
> > appear in multiple places on the tree so these genera are not monophyletic. 
> > Again, many, many, many, many microbial lineages first defined by 
> > morphology turn out not to be monophyletic and we need to capture them. As 
> > constructed, a researcher interested in finding the genus Hartmanella or 
> > Nebela will end up a dead-end circle. One partial solution here is to have 
> > species names appear in search box when you type in genus name. 
> > 
> > The current situation will suggest that many, many species are not in the 
> > tree because they cannot be found by searching for genus name. 
> > 
> > 2) I appreciate your doing the work to see that our molecular data (Lahr 
> > et al -- study 6607) provide the evidence in this case to support the 
> > non-monophyly of the genus. But this information is not currently 
> > accessible to the general user. If I want to find Nebela, i search for 
> > genus, land on dead end circle, and find no information as to why genus 
> > name appears parentless/childless. IF i happen to know that Nebela carinata 
> > is in the synthetic tree, i can search for it. Then once I find it, I have 
> > to know to click on red circle to find conflict. How would I know this if I 
> > was not part of the project? 
> > 
> > 3) If I happened to search for a different Nebela, such as Nebella 
> > flabellum, I get taken to a different part of the tree where I see a big 
> > comb of Nebela species sunk inappropriately to a deep level (this is 
> > because we don't currently allow non-monophyletic genera). If I click on 
> > any one of these, I see only taxonomy for evidence, and I'd have no way of 
> > knowing that it is the Lahr study that has confounded things. 
> > 
> > I hope you appreciate that I am pushing here because our goal is to create 
> > a product that can be used by the community to understand biodiversity. 
> > 
> > So, I'd recommend three things: 
> > 1) allowing non-monophyletic genera to exist. Otherwise, we lose TONS of 
> > power in representing what we know about microbial (and likely other) 
> > diversity (right now, nodes get collapsed in cases where genera are 
> > non-monophyletic and this has led to a mess in parts of the tree -- see big 
> > combs at Tubulinea and Amoeoboza, for example). Non-monophyletic genera 
> > could be marked somehow to 'warn' people that these are taxa waiting 
> > redescription. 
> > 
> > 2) show species names when searching for generic names 
> > 
> > 3) think a bit more about how users can understand sources of conflict in 
> > our synthetic tree. In the case above, searching for Nebela carinata would 
> > give a clue but searching for Nebela flabellum would not..... Of course, 
> > marking non-monophyletic genera with 'offending' study would help. 
> > 
> > Thanks, 
> > 
> > Laura 
> > 
> > On Jun 13, 2014, at 11:42 AM, Joseph W. Brown wrote: 
> > 
> > > Hi Laura. 
> > > 
> > > I think I might not understand the question, so please bear with me. 
> > > 
> > > The taxa you list have source trees that disprove monophyly. For 
> > > example, 
> > > for "Nebela", the only tree that involves this taxon is this one 
> > > http://www.reelab.net/phylografter/stree/svgView/6607 (one of your 
> > > own), 
> > > which does not recover it as monophyletic. Since "Nebela" is not 
> > > monophyletic, it is not a taxon, and cannot appear in the synthetic 
> > > tree. 
> > > This part is clear, yes? For example, you would not be able to label any 
> > > node in the Lahr tree 
> > > http://www.reelab.net/phylografter/stree/svgView/6607 as "Nebela". Or 
> > > do 
> > > you think we can? Again, I think I am misunderstanding something here. 
> > > 
> > > However, "Nebela" _was_ present in the the original taxonomy, so there 
> > > _is_ 
> > > a node called "Nebela" in the graph database, the synthetic tree just 
> > > doesn't pass through that node. That is why when you search for "Nebela" 
> > > in 
> > > the browser tree that you find a hit. Unfortunately, it is a hit to the 
> > > isolated node in the data base that the synthetic tree doesn't pass 
> > > through. This will happen for any nonmonophyletic "taxon". I agree that 
> > > this should be fixed; rather than present the isolated node as a search 
> > > hit, present its descendant taxa (although this might only work at the 
> > > genus level). 
> > > 
> > > Or, is the issue instead "where are the descendant taxa of Nebela"? They 
> > > are in the tree here 
> > > http://dev.opentreeoflife.org/opentree/otol.draft.22@3595955. 
> > > 
> > > HTH. 
> > > Joseph. 
> > > 
> > > On 12 June 2014 17:43, Katzlab notifications@github.com wrote: 
> > > 
> > > > Stephen, 
> > > > 
> > > > To be clear... many molecular trees fail to support the monophyly of 
> > > > many 
> > > > genera and species that were originally named based on morphology.... 
> > > > 
> > > > Can you tell me (or tell me how i can figure out) what happened to: 
> > > > Arcellinida 
> > > > Hyalosphenia 
> > > > Heleopera 
> > > > Nebela 
> > > > (all lone dots in synthesis) 
> > > > 
> > > > These taxa should all be nested within Tubulinea, which is now a mess 
> > > > with 
> > > > many species falling to root of clade (e.g. all of the Hartmanella 
> > > > species). 
> > > > 
> > > > Also, I notice that our molecular study (Study 2484) pulled some but 
> > > > not 
> > > > all Nolandella species into a nested clade ... but the Nolandella 
> > > > species 
> > > > that weren't pulled appear to be placed only by taxonomy.... SHould 
> > > > the 
> > > > molecular phylogeny have pulled the 'unsampled' species? This likely 
> > > > reflects problem with starting taxonomy but how can I tell? I 
> > > > obviously am 
> > > > still struggling to understand mechanics of synthesis. 
> > > > 
> > > > How can I, or a community member, figure out the source of problems 
> > > > here? 
> > > > 
> > > > Laura 
> > > > 
> > > > On Jun 12, 2014, at 11:19 AM, Stephen Smith wrote: 
> > > > 
> > > > > Hi Laura 
> > > > > Mapping taxonomy into a tree that has things not monophyletic is 
> > > > > doable 
> > > > > (you may end up mapping multiple names to the same node but it is 
> > > > > doable). 
> > > > > That is just a different procedure than what we do with synthesis 
> > > > > where the 
> > > > > trees can suggest something to not be monophyletic. 
> > > > > 
> > > > > It is possible that we could map names that have no trees that 
> > > > > support 
> > > > > it (by not being nonmonophyletic) after the fact and they would show 
> > > > > at the 
> > > > > MRCA of the names. However, my guess is that would not necessarily 
> > > > > make 
> > > > > sense for many groups. That might help though. Otherwise, we would 
> > > > > simply 
> > > > > need a tree that supports the existence of the group (other than 
> > > > > taxonomy). 
> > > > > 
> > > > > Take care, 
> > > > > Stephen 
> > > > > 
> > > > > On Thu, Jun 12, 2014 at 8:31 AM, Laura A. Katz lkatz@smith.edu 
> > > > > wrote: 
> > > > > Thanks for this link also Mark. 
> > > > > 
> > > > > The requirement for monophyly of genera/species is a real problem in 
> > > > > our 
> > > > > world as many, many, many microbial genera/species/clades that were 
> > > > > originally defined by morphology turn out to be non-monophyletic. 
> > > > > (Obviously, these species/genera ultimately need to be re-described... 
> > > > > but 
> > > > > the molecular data are, at this point, ahead of the taxonomic 
> > > > > redescription 
> > > > > process....). 
> > > > > 
> > > > > Removing/unlinking non-monophyletic names from our synthetic tree 
> > > > > may 
> > > > > make it more difficult for community to see the nature of the data 
> > > > > (i.e. 
> > > > > our current understanding of biodiversity on Earth). Also, how will 
> > > > > studies 
> > > > > be 'mappable' with this criterion in place? 
> > > > > 
> > > > > I know Dail has raised this issue in the past and I see that Mark 
> > > > > has 
> > > > > presented some suggestions available on the link below.... I hope we 
> > > > > can 
> > > > > come up with some workable solution that captures our current 
> > > > > understanding 
> > > > > of biodiversity (i.e. the many cases where taxonomy and phylogeny 
> > > > > present 
> > > > > discordant patterns of monophyly). Looking for your favorite taxon 
> > > > > (e.g. 
> > > > > try Hyalosphenia here dev.opentreeoflife.org/opentree) and finding a 
> > > > > floating dot is discouraging. 
> > > > > 
> > > > > Laura 
> > > > > 
> > > > > On Jun 12, 2014, at 7:05 AM, Mark T. Holder wrote: 
> > > > > 
> > > > > > I think that this was an issue mentioned on an email thread at: 
> > > > 
> > > > https://groups.google.com/forum/#!topic/opentreeoflife-software/raWZ7hSfUpI 
> > > > 
> > > > > ## 
> > > > > 
> > > > > You received this message because you are subscribed to the Google 
> > > > > Groups "Open Tree of Life" group. 
> > > > > To unsubscribe from this group and stop receiving emails from it, 
> > > > > send 
> > > > > an email to opentreeoflife+unsubscribe@googlegroups.com. 
> > > > > To post to this group, send email to opentreeoflife@googlegroups.com. 
> > > > > 
> > > > > Visit this group at http://groups.google.com/group/opentreeoflife. 
> > > > > For more options, visit https://groups.google.com/d/optout. 
> > > > > 
> > > > > ## 
> > > > > 
> > > > > You received this message because you are subscribed to the Google 
> > > > > Groups "Open Tree of Life" group. 
> > > > > To unsubscribe from this group and stop receiving emails from it, 
> > > > > send 
> > > > > an email to opentreeoflife+unsubscribe@googlegroups.com. 
> > > > > To post to this group, send email to opentreeoflife@googlegroups.com. 
> > > > > 
> > > > > Visit this group at http://groups.google.com/group/opentreeoflife. 
> > > > > For more options, visit https://groups.google.com/d/optout. 
> > > > 
> > > > +++++++++++++++++++++++++++++++++++++++++++++ 
> > > > Laura A. Katz, Elsie Damon Simonds Professor 
> > > > Department of Biological Sciences 
> > > > lkatz@smith.edu 
> > > > 44 College Lane 
> > > > Smith College 
> > > > Northampton, MA 01063 
> > > > Phone: 413-585-3825 (office) 
> > > > 413-585-3750 (lab) 
> > > > Fax: 413-585-3786 
> > > > http://www.science.smith.edu/departments/Biology/lkatz/ 
> > > > ++++++++++++++++++++++++++++++++++++++++++++ 
> > > > 
> > > > Looking to meet? Either stop by my office hours Wednesdays 2-3 in 
> > > > SR331, 
> > > > or use the link below to sign up for an appointment slot 
> > > > by replacing "no title" with your name: 
> > > > http://www.science.smith.edu/departments/Biology/lkatz/appointments 
> > > > 
> > > >  
> > > > Reply to this email directly or view it on GitHub 
> > > > < 
> > > > https://github.com/OpenTreeOfLife/feedback/issues/37#issuecomment-45951949> 
> > > > 
> > > > . 
> > > > 
> > > >  
> > > > Reply to this email directly or view it on GitHub. 
> > 
> > +++++++++++++++++++++++++++++++++++++++++++++ 
> > Laura A. Katz, Elsie Damon Simonds Professor 
> > Department of Biological Sciences 
> > lkatz@smith.edu 
> > 44 College Lane 
> > Smith College 
> > Northampton, MA 01063 
> > Phone: 413-585-3825 (office) 
> > 413-585-3750 (lab) 
> > Fax: 413-585-3786 
> > http://www.science.smith.edu/departments/Biology/lkatz/ 
> > +++++++++++++++++++++++++++++++++++++++++++++ 
> > 
> >  
> > Reply to this email directly or view it on GitHub 
> > https://github.com/OpenTreeOfLife/feedback/issues/37#issuecomment-46037019 
> > . 
> > 
> > 
> > Reply to this email directly or view it on GitHub.

+++++++++++++++++++++++++++++++++++++++++++++
Laura A. Katz, Elsie Damon Simonds Professor
Department of Biological Sciences
lkatz@smith.edu
44 College Lane
Smith College
Northampton, MA 01063
Phone:  413-585-3825 (office)
            413-585-3750 (lab)
Fax:    413-585-3786
http://www.science.smith.edu/departments/Biology/lkatz/
+++++++++++++++++++++++++++++++++++++++++++++

**Comment by josephwb** [comment]
Laura,

I am having a lot of trouble comprehending what a "nonmonophyletic genus" is (the words mean mutually-exclusive things), and even more how such a thing could be displayed in a tree structure. Could you help me out by giving an example of how this could be done? Can you make a figure, or point to one that exists?

Thanks.
JWB.

**Comment by hyanwong** [comment]
Just looking over feedback issues: I think this is mainly a search problem, and one that I previously encountered with searches for _Panthera_, before NCBI changed _Uncia uncia_ to _Panthera uncia_. What I think would work is that if a user types a genus name into the search box, if the genus is 'nonmonophyletic' (i.e. a genus label that does not apply to all descendants of a clade), then the autocomplete in the search box should provide a list of binomial species instead (or in addition to) the problematic genus name. So typing "Nebela" should result in autocompletions such as "Nebela tincta", "Nebela maxima" etc: these taxa presumably _do_ exist in the synth tree.

**Comment by mtholder** [comment]
closing this - these were in reference to an old tree.
