### ISSUE TITLE
Errore

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#372]
I can not enter entries in the search box.
The words "Error loading context value" appear to me: how can I resolve? Thank you.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Siro](mailto:servizieprogettazione@gmail.com) 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by jimallman** [comment]
Please try again! We had some outages today, but the name-resolution service has been restored.
