### ISSUE TITLE
Insectivora is abandoned

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#375]
Is abandoned please update the tree

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Danielle](mailto:dewilson377@gmail.com) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott796664/Insectivora](https://tree.opentreeoflife.org/opentree/opentree9.1@ott796664/Insectivora) 
Target node label   |   Insectivora 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott796664 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.m.wikipedia.org/wiki/Insectivora

**Comment by mtholder** [comment]
fixed in previous OTT
