### ISSUE TITLE
Pelmatozoa no longer valid

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#376]
It is no longer a classification

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Danielle 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott451020/Echinodermata](https://tree.opentreeoflife.org/opentree/opentree9.1@ott451020/Echinodermata) 
Target node label   |   Echinodermata 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott451020 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://www.accessscience.com/content/pelmatozoa/495400

**Comment by mtholder** [comment]
this is coming to OTT via NCBI. Closing this, as we'll need to have it fixed there.
