### ISSUE TITLE
Honeybee tree

### ISSUE THREAD

**Issue by vishwasgowda** [OpenTreeOfLife/feedback#378]
Hello OpenTreeOfLive,

I am Vishwas, I am working analyzing several species of honeybee data. I was suggested to run PGLS analysis, in order to do that I need the tree. My species (Apis mellifera, Apis cerana, Apis florea, Apis dorsata and Bombus impatiens). I was wondering if there is a possibility to get the tree to compare these species. I appreciate if you could get back to me at your earliest convenience.

Thank you
Vishwas

**Comment by mtholder** [comment]
curl -X POST https://api.opentreeoflife.org/v3/tree_of_life/induced_subtree -H "content-type:application/json" -d '{"ott_ids":[42692, 625771, 625767, 461631, 461645]}'
    {
       "broken": {},
       "newick": "((((Bombus_impatiens_ott42692)mrcaott1840ott1854)mrcaott1840ott61355)mrcaott470ott1840,((('Apis mellifera (species in domain Eukaryota) ott461645')mrcaott11707ott30259,(((Apis_cerana_ott625771)mrcaott26937ott181524)mrcaott26937ott625758,(Apis_dorsata_ott625767,(Apis_florea_ott461631)mrcaott461631ott461668)mrcaott61839ott461631)mrcaott26937ott61839)mrcaott11707ott26937)mrcaott11707ott62412)mrcaott470ott11707;",
       "supporting_studies": [
         "pg_2604@tree6043",
         "ot_1053@tree1",
         "ot_1059@tree1"
       ]
       }
