### ISSUE TITLE
redesign feedback page

### ISSUE THREAD

**Issue by arlin** [OpenTreeOfLife/feedback#381]
Clicking on "Feedback" opens https://tree.opentreeoflife.org/contact, which is entitled "Contact".  The page says "We have three public google groups" and provides links, then mentions github and provides links, then mentions a public chat room on Gitter, then provides a button under "Comments" labeled "Add a new topic", followed by a listing of previous comments.  Clicking the button provides a choice of topic categories including bug report, taxonomy issue, suggest a tree, etc.  To summarize, the feedback page gives access to 8 main actions, the first 7 of which are clicking on various links. 

I think this could be improved.  @jar398 pointed out to me that this is how users can suggest trees, but a user who wants to suggest a tree is probably going to be confused by what happens when the feedback page is loaded, because (1) it's called "Comments", (2) the action to suggest a tree is the 8th item, at the bottom, and (3) this action is actuated via "Comments" --> "Add a new topic" which doesn't sound like the answer to "how do I suggest a tree to include".  In general, this design seems tuned to more advanced users who might want to get involved.   

I would suggest to redesign this, to respond to various use cases in order of frequency
* naive user wants to leave comment with no question or suggestion like "this is great!" 
* naive user wants to ask a question or make a suggestion of a non-technical nature.  Can you support common names?  How can I use this in my class?  Is this project still active?  
* knowledgeable user wants to make a technical suggestion regarding interfaces or content (taxonomy or phylogeny)
* knowledgeable user wants to join project or contribute 

Based on that, here is what I would suggest
1.  Take all the geeky stuff at the top, which most users won't understand, and put it on a separate page accessed by a top-level menu item called "Get involved".   
1.  Focus the "Feedback" page solely on browsing and adding to the list of topics (currently at the bottom)
   - rename the page from "Contact" to "Feedback"
   - remove the stuff at the top
   - at the top of the page, list the topic categories explicitly so that users can see what kinds of options are being solicited, e.g., we encourage you to click "Feedback" below to make a comment, suggest a feature, recommend a tree to add, point out possible problems with taxonomy or phylogeny, or anything else

**Comment by jar398** [comment]
Actually it didn't occur to me to use "Feedback" to suggest a tree. I had in mind the "show comments" interface from a node in the tree browser. Many of your comments may apply there as well. It's sort of odd that two interfaces for the same thing are available at the same time, but it is important that (a) you can give feedback even when you're not at a node, (b) you can see and give feedback that becomes associated with the current node.

**Comment by jimallman** [comment]
> it is important that (a) you can give feedback even when you're not at a node, (b) you can see and give feedback that becomes associated with the current node.

Exactly. Note that by default, comments are associated with the current URL, but of course we can disregard this if it's clear they're talking about e.g. Mammalia

**Comment by mtholder** [comment]
closing because I created an issue in opentree repo for this.
