### ISSUE TITLE
taxon search on "tectaria subglabra" hangs

### ISSUE THREAD

**Issue by arlin** [OpenTreeOfLife/feedback#383]
Go to main viewer, put "tectaria subglabra" in the search box (with "All life" selected, but I think this doesn't matter), and hit return.  It just hangs forever with the "search in progress" message.  By contrast, "Homo sapiens" immediately returns a positive result and "whatever" immediately returns a negative result ("no results found").

**Comment by jimallman** [comment]
Other funky test values:
- "homo subglabra" works
- "tectaria" (bare word) works
- "tectaria " (single space after) fails
- "tectariaa " (extra "a", single space after) 

Entering string manually (vs. pasting from @arlin's issue) gives the same results, so it's not a subtle Unicode problem. Odd.

**Comment by jimallman** [comment]
Also, here's the return message I see when this fails (500 errors):
```json
{
  "message" : "String index out of range: -1",
  "exception" : "StringIndexOutOfBoundsException",
  "fullname" : "java.lang.StringIndexOutOfBoundsException",
  "stacktrace" : [ "java.lang.String.substring(String.java:1931)", "org.opentree.tnrs.queries.SingleNamePrefixQuery.runQuery(SingleNamePrefixQuery.java:188)", "org.opentree.taxonomy.plugins.tnrs_v3.autocomplete_name(tnrs_v3.java:160)", "java.lang.reflect.Method.invoke(Method.java:498)", "org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:57)", "org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)", "java.lang.reflect.Method.invoke(Method.java:498)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]
}
```

**Comment by mtholder** [comment]
curl -X POST https://api.opentreeoflife.org/v3/tnrs/autocomplete_name -H "content-type:application/json" -d  '{"name":"tectaria subglabra","context_name":"All life"}'

generates a exception in the java code. So a taxomachine issue. (and the opentree webapp should probably be handling the exception more gracefully).

**Comment by mtholder** [comment]
oops @jimallman  you beat me to it, sorry for the static....

I'll look at the java code now...

**Comment by jimallman** [comment]
> the opentree webapp should probably be handling the exception more gracefully

True that. I'll add a minimal message like 
`Error <click for details>, please modify your search and try again.`

**Comment by jimallman** [comment]
PR #1143 (above) shows a server-side error like so (details are hidden until user clicks link):
<img width="365" alt="screen shot 2018-04-13 at 4 29 44 pm" src="https://user-images.githubusercontent.com/446375/38757118-d7471b90-3f39-11e8-909e-da9a8048e8b6.png">

**Comment by jimallman** [comment]
I realize the treatment above is not pretty, but the synth-tree viewer doesn't use our typical site footer (full-width for a generous details display). When I repeat this fix in curation app, I'll use the footer display for details.

**Comment by jimallman** [comment]
Here are the two TNRS error displays in the study editor:
<img width="1010" alt="screen shot 2018-04-18 at 12 19 28 pm" src="https://user-images.githubusercontent.com/446375/38945419-761fadcc-4304-11e8-89c6-d32eae5b70ab.png">
<img width="1012" alt="screen shot 2018-04-18 at 12 27 07 pm" src="https://user-images.githubusercontent.com/446375/38945420-7631ddda-4304-11e8-8944-53d210872059.png">

**Comment by mtholder** [comment]
closing because this was a taxomachine issue
