### ISSUE TITLE
Dotted lines?

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#386]
What do the dotted lines mean? What do the solid lines mean?

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Danielle Wilson 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by mtholder** [comment]
If you click on the grey oval with the word "Legend" above the tree, the page should show you a key to the visual elements used on the page. Branches that are placed entirely based on the taxonomy are dashed. The solid edges have some support from at least one published phylogenetic tree.
