### ISSUE TITLE
Servers down?

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#388]
Hello,
I am currently unable to access your webpage or download anything through R. Just wondering if the server is down or any other issue? Have double checked this with multiple devices.
Thanks,
Mike

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Mike](mailto:michaelmixalit@gmail.com) 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by mtholder** [comment]
Thanks for reporting this. The server is being *very* slow for me too. I'll try to diagnose the issue. I can `ssh` into the front-end and the back-end.  But something is definitely not working as intended...

**Comment by mtholder** [comment]
seems to be more responsive now. I did try to restart apache, but it is acting more like a general network latency problem with wherever the server sits (as opposed to something that I fixed).
