### ISSUE TITLE
Obsolete species, markes as deleted in GBIF

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#389]
Only present from GBIF which says "This species was deleted on 14 February 2017"

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott6154189/Certhidea-ridgwayi](https://tree.opentreeoflife.org/opentree/opentree9.1@ott6154189/Certhidea-ridgwayi) 
Target node label   |   Certhidea ridgwayi 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott6154189 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.gbif.org/species/7844375

**Comment by mtholder** [comment]
fixed in old OTT
