### ISSUE TITLE
Second try - New curation app. 

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/feedback#39]
New curation app.

June 18, 2014

Study:
Pildain, María Belén, and Mario Rajchenberg. "The phylogenetic position of Postia sl (Polyporales, Basidiomycota) from Patagonia, Argentina." Mycologia 105.2 (2013): 357-367.
1.  Two records were created. I guess one is the Phylografter record – this can be confusing because the info within them is different i.e., mapped OTUs differ.

pg_2339
ot_21
1.  This study was faster and easier to map that the previous one – since this is a strict systematic study on a fungal genus, so no strains were included as OTUs. However, there were still some OTUs that were not mapped automatically even though these names should be in OTT (or will be once we get the new IF). Below are these OTUs. I would like to know if this is because we are counting with an old version of IF or because information on synonyms are not being incorporated into OTT? This is an important issue since Fungi has TONS of synonyms. If this is an issue of using an old version of IF, then it would be ok.
- Fibroporia gossypium (Speg.) Parmasto 1968, (also see Species Fungorum: Antrodia gossypium); Fomitopsidaceae
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=330869
- Oligoporus balsameus (Peck) Gilb. & Ryvarden 1985, (also see Species Fungorum: Postia balsamea); Fomitopsidaceae
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=105571
- Postia placenta (Fr.) M.J. Larsen & Lombard 1986, (also see Species Fungorum: Rhodonia placenta); Polyporaceae
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=103728
- Oligoporus rennyi (Berk. & Broome) Donk 1971, (also see Species Fungorum: Postia rennyi); Fomitopsidaceae
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=318944
- Oligoporus lacteus (Fr.) Gilb. & Ryvarden 1985, (also see Species Fungorum: Tyromyces lacteus); Polyporaceae
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=105579
1. Selection of ingroup is ok, selection of root can be confusing, maybe select outgroup option? 
2. After selecting preferred tree, I got a message: Conflicts found! In one of the trees. This was because in the phylogeny the species Postia disecta appear as paraphyletic. This is a very good issue to point out, but I wonder what I should do as a curator? Will this prevent the study to pass through tree machine? This study is supposed to be already published…so what would be the next step for the submitter? 
3. After mapping all but 3 OTUs (species names in IF http://www.indexfungorum.org/names/NamesRecord.asp? RecordID=110921–had no synonym - ), selecting ingroup, selecting preferred tree, completing metadata etc etc, this study was only 66% quality. Is this because of the conflict? I think it was 90% before starting the curation process.

**Comment by mtholder** [comment]
@jimallman it looks like the use of autocompleteBoxQuery for TNRS is causing us to miss synonyms. At least for the first of @rgazis's examples:

```
$  ottautocomplete -cFungi 'Fibroporia gossypium'
using "http://devapi.opentreeoflife.org" for taxomachine
[]
$  ottContextTNRS -cFungi 'Fibroporia gossypium'
using "http://devapi.opentreeoflife.org" for taxomachine
{
  "context": "Fungi", 
  "governing_code": "ICBN", 
  "matched_name_ids": [
    "Fibroporia gossypium"
  ], 
  "results": [
    {
      "id": "Fibroporia gossypium", 
      "matches": [
        {
          "dubious_name": false, 
          "flags": [], 
          "is_approximate_match": false, 
          "is_homonym": false, 
          "is_perfect_match": false, 
          "is_synonym": true, 
          "matched_name": "Antrodia gossypium", 
          "matched_node_id": 450183, 
          "matched_ott_id": 69883, 
          "nomenclature_code": "ICBN", 
          "parent_name": "Antrodia", 
          "rank": "", 
          "score": 1.0, 
          "search_string": "fibroporia gossypium", 
          "source_name": "ott", 
          "synonym_or_homonym_status": "known", 
          "unique_name": "Antrodia gossypium"
        }
      ]
    }
  ], 
  "unambiguous_name_ids": [], 
  "unmatched_name_ids": []
}
```

**Comment by mtholder** [comment]
ottContextTNRS is https://gist.github.com/mtholder/fb8110613cea97baa37d
ottautocomplete is https://gist.github.com/mtholder/c6b1c44a2332d44efee0

**Comment by mtholder** [comment]
Hi, @rgazis Thanks for the feedback. It looks like all of those names are in OTT, but the way that we are accessing the taxonomic name resolution service is not checking the synonyms. We'll work on fixing that.
