### ISSUE TITLE
simple clarification to message for missing taxon 

### ISSUE THREAD

**Issue by arlin** [OpenTreeOfLife/feedback#396]
Go to the home page and, in the "Search for taxon" box, enter something that is not in the synth tree, e.g., "Brownimecia" (extinct ant).  

The result is non-ideal.  At the top is the tree view strip which says something like "Loading tree" and has menu items that are not actionable or not relevant to the result message, which says
> This taxon is in our taxonomy but not in our tree synthesis database. This can happen for a variety of reasons, but the most probable is that is has a taxon flag (e.g. incertae sedis) that causes it to be pruned from the synthetic tree. See the taxonomy browser for more information about this taxon.

I actually looked around for a button to link to the taxon entry, and I even started writing out a bug report before I realized that there already is a link ("See the taxonomy browser"), it's just hiding at the end of the paragraph instead of the beginning.  If the user is searching for "Brownimecia" then the way to satisfy the user is to tell them something about Brownimecia, so I think that the result page should feature the taxon link at the beginning, e.g., "Brownimecia is in our taxonomy (here), but ..."

Also, change "is that is has" to "is that it has".  Actually one could just re-write the message more concisely as
> This taxon is in our taxonomy (Brownimecia) but not in the synthetic tree.  The reason is typically that the taxon is extinct or cannot be placed reliably (incertae sedis).

**Comment by mtholder** [comment]
closing due to creating an issue in opentree repo for this.
