### ISSUE TITLE
Molluscs in the cnidarians

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#397]
The node ([Zygochlamys + Favites halicora])  which is placed in the cnidarians contains about 600 scallop species. I can't figure out how this might have happened, 

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree9.1@mrcaott18935ott28681/Zygochlamys--Favites-halicora](https://tree.opentreeoflife.org/opentree/argus/opentree9.1@mrcaott18935ott28681/Zygochlamys--Favites-halicora) 
Target node label   |   [Zygochlamys + Favites halicora] 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   mrcaott18935ott28681 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Adamussium, http://www.marinespecies.org/aphia.php?p=taxdetails&id=577993

**Comment by hyanwong** [comment]
This also results in duplicate species in radically different places on the tree, for instance https://tree.opentreeoflife.org/opentree/argus/opentree9.1@ott449041 and https://tree.opentreeoflife.org/opentree/argus/opentree9.1@ott6370755 (both _Placopecten magellanicus_)

**Comment by TonyRees** [comment]
Pectiniidae Vaughan & Wells, 1943 is a former family in Cnidaria as above, based on the coral genus Pectinia Blainville, 1825; presently a synonym of Merulinidae according to WoRMS. Placopecten, however, belongs in Pectinidae Wilkes, 1810 (-i- not -ii-) which is the bivalve family. Evidently someone has put it in the wrong family instance at one time, presumably now corrected. Cheers - Tony

**Comment by hyanwong** [comment]
Someone has flagged this up again on OneZoom. This would be a good test of providing feedback from OneZoom through to the OpenTree. It's not clear to me how we would show on OneZoom that  a problem has already been flagged up at this node (ping @snacktavish), especially as I can't find any trace of a link to this issue on the current page at https://tree.opentreeoflife.org/opentree/argus/opentree10.4@mrcaott18935ott28681/Favites-halicora--Zygochlamys

It looks like this in *not* fixed in nexttree (https://nexttree.opentreeoflife.org/opentree/argus/opentree11.0@mrcaott18935ott34488/Favites-halicora--Montastraeidae). I'm guessing this is because nexttree is not using the new IRMNG dataset?

**Comment by kcranston** [comment]
Ok, folks. I think this is fixed in the latest taxonomy draft (which should be up on dev next week). Thanks for your patience!

**Comment by hyanwong** [comment]
This is *fantastic*. Thanks for all your hard work @kcranston - I hope it is more generally useful (not just for molluscs / cnidaria) too.

**Comment by mtholder** [comment]
fixed in previous OTT
