### ISSUE TITLE
Missing in Bacteria

### ISSUE THREAD

**Issue by hdliv** [OpenTreeOfLife/feedback#4]
Lentisphaerae  <- this groups comes in from SILVA

**Comment by jar398** [comment]
Looks to me like it's there:
http://dev.opentreeoflife.org/opentree/argus/ottol@261999/Lentisphaerae

**Comment by hdliv** [comment]
Sorry for not being clear.  The parent should be Bacteria and not Verrucomicrobia...which is why I didn't find it.

**Comment by jar398** [comment]
When I move things around I like to leave evidence behind. If you happen to have a URL for a paper or database entry that supports this placement that would be most welcome. Otherwise that's fine, I'll just leave a pointer to this issue.

**Comment by hdliv** [comment]
Lentisphaerae was a phylum in SILVA, I believe.  Thanks.

**Comment by jar398** [comment]
This change will be made in next taxonomy build.
