### ISSUE TITLE
404 on newick download of the tree

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/feedback#40]
http://files.opentreeoflife.org/other/curnewicks/life_synth.tre

gives a 404.

**Comment by mtholder** [comment]
It should be http://files.opentreeoflife.org/other/curnewicks/life_synth.tre.gz (.gz was missing) what is the source of the link?

**Comment by kcranston** [comment]
This page:

http://files.opentreeoflife.org/other/curnewicks/index.html

**Comment by jar398** [comment]
Index page fixed.

**Comment by josephwb** [comment]
So, those are _really_ old trees. It was just set up to easily share with
the empirical folks to check draft trees. It didn't really work as a method
of communication (hence, the age of the trees).

We should either 1) get rid of this entirely, or 2) put the most current
trees up.

JTB.

**Comment by jar398** [comment]
They are very old, yes.  Funny that the folder is called 'curnewicks'. I guess they were current at the time. Stephen set this up for debugging only, I think. I put the dates in the index file, so we'd have some clue as to what they were.

The current tree is in files.opentreeoflife.org/trees/draftversion1.tre.gz . I can't find any link to it...  maybe there is another copy in a more official location?  There ought to be a link to it from the 'developer resources' page, anyone care to take care of this?

To redeploy from a checkout, do 
./push.sh -c ../../deployed-systems/development/ot10.config files
from the opentree/deploy directory.

Only the smallish files for the files site are in git. I put the biggish ones there manually.

**Comment by kcranston** [comment]
I can tackle the developer resources page later today

**Comment by jar398** [comment]
Recovered trees/index.html
https://github.com/OpenTreeOfLife/opentree/commit/255dc6de23dd9108c2fab1a11b1cdb295ca601f1 .
also recovered trees/draftversion1.tre.gz (the 'production' tree)

Nobody should be pointing to curnewicks which are only for debugging.  Will keep this issue open until the link from the developer resources page is removed (and replaced presumably with a link to trees/ ).

**Comment by josephwb** [comment]
I think we've abandoned curnewicks for debugging. It is safe to chuck this.
JTB.
