### ISSUE TITLE
script

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#406]
hello <script>alert('xss')</script>

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [ejm](mailto:ejmctavish@gmail.com) 
Upvotes   |   0 
URL   |   [devtree.opentreeoflife.org/opentree/argus/opentree10.3@ott93302](https://devtree.opentreeoflife.org/opentree/argus/opentree10.3@ott93302) 
Target node label   |   cellular organisms 
Synthetic tree id   |   opentree10.3 
Synthetic tree node id   |   ott93302 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by snacktavish** [comment]
This was me, closing issue.

**Comment by mtholder** [comment]
me reopening to test...

**Comment by mtholder** [comment]
oops this is devtree...
