### ISSUE TITLE
This is a <script>alert('hi');</script> bad test.

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/feedback#407]
More naughty input here <script>alert('hello');</script>.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Jim Allman](https://github.com/jimallman) 
Upvotes   |   0 
URL   |   [devtree.opentreeoflife.org/opentree/argus/opentree10.1@ott93302/cellular-organisms](https://devtree.opentreeoflife.org/opentree/argus/opentree10.1@ott93302/cellular-organisms) 
Target node label   |   cellular organisms 
Synthetic tree id   |   opentree10.1 
Synthetic tree node id   |   ott93302 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   <script>alert('hola');</script>example.com

**Comment by jimallman** [comment]
Another <script>alert('reply!');</script> bit of mischief.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Jim Allman](https://github.com/jimallman) 
Upvotes   |   0

**Comment by snacktavish** [comment]
closing for the time being, feel free to re-open

**Comment by sriram-Alkimi** [comment]
&lt;script&gt;alert(&quot;Hi&quot;);&lt;/script&gt;
