### ISSUE TITLE
Can't get to developer resources page on small screen

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#41]
I'm on an iphone and can't get to the developer resources page. It always takes me to the taxon search box instead.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [JAR](mailto:Rees@nescent.org) |
| Upvotes | 0 |
| URL | [devtree.opentreeoflife.org/opentree/argus/otol.draft.22@127](http://devtree.opentreeoflife.org/opentree/argus/otol.draft.22@127) |
| Target node label | cellular organisms |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 127 |
| Source tree id(s) | ncbi:131567 |
| Open Tree Taxonomy id | 93302 |
| Intended scope |  |

**Comment by jimallman** [comment]
Confirmed with same behavior on Android (but I think the actual behavior is to stay on the current page, with a mangled layout). Chasing this now..

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jim Allman](https://github.com/jimallman) |
| Upvotes | 0 |

**Comment by jimallman** [comment]
@jar398, This is working now on Android (on **devtree**, of course). Please let me know what you see on iOS.

**Comment by jar398** [comment]
No, refreshed and tried again and I can't get to _any_ of the 'about'
pages.​

**Comment by jar398** [comment]
Still fails. I select the 'About' dropdown, scroll down so I can see 'Developer resources', try to select 'Developer resources', and....   the dropdown goes away, and the little waiting-for-network wheel spins, but I don't get the Developer resources page.

**Comment by mtholder** [comment]
moved to opentree repo
