### ISSUE TITLE
Trox in Insecta:Psocoptera:Trogiidae, should be in Insecta:Coleoptera:Trogidae

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#411]
The members of the beetle family Trox are found in two places: Insecta:Psocoptera:Trogiidae and Insecta:Coleoptera:Trogidae.

As far as I can tell, there is not genus Trox in the Trogiidae, so all members of that genus are beetles and should be in Trogidae.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [John Boyle](mailto:john.h.boyle@gmail.com) 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Trogidae

**Comment by opentreeapi** [comment]
Members of Omorgus and Afromorgus are also currently divided among Pscoptera:Trogiidae and Coleoptera:Trogidae; all should be in Coleoptera:Trogidae
https://en.wikipedia.org/wiki/Trogiidae
https://en.wikipedia.org/wiki/Trogidae

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [John Boyle](mailto:john.h.boyle@gmail.com) 
Upvotes   |   0

**Comment by mtholder** [comment]
fixed in previous OTT (though Afromorgus is now barren in OTT).
