### ISSUE TITLE
Incorrect synonymy (Delia vs Dellia)

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#412]
The taxonomic name reconciliation service considers Diptera:Neohylemyia monticola a synonym of Orthoptera:Dellia monticola. It should probably be a synonym of Diptera: Delia monticola.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [John Boyle](mailto:john.h.boyle@gmail.com) 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://arctos.database.museum/name/Delia%20monticola

**Comment by mtholder** [comment]
fixed in previous OTT
