### ISSUE TITLE
Incorrect synonymy (Orchamoplatus)

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#413]
The taxonomic name reconciliation service considers Orchamoplatus to be a synonym of Orchamus. Since Orchamoplatus is a genus of Hemiptera, and Orchamus is Orthoptera, this is likely incorrect. A google search did not turn up any evidence that there was even an Orchamoplatus genus in the orthoptera, although Hemiptera:Orchamoplatus was originally called Hemiptera:Orchamus, so possibly that is the source of confusion?

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [John Boyle](mailto:john.h.boyle@gmail.com) 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/List_of_whitefly_species

**Comment by opentreeapi** [comment]
Other reference:
https://core.ac.uk/download/pdf/5103593.pdf

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [John Boyle](mailto:john.h.boyle@gmail.com) 
Upvotes   |   0

**Comment by mtholder** [comment]
thanks. Will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/ca74a8d77d2956ca2160d0ee37736f68091ca7a3
