### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#414]
This name is a typo, and it's also a synonym (the current name is Natrix natrix).

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Andrew Durso](mailto:amdurso@gmail.com) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott4946051/Tropidonotus-matrix](https://tree.opentreeoflife.org/opentree/opentree9.1@ott4946051/Tropidonotus-matrix) 
Target node label   |   Tropidonotus matrix 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott4946051 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://reptile-database.reptarium.cz/species?genus=Natrix&species=natrix&search_param=%28%28genus%3D%27natrix%27%29%29

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/e1b5a2185918d1d4e5b3b4f59fe40e53ecfd044a
