### ISSUE TITLE
Two incorrect & misleading taxa

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#415]
Both "Lanthanotidae" and "Crotalidae" are incorrectly placed here; in addition, "Lanthanotidae" is mispelled (correct = Lanthanotidae) & Crotalidae is not widely used (most use Crotalinae within Viperidae). Both should be removed from this view.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Andrew Durso](mailto:amdurso@gmail.com) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree9.1@ott35888/Squamata](https://tree.opentreeoflife.org/opentree/opentree9.1@ott35888/Squamata) 
Target node label   |   Squamata 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott35888 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://reptile-database.reptarium.cz/species?genus=Lanthanotus&species=borneensis&search_param=%28%28taxon%3D%27Lanthanotidae%27%29%29

**Comment by mtholder** [comment]
Lanthanotus fixed in previous OTT. https://github.com/OpenTreeOfLife/edOTTs/commit/69c79bb12f9777280fbb8e22fdbbbc1383820e5a will fix Crotalidae issues.
