### ISSUE TITLE
/studies/find_trees end point down?

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#416]
This example (taken from the API doc) returns nothing. Is there an issue with this end point currently?

```shell
curl -X POST https://api.opentreeoflife.org/v3/studies/find_trees \
 -H "content-type:application/json" -d \
 '{"property":"ot:ottTaxonName","value":"Solifugae","verbose":true}'
```

```json
{
  "matched_studies" : [ ]
} 
```

**Comment by mtholder** [comment]
hmm. that is the correct endpoint. 

    curl -X POST https://api.opentreeoflife.org/v3/studies/fid_studies  -H "content-type:application/json" -d  '{"property":"ot:focalCladeOTTTaxonName","value":"Solifugae","verbose":true}'

returns one study (https://tree.opentreeoflife.org/curator/study/view/ot_509). Certainly searching on the taoxon name for the tree should work...
It could be an indexing bug - we have some very long standing issues with keeping the index up to date. 

Or it could be that we are only indexing the tips labels themselves and not their clades. I can't recall how that indexing step is done; I wasn't involved with the implementation.  

I'll try to look into this some time this week and give you a better answer. @snacktavish is working on getting https://github.com/OpenTreeOfLife/otindex deployed which will replace the old buggy indexer.
