### ISSUE TITLE
Download in Newick format dysfunctional 

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#419]
Starting from a few weeks ago, I cannot download a subtree anymore in Newick format. There seems to have been also some change with the download URL recently. I need to download regularly the vertebrate subtree (https://tree.opentreeoflife.org/opentree/default/download_subtree/node-id/ott801601/Vertebrata) and luckily I have an old version of the tree, which works for my script, but it will become outdated with time :-(

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [mjeltsch](mailto:michael@jeltsch.org) 
Upvotes   |   0 
URL   |   [/contact](None/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by mtholder** [comment]
hmm that is odd that it changed a few weeks ago. we did change some of the back-end software on Monday. I'll try to figure out what is going on. There is a limit on the number of tips that can be downloaded from the web services. But if you have the entire vertebrate tree via a previous download, that seems like a poor explanation...

**Comment by mtholder** [comment]
and thanks for the bug report!

**Comment by opentreeapi** [comment]
Still gives my nothing when I try to download the vertebrate subtree in newick format :-( Maybe you have changed the limits? I manage with smaller subtrees, but e.g. also the amniota phylum fails. The downlaoded filecontains only the string "NEWICK_NOT_FOUND"

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [mjeltsch](mailto:michael@jeltsch.org) 
Upvotes   |   0

**Comment by jimallman** [comment]
Confirmed, this tree won't load, while I'm able to fetch the [primate tree](https://tree.opentreeoflife.org/opentree/opentree10.4@ott913935/Primates) as Newick successfully. Could be a problem with larger clades, or perhaps a "poison pill" (funky Unicode taxon name)?

**Comment by mjeltsch** [comment]
It's working again, thanks. If I reference this tree in a scientific publication, how should I cite it?

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Michael Jeltsch](https://github.com/mjeltsch) 
Upvotes   |   0

**Comment by mtholder** [comment]
Great. General guidelines for citation of parts of the project are at https://tree.opentreeoflife.org/about/open-tree-of-life 
Studies that inform parts of the primate tree can be found in the "Supporting trees" panel for the relevant view of the tree at https://tree.opentreeoflife.org/opentree/argus/opentree12.3@ott913935/Primates if you want to cite the original publications.
