### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by wellcaffeinated** [OpenTreeOfLife/feedback#420]
I've been getting 500 errors recently (within the last week). I haven't changed anything on my end.

Here's the request/response data from chrome devtools:

> Request URL: https://api.opentreeoflife.org/v3/tree_of_life/node_info
> Request Method: OPTIONS
> Status Code: 500 Internal Server Error
> Remote Address: 34.221.232.64:443
> Referrer Policy: no-referrer-when-downgrade
> Connection: close
> Content-Length: 110
> Content-Type: text/plain
> Date: Thu, 13 Sep 2018 20:06:06 GMT
> Server: waitress
> Provisional headers are shown
> Access-Control-Request-Headers: content-type
> Access-Control-Request-Method: POST
> DNT: 1
> Origin: http://wellcaffeinated.net
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by jimallman** [comment]
Just to note the nearly-obvious, this appears to be an error on the CORS "preflight" request before the true API method call. Strange...

**Comment by wellcaffeinated** [comment]
Yes, odd. But it was working last week. No changes...

**Comment by mtholder** [comment]
We did redeploy the back-end server software this week, so that is the likely culprit...

@bredelings , can you look into this?

**Comment by bredelings** [comment]
It looks like there may be some problem with the formatting of the JSON 
you were sending.  I think I've fixed it to give a reasonable response:

$ curl -X POST https://api.opentreeoflife.org/v3/tree_of_life/subtree -d 
'{"yo'
[/v3/tree_of_life/subtree] Error: Could not parse body of call as JSON.

I guess this raises the question: do you think your JSON is OK?

<analysis>

The time of the error was really helpful; it allowed me to find a trace 
in the log for the python wrapper.

The problem was in get_json_or_none( ). For some reason "except 
json.decoder.JSONDecodeError" doesn't work on api, although it does 
locally.  I changed this to "except ValueError:" and now it works.

</analysis>

-BenRI

**Comment by mtholder** [comment]
We should be catching this exception and reporting some 400-type error, or 200 if we want to allow incorrect JSON with the OPTIONS verb.
Treemachine was probably just more lenient and allowed it. I don't see the harm in doing that...

**Comment by wellcaffeinated** [comment]
It seems to be working now. I'm not sure about the json. It should be
correct though...

**Comment by bredelings** [comment]
OK, glad to here things are working.  In retrospect, I don't think there 
was any reason to think the JSON is bad.

Let us know if you have any more questions! :-)

-BenRI

**Comment by wellcaffeinated** [comment]
Thanks!

**Comment by wellcaffeinated** [comment]
Hmm... it started doing the same thing again just now. 
```
Request URL: https://api.opentreeoflife.org/v3/tree_of_life/node_info
Request Method: OPTIONS
Status Code: 500 Internal Server Error
Remote Address: 34.221.232.64:443
Referrer Policy: no-referrer-when-downgrade
Connection: close
Content-Length: 78
Content-Type: text/html; charset=UTF-8
Date: Mon, 17 Sep 2018 18:12:41 GMT
Server: waitress
Provisional headers are shown
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: POST
Origin: http://localhost:8080
Referer: http://localhost:8080/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3554.0 Safari/537.36
```

Response
>  Error: could not connect to 'http://localhost:1984/v3/tree_of_life/node_info'

**Comment by mtholder** [comment]
We had some issues with the deployment of the fix (and the redirections on the servers side were not working for a few minutes). I think it is fixed and the deployment is now working... sorry for the repeated errors.

**Comment by bredelings** [comment]
It is still a 500 error, but not for the same reason.

Port 1984 is where the otcetera server runs.  When we restart it, you'll see this message for a minute until if reloads.  If you see this for longer than about a minute, then if might actually be down.

Hmm... I suppose we could add an explanation to the "can't connect" message, like "Please wait for a minute and try again, you might have caught us in the middle of restarting the API server."

**Comment by jar398** [comment]
Sounds like 503 would be the machine readable version of that situation. But human readable is good too.
