### ISSUE TITLE
missing final ";" in newick string

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#422]
the newick string returned by induced subtree  (api.opentreeoflife.org/v3/tree_of_life/induced_subtree) doesn't have a final ";".

**Comment by bredelings** [comment]
This should be fixed now - thanks for the report!

**Comment by fmichonneau** [comment]
Thanks for fixing it quickly. I noticed that the tol_subtree endpoint is also missing the ";"

**Comment by bredelings** [comment]
Also fixed!  Good catch.
