### ISSUE TITLE
Copyright of the data

### ISSUE THREAD

**Issue by oseiskar** [OpenTreeOfLife/feedback#424]
This is a cool project, but it is unclear under what conditions the tree _data_ can be downloaded, used and redistributed. Can this information be found somewhere on the project website? If I download the data from, say, https://tree.opentreeoflife.org/about/synthesis-release/v10.3 am I allowed to publish derivative works of it for non-commercial purposes? 

(because I already did a few year ago by making this visualization http://oseiskar.github.io/tree-of-life/ but I can unpublish it if this is not OK)

**Comment by snacktavish** [comment]
Our tree and taxonomy are licensed CC0, so available for any and all downstream uses! So go for it. We will add the license directly to the download page. https://creativecommons.org/publicdomain/zero/1.0/
