### ISSUE TITLE
Can't add tree to collection

### ISSUE THREAD

**Issue by wdahdul** [OpenTreeOfLife/feedback#427]
I can't seem to add a tree to my tree collection (Ostariophysi • wdahdul/ostariophysi). I'm able to go through the steps to add a tree (for example, selecting the tree from Zanata and Vari 2005, and specifying a commit message for inclusion of the tree), but the collection remains at 0 trees.

**Comment by snacktavish** [comment]
Huh, I'm not sure what went wrong, but I did successfully just add that tree to that collection. Does it look OK to you?

**Comment by wdahdul** [comment]
Yes it works! I didn't realize I needed hit the little blue + button next to the selected tree before saving the edit.
