### ISSUE TITLE
Amiiformes has only one extant species, wrongly contains a fossil

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#43]
The synthetic tree here does not follow DeepFin, and is missing Lepisosteiformes (e.g. anything in genus Lepisosteus)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [hyanwong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@329630/Amiiformes](http://tree.opentreeoflife.org/opentree/argus/ottol@329630/Amiiformes) |
| Target node label | Amiiformes |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 635721 |
| Source tree id(s) | ncbi:7921,gbif:494,irmng:11975 |
| Open Tree Taxonomy id | 329630 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
I need to modify the paleodb-via-gbif-only-means-extinct heuristic to also be activated by the case where the taxon also comes from IRMNG - because IRMNG imports paleodb.
Re Lepisosteidae, it's inferred to be extinct - I gather that's incorrect (since it has an NCBI record). This will have to be patched.

**Comment by hyanwong** [comment]
Re Lepisosteidae: this has 7 extant species in 2 genera: http://www.fishbase.org/summary/FamilySummary.php?ID=34 (also see e.g. https://en.wikipedia.org/wiki/Gar)

**Comment by hyanwong** [comment]
As of OpenTree 11.4 this is correct, but OpenTree 12.3 wrongly includes yet another fossil bowfin, _Amia media_, which needs flagging as extinct. I have also flagged some newly introduced extinct Lepisosteidae species in 12.3 at https://github.com/OpenTreeOfLife/feedback/issues/455. Once these two extinct/extant issues are solved, this issue can be closed

**Comment by mtholder** [comment]
closing because I closed #455
