### ISSUE TITLE
TEST ascii cow and emoji

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#435]
_______
< I'm a cow >
 -------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Emily Jane McTavish](https://github.com/snacktavish) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree10.4@ott1066581/Bos](https://tree.opentreeoflife.org/opentree/opentree10.4@ott1066581/Bos) 
Target node label   |   Bos 
Synthetic tree id   |   opentree10.4 
Synthetic tree node id   |   ott1066581 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by snacktavish** [comment]
🐃

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Emily Jane McTavish](https://github.com/snacktavish) 
Upvotes   |   0

**Comment by opentreeapi** [comment]
<body onload=alert('test1')>

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   EJM
Upvotes   |   0
