### ISSUE TITLE
Geranoaetus albicaudatus is a synonym of Buteo albicaudatus

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#437]
According to GBIF https://tree.opentreeoflife.org/taxonomy/browse?id=458094 and https://tree.opentreeoflife.org/taxonomy/browse?id=6151499 are the same taxon.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Emily Jane McTavish](https://github.com/snacktavish) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree10.4@ott6151499/Geranoaetus-albicaudatus](https://tree.opentreeoflife.org/opentree/argus/opentree10.4@ott6151499/Geranoaetus-albicaudatus) 
Target node label   |   Geranoaetus albicaudatus 
Synthetic tree id   |   opentree10.4 
Synthetic tree node id   |   ott6151499 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.gbif.org/species/7787493

**Comment by mtholder** [comment]
fixed in previous OTT
