### ISSUE TITLE
issue with API availability?

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#439]
I'm getting a high number of failures with the `rotl` tests with this type of response from the server

```
Error: HTTP failure: 502
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/v3/tnrs/match_names">POST&nbsp;/v3/tnrs/match_names</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.opentreeoflife.org Port 443</address>
</body></html>
```

**Comment by mtholder** [comment]
hi @fmichonneau over what time frame have you been seeing problems?

We've had a few sporadic problems crop up in our monitoring ( https://groups.google.com/forum/#!topic/open-tree-monitoring/pxTslrIbj9Y ). But I usually don't look into it unless the cronjob fails twice in a row (a network outage on the host that runs the test can give us some false positives).  So I didn't think we were having major problems.

Perhaps we are having more problems than I realize. I'll mention it on gitter and hopefully one of us will have time in the next few days to look at the server logs and figure out what is causing the issues.

**Comment by fmichonneau** [comment]
I've looked a little more into it, and it looks like the issue is caused by queries to the `match_names` endpoint that include "_" in the taxon names (e.g. " Passer_domesticus"). This didn't use to be an issue.
