### ISSUE TITLE
Show more genera, fewer species

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/feedback#44]
In this view you see a lot of detail for a few genera, but the list of genera itself is curtailed. Maybe it's just me but I wonder if it would be better to use screen real estate to give longer lists of higher taxa (e.g. genera) in preference to longer lists of lower taxa (e.g. species). That is, show as many genera as will fit, and then if there's space left over, start showing species.

**Comment by jar398** [comment]
Here's what I was looking at that prompted the comment:
http://tree.opentreeoflife.org/opentree/otol.draft.22@3168166/Rhodymeniophycidae

**Comment by mtholder** [comment]
old tree
