### ISSUE TITLE
studies/ endpoint down?

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#442]
these endpoints seem to return a 404 with a high frequency:

- https://api.opentreeoflife.org/v3/studies/properties
- https://api.opentreeoflife.org/v3/studies/find_studies
- https://api.opentreeoflife.org/v3/studies/properties

which is causing the automated checks performed by CRAN to fail for the `rotl` package (https://cran.r-project.org/web/checks/check_results_rotl.html)

**Comment by snacktavish** [comment]
Ah, thanks for letting us know. We just changed up how the studies methods are being called. I'll look into what is going wrong!

**Comment by snacktavish** [comment]
OK! Made some progress. Properties and find_studies are behaving correctly now I think. New version of studies API didn't accept a trailing '\', but now it does.

But am having some issues with find_trees. 
I'm running through the data mashup vignette, and find_trees is failing here.
https://github.com/ropensci/rotl/blob/master/vignettes/data_mashups.Rmd#L88

On the server side it appears it is calling  
```curl -X POST https://api.opentreeoflife.org/v3/studies/find_trees -H "content-type:application/json" -d '{"property":"ot:ottId","value":"180195","3":[false],"4":[false]}'```

I'm not seeing where the payload is getting put together in rotl though, or why those other parameters would be getting added. Any ideas?

**Comment by snacktavish** [comment]
Rolled back to previous version of studies API due to further issues! Is there a way to set the api endpoint in rotl? If so, I can try things out on our development server, and see in advance if changes will break things.

**Comment by fmichonneau** [comment]
Thanks! I'll monitor the CRAN check page in the next few days to see if these warnings disappear.

If you edit https://github.com/ropensci/rotl/blob/master/R/base.R#L1 and install the package locally, you can modify the endpoints. The `otl_url()` function takes a `dev` argument that we used in the early phases of development of the package but I don't remember how easy it is to use at this time. Let me know if you need more guidance or if there is anything I can do on my end to make this easier. Thanks!

**Comment by snacktavish** [comment]
Thanks! We just re-ployed the new studies endpoint, but hopefully with the fixes in place. I'll keep an eye on it! 
It does appear that this find_trees problem is independent of the move though?
https://github.com/OpenTreeOfLife/feedback/issues/442#issuecomment-500546717

**Comment by fmichonneau** [comment]
thanks, it does look like it's working now. It looks like the OpenTree API used to be happy to parse unnamed arguments but they are now required to be named which was the cause of the find_trees issue. I fixed it on the rotl side, so I think we're all set. Thanks again for looking into this quickly!
