### ISSUE TITLE
Update taxonomy to deal with synonymies

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#443]
A while ago, I left a comment here regarding the fact that many species appeared in multiple genera in this family. I was encouraged to contact the folks at GBIF to see if they could deal with some of the problems in their own taxonomy, which could then be incorporated into the Open Tree of Life system.

So, I have done that! I am happy to say that the GBIF taxonomy for Piophilidae is much improved over how it was about two years ago. Although I don't always personally agree with the genera each species has been placed in, it is still a substantially more functional classification.

Is it possible now to incorporate the revised GBIF taxonomy into this family on Open Tree of Life?

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Chris Angell](mailto:csangell11@gmail.com) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/ottol@1007135/Piophilidae](https://tree.opentreeoflife.org/opentree/argus/ottol@1007135/Piophilidae) 
Target node label   |   Piophilidae 
Synthetic tree id   |   opentree10.4 
Synthetic tree node id   |   ott1007135 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.gbif.org/species/9503

**Comment by kcranston** [comment]
Awesome! Thanks for letting us know (and for contacting GBIF). As it happens, we are currently working on a re-build with the new GBIF. You will probably see a version with the new NCBI first - that one is already built, just needs to be deployed with a new synthesis tree. Probably by end of October for new GBIF?
