### ISSUE TITLE
This node represents Tephritoidea

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#445]
As the title says, this node represents the traditional superfamily Tephritoidea, which is a more useful name than the current [Blepharoneurinae + Richardiidae]. This taxon is monophyletic, so I believe naming it on the tree is appropriate.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Chris Angell](mailto:csangell11@gmail.com) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree10.4@mrcaott4859ott24836/Blepharoneurinae--Richardiidae](https://tree.opentreeoflife.org/opentree/opentree10.4@mrcaott4859ott24836/Blepharoneurinae--Richardiidae) 
Target node label   |   [Blepharoneurinae + Richardiidae] 
Synthetic tree id   |   opentree10.4 
Synthetic tree node id   |   mrcaott4859ott24836 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://dx.doi.org/10.1016/j.ympev.2004.10.017

**Comment by mtholder** [comment]
Tephritoidea has been added in a previous version of OTT
