### ISSUE TITLE
Eptatretus rubicundus now in its own genus

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#447]
It should be in genus Rubicundus, which is now in the OpenTree. GBIF has changed the name, but this has not been picked up yet, I guess

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree11.4@ott772588/Eptatretus-rubicundus](https://tree.opentreeoflife.org/opentree/argus/opentree11.4@ott772588/Eptatretus-rubicundus) 
Target node label   |   Eptatretus rubicundus 
Synthetic tree id   |   opentree11.4 
Synthetic tree node id   |   ott772588 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://doi.org/10.1111/jzs.12035

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/d4d2d74823d9c0d0b219615c55f3e7be3c2de237
