### ISSUE TITLE
Microhydromys incorrectly synonymised with Rattus

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#448]
E.g. Microhydromys richardsoni  (https://en.wikipedia.org/wiki/Northern_groove-toothed_shrew_mouse) is a completely different beast from _Rattus richardsoni_ https://en.wikipedia.org/wiki/Glacier_rat

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree11.4@ott3610404/Microhydromys](https://tree.opentreeoflife.org/opentree/argus/opentree11.4@ott3610404/Microhydromys) 
Target node label   |   Microhydromys 
Synthetic tree id   |   opentree11.4 
Synthetic tree node id   |   ott3610404 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.iucnredlist.org/species/48002425/22459257

**Comment by mtholder** [comment]
fixed in previous OTT. thanks.
