### ISSUE TITLE
Chiropodomys pusillus incorrectly synonymised with Haeromys pusillus

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#449]
The OpenTree redirects Haeromys pusillus to Chiropodomys pusillus, but they are different beasts, e.g. https://en.wikipedia.org/wiki/Small_pencil-tailed_tree_mouse vs. https://en.wikipedia.org/wiki/Lesser_ranee_mouse

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree11.4@ott3608659/Chiropodomys-pusillus](https://tree.opentreeoflife.org/opentree/opentree11.4@ott3608659/Chiropodomys-pusillus) 
Target node label   |   Chiropodomys pusillus 
Synthetic tree id   |   opentree11.4 
Synthetic tree node id   |   ott3608659 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.iucnredlist.org/species/9632/22449670

**Comment by mtholder** [comment]
will be fixed in 3.7.2
