### ISSUE TITLE
Gerbillus gleadowi incorrectly synonymised with Millardia gleadowi

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#450]
The current incorrect placement of _Gerbillus gleadowi_ (sister to Millardia), the Little Hairy-footed Gerbil is due to what I think is incorrect synonymy with Millardia gleadowi, the Sand-coloured Metad

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree11.4@ott3608650/Gerbillus-gleadowi](https://tree.opentreeoflife.org/opentree/opentree11.4@ott3608650/Gerbillus-gleadowi) 
Target node label   |   Gerbillus gleadowi 
Synthetic tree id   |   opentree11.4 
Synthetic tree node id   |   ott3608650 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.iucnredlist.org/species/13522/115115596

**Comment by mtholder** [comment]
will be fixed in ott3.7.2
