### ISSUE TITLE
Nystactes noanamae (a synonym of Bucco noanamae), a bird, is in the conger eels

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#451]
I have absolutely no idea how this happened, especially as _Bucco_ is in OTT. _Nystactes_ in OTT seems bizarrely to be synonymised with _Heteroconger_

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree11.4@ott3600719/Nystactes-noanamae](https://tree.opentreeoflife.org/opentree/opentree11.4@ott3600719/Nystactes-noanamae) 
Target node label   |   Nystactes noanamae 
Synthetic tree id   |   opentree11.4 
Synthetic tree node id   |   ott3600719 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.iucnredlist.org/species/22682255/92937287

**Comment by mtholder** [comment]
fixed in previous OTT
