### ISSUE TITLE
Pogonomys loriae incorrectly synonymised with Grammomys dryas

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#452]
_Pogonomys loriae_ (large tree mouse: Australia, Indonesia, and Papua New Guinea) is incorrectly treated as a synonym of the forest thicket rat (_Grammomys dryas_: found in Burundi, Democratic Republic of the Congo, and Uganda). This is a GBIF error: https://www.gbif.org/species/2439198

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/ottol@466608/Pogonomys-loriae](https://tree.opentreeoflife.org/opentree/argus/ottol@466608/Pogonomys-loriae) 
Target node label   |   Pogonomys loriae 
Synthetic tree id   |   opentree11.4 
Synthetic tree node id   |   ott466608 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.iucnredlist.org/species/9455/22437574

**Comment by mtholder** [comment]
will be fixed in ott3.7.2
