### ISSUE TITLE
In OpenTree 12.3, Lepisosteidae contains several extinct spp from taxonomy

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#455]
In particular, _Atractosteus lapidosus_, _Lepisosteus atrox_ and _Nhanulepisosteus mexicanus_ are extinct, but not marked as such in OTT 3.2. Since these are only placed by taxonomy, they should probably not be displayed

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [nexttree.opentreeoflife.org/opentree/opentree12.3@ott904123/Lepisosteidae](https://nexttree.opentreeoflife.org/opentree/opentree12.3@ott904123/Lepisosteidae) 
Target node label   |   Lepisosteidae 
Synthetic tree id   |   opentree12.3 
Synthetic tree node id   |   ott904123 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   Extant listed in https://www.fishbase.in/Nomenclature/FamilySearchList.php?Family=Lepisosteidae

**Comment by hyanwong** [comment]
Edited to refer to 12.3, where this emerges as a problem, rather than 11.4, where the extinct spp are not present in the 3.1 taxonomy file.

**Comment by mtholder** [comment]
not deployed yet, but fixed in newest taxonomy. thanks
