### ISSUE TITLE
A pattern of badly synonymised rodents, including new ones in OpenTree 12.3

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#456]
As well as the incorrectly synonymised rodent species I previously identified in https://github.com/OpenTreeOfLife/feedback/issues/452, https://github.com/OpenTreeOfLife/feedback/issues/450, https://github.com/OpenTreeOfLife/feedback/issues/448, and
https://github.com/OpenTreeOfLife/feedback/issues/449, OpenTree 12.3 has now also introduced a few more incorrect synonyms in the rodents, namely _Hydromys chrysogaster_ with _Melomys caurinus_, and
_Rattus pococki_ with _Mus mayori_. It seems like this is a particularly prevalent pattern in the rodents, and I'm wondering if there's a rogue algorithm running somewhere, either in the OpenTree, or in an upstream provider.

**Comment by mtholder** [comment]
_Melomys caurinus_ added and _Rattus pococki_ added via UI. I'm not sure what the cause of this is, unfortunately.
