### ISSUE TITLE
Primatomorpha 

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#459]
The Dermoptera + Primates clade was christened Primatomorpha on the basis of paleontological and comparative anatomical data in 1991. (see Beard, K. C. 1991b. Vertical postures and climbing in the morphotype of Primatomorpha: Implications for locomotor evolution in primate history, in: Y. Coppens and B. Senut (eds.), Origines de la Bipedie chez les Hominides, pp. 79–87. Editions du CNRS (Cahiers de Paleoanthropologie), Paris.) Virtually all recent genomic data support this clade. The affinities of Scandentia remain controversial with respect to other members of Euarchontoglires.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Chris Beard](mailto:chris.beard@ku.edu) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree12.3@mrcaott786ott112387/Primates--Dermoptera](https://tree.opentreeoflife.org/opentree/opentree12.3@mrcaott786ott112387/Primates--Dermoptera) 
Target node label   |   [Primates + Dermoptera] 
Synthetic tree id   |   opentree12.3 
Synthetic tree node id   |   mrcaott786ott112387 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://doi.org/10.1007/978-1-4899-2388-2_2

**Comment by mtholder** [comment]
Thanks, Chris. We'll see if we can get this name in the taxonomy the next time we build it.

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/3782347deb71b617d0144f2feb4e6689e4360c5c
