### ISSUE TITLE
anonymous topic from new app

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#463]
here's a little body

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [TEST Jim](mailto:jim@ibang.com) 
Upvotes   |   0 
URL   |   [devtree.opentreeoflife.org/opentree/argus/opentree12.3@ott93302](https://devtree.opentreeoflife.org/opentree/argus/opentree12.3@ott93302) 
Target node label   |   cellular organisms 
Synthetic tree id   |   opentree12.3 
Synthetic tree node id   |   ott93302 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by opentreeapi** [comment]
here's a follow-up comment

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [TEST Jim](mailto:jim@ibang.com)
Upvotes   |   0

**Comment by opentreeapi** [comment]
Amazing and perfect job

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Anonimous 
Upvotes   |   0

**Comment by opentreeapi** [comment]
Amazing and perfect job

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Anonimous 
Upvotes   |   0

**Comment by opentreeapi** [comment]
Sorry, the comment was duplicate

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Anonimous 
Upvotes   |   0

**Comment by opentreeapi** [comment]
Here's another anonymous comment,

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [TEST](mailto:JIM) 
Upvotes   |   0

**Comment by jimallman** [comment]
closing since this is in a prominent location
