### ISSUE TITLE
Weirdly placed Ranoidea aurea is synonym for sensibly placed Litoria aurea

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#464]
This taxon, placed high up in the Anura tree, is a synonym for https://tree.opentreeoflife.org/opentree/argus/ottol@414589/Litoria-aurea

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree12.3@ott7666857/Ranoidea-aurea](https://tree.opentreeoflife.org/opentree/argus/opentree12.3@ott7666857/Ranoidea-aurea) 
Target node label   |   Ranoidea aurea 
Synthetic tree id   |   opentree12.3 
Synthetic tree node id   |   ott7666857 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://amphibiansoftheworld.amnh.org/Amphibia/Anura/Pelodryadidae/Pelodryadinae/Ranoidea/Ranoidea-aurea

**Comment by hyanwong** [comment]
This also leads to a misplacing of the family Pelodryadidae, which should be a node just above https://tree.opentreeoflife.org/opentree/opentree12.3@ott245328/Pelodryadinae , if it exists at all in the tree.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/26671b0a479fb7f32aa60327ce0a855ae5ec82a2
