### ISSUE TITLE
Testing ability to save a comment without logging in to github

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#47]
z
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jonathan A. Rees](mailto:jar398@mumble.net) |
| Upvotes | 0 |
| URL | [devtree.opentreeoflife.org/opentree/otol.draft.22@148033/BD1-5](http://devtree.opentreeoflife.org/opentree/otol.draft.22@148033/BD1-5) |
| Target node label | BD1-5 |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 148033 |
| Source tree id(s) | silva:AB015518/#2 |
| Open Tree Taxonomy id | 5246062 |
| Intended scope |  |

**Comment by jimallman** [comment]
yy

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jim Allman](https://github.com/jimallman) |
| Upvotes | 0 |

**Comment by jimallman** [comment]
zzz

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Jim Allman](https://github.com/jimallman) 
Upvotes   |   0

**Comment by jimallman** [comment]
aaa

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jim Allman](https://github.com/jimallman) |
| Upvotes | 0 |
