### ISSUE TITLE
http://files.opentreeoflife.org seems to  be down

### ISSUE THREAD

**Issue by pshustad** [OpenTreeOfLife/feedback#470]
According to https://tree.opentreeoflife.org/about/synthesis-release/v12.3, I should be able to download the synthetic tree from 
http://files.opentreeoflife.org/synthesis/opentree12.3/opentree12.3_tree.tgz

However, files.opentreeoflife.org seems to be down. I do not manage to ping it or access the files

**Comment by mtholder** [comment]
I actually just got the files server back running today, but I think our system adminstrators are still blocking traffic in the aftermath of the hack that affected Open Tree last month (see https://opentreeoflife.github.io/hack/).
I think it should be available in the next day or two at the normal URL.
In the meantime, you can download the file from our backup site. For that file the URL will be:

http://opentreeoflifebackup.org/synthesis/opentree12.3/opentree12.3_tree.tgz
