### ISSUE TITLE
I feel extinct, but I'm not!

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#480]
Needs to updates Homo sapiens to be alive.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Emily Jane McTavish](https://github.com/snacktavish) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree12.3@ott770315/Homo-sapiens](https://tree.opentreeoflife.org/opentree/argus/opentree12.3@ott770315/Homo-sapiens) 
Target node label   |   Homo sapiens 
Synthetic tree id   |   opentree12.3 
Synthetic tree node id   |   ott770315 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   opentreeoflife.org

**Comment by jar398** [comment]
https://github.com/OpenTreeOfLife/reference-taxonomy/blob/93c53a76200917b1fc78fa79c742d2976cd1d80f/curation/amendments.py#L217

**Comment by mtholder** [comment]
fixed in previous OTT
