### ISSUE TITLE
Duplicate branch for Nucleariidae and Fonticula

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#51]
There is already a branch for this at http://tree.opentreeoflife.org/opentree/otol.draft.22@384849/Discicristoidea
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [hyanwong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/otol.draft.22@3136156/Nucleariidae-and-Fonticula-group](http://tree.opentreeoflife.org/opentree/argus/otol.draft.22@3136156/Nucleariidae-and-Fonticula-group) |
| Target node label | Nucleariidae and Fonticula group |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 3136156 |
| Source tree id(s) | ncbi:1001604 |
| Open Tree Taxonomy id | 5353117 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
Nucleariidae and Fonticula group is now marked 'inconsistent' so it's not in the synthetic tree.
