### ISSUE TITLE
The living coelacanths (Latimeria - 2 app) are missing

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#511]
The should belong in this clade. When searched for, they are listed as extinct_inherited.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree12.3@ott760169/Coelacanthimorpha](https://tree.opentreeoflife.org/opentree/argus/opentree12.3@ott760169/Coelacanthimorpha) 
Target node label   |   Coelacanthimorpha 
Synthetic tree id   |   opentree12.3 
Synthetic tree node id   |   ott760169 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   N/a

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/d1b60e6807751d992cd5c9dc42ab24b7fe36525d
