### ISSUE TITLE
Dodos and the Rodrigues solitaire should be marked as extinct

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#514]
They are currently extant on the synthetic tree

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree12.3@ott543770/Raphidae](https://tree.opentreeoflife.org/opentree/argus/opentree12.3@ott543770/Raphidae) 
Target node label   |   Raphidae 
Synthetic tree id   |   opentree12.3 
Synthetic tree node id   |   ott543770 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Rodrigues_solitaire

**Comment by TonyRees** [comment]
Speaking from an IRMNG perspective (also probably as per WoRMS) we only presently distinguish "extant" from "fossil", the latter cuts in from around AD 1500 and before - to include subfossils like Moas etc. I (we) do not have a category for "recently extinct" but I have sometimes thought that we should have one... I will approach WoRMS (who provide the software that supports both systems) and ask for their thoughts, and relay back here if I/we get anywhere further. (Not sure if GBIF etc. have similar logic, I will include Markus on the email). Cheers - Tony Rees, IRMNG

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/9d7b1a0c15ecb9d063857064ea59fd3313e653d2
