### ISSUE TITLE
Why is this a tip?

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#519]
This is a family, but all of it's descendants are pruned as incertae sedis. I guess that's the answer to my question. :P But I am leaving this here as a reminder.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Emily Jane McTavish](https://github.com/snacktavish) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/opentree12.3@ott641537/Dothideomycetidae](https://tree.opentreeoflife.org/opentree/opentree12.3@ott641537/Dothideomycetidae) 
Target node label   |   Dothideomycetidae 
Synthetic tree id   |   opentree12.3 
Synthetic tree node id   |   ott641537 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi

**Comment by mtholder** [comment]
will be fixed (as in not showing up) via flagging https://github.com/OpenTreeOfLife/edOTTs/commit/b66c226a31360e82fd619f64debd333e9917d2c6
