### ISSUE TITLE
Zygomycota has only a single leaf

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#52]
This is presumably an artifact, and should be somehow merged into http://tree.opentreeoflife.org/opentree/otol.draft.22@837887/Mucoromycotina
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [hyanwong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@4115686/Zygomycota](http://tree.opentreeoflife.org/opentree/argus/ottol@4115686/Zygomycota) |
| Target node label | Zygomycota |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 846801 |
| Source tree id(s) | if:90405,gbif:96,irmng:215 |
| Open Tree Taxonomy id | 4115686 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
Zygomycota is no longer in the TNRS.
