### ISSUE TITLE
Duplicate of Piezorhina cinerea

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#520]
https://tree.opentreeoflife.org/taxonomy/browse?id=423790
This is the same taxon

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Emily Jane McTavish](https://github.com/snacktavish) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree12.3@ott7662380/Piezorhina-cinera](https://tree.opentreeoflife.org/opentree/argus/opentree12.3@ott7662380/Piezorhina-cinera) 
Target node label   |   Piezorhina cinera 
Synthetic tree id   |   opentree12.3 
Synthetic tree node id   |   ott7662380 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://tree.opentreeoflife.org/taxonomy/browse?id=423790

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/637389ac3504cbf849062f1da859adc6d501933e
