### ISSUE TITLE
Neacomys musseri incorrectly synonymized with Pseudohydromys musseri

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#525]
This taxon (Peruvian / S. American) appears when searching for the endemic New Guinean shew mouse Pseudohydromys musseri

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/ottol@48240/Neacomys-musseri](https://tree.opentreeoflife.org/opentree/argus/ottol@48240/Neacomys-musseri) 
Target node label   |   Neacomys musseri 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott48240 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Musser%27s_shrew_mouse

**Comment by mtholder** [comment]
fixed via manual addition
