### ISSUE TITLE
Taxonomy ignored for Fasciosminthurus quinquefasciatus (Bourletiellida) 

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#526]
This is a collembolan, so even taxonomy should place it within https://tree.opentreeoflife.org/opentree/argus/ottol@269712/Collembola rather than at the highest level of Arthropoda, as it appears to be place in OT13.4. I don't quite know why the normal taxonomic placement is being missed here.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott5008315/Fasciosminthurus-quinquefasciatus](https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott5008315/Fasciosminthurus-quinquefasciatus) 
Target node label   |   Fasciosminthurus quinquefasciatus 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott5008315 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.gbif.org/species/4537070

**Comment by mtholder** [comment]
typo in family name was causing this to join a bogus, unplaced family. Fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/5248afe5816e71740ff48293c241f0a0fc3ecee4
