### ISSUE TITLE
Mola ramsayi is junior synonym of Mola alexandrini

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#527]
Should be synsonymised with https://tree.opentreeoflife.org/opentree/opentree13.4@ott7062423/Mola-alexandrini

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/ottol@3631101/Mola-ramsayi](https://tree.opentreeoflife.org/opentree/argus/ottol@3631101/Mola-ramsayi) 
Target node label   |   Mola ramsayi 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott3631101 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://doi.org/10.1007%2Fs10228-017-0603-6

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/46b614afcfe7d0ee5963b361f0b159f81f19f79d
