### ISSUE TITLE
Personidae in insects is wrong synonym for a snail family

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#529]
Personidae is a family of molluscs, here on the Opentree https://tree.opentreeoflife.org/opentree/argus/ottol@762727/Personidae-family-in-Lophotrochozoa-

The insect family is (I think) base on an extinct fossil, genus †Persona Novokshonov, 1995, and should not contain all these snail species (if it is in fact a valid name at all)

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott6293460/Personidae](https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott6293460/Personidae) 
Target node label   |   Personidae 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott6293460 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   http://grylloblattodea.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1221747

**Comment by mtholder** [comment]
see https://github.com/OpenTreeOfLife/feedback/issues/515
