### ISSUE TITLE
Griphopithecus is extinct...

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#53]
... but appears in the synthetic tree
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [hyanwong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/otol.draft.22@3062049/Griphopithecus](http://tree.opentreeoflife.org/opentree/otol.draft.22@3062049/Griphopithecus) |
| Target node label | Griphopithecus |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 3062049 |
| Source tree id(s) | gbif:4827648,irmng:1232721 |
| Open Tree Taxonomy id | 4117747 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
extinct in ott 2.9draft12
