### ISSUE TITLE
Snail genus Ficus contains many plant species

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#530]
e.g. Ficus religiosa

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott1068336/Ficus](https://tree.opentreeoflife.org/opentree/opentree13.4@ott1068336/Ficus) 
Target node label   |   Ficus 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott1068336 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Ficus_(gastropod)

**Comment by mtholder** [comment]
woo. that was a mess.
fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/1aadcaca06cbdb8780c72526a83dc593c645ea5d
