### ISSUE TITLE
This species name contains the author (Blume 1825))

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#531]
Might be because Ficus variegata is also a valid name for a species of snail

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott1050104/Ficus-variegata-Blume-1825](https://tree.opentreeoflife.org/opentree/opentree13.4@ott1050104/Ficus-variegata-Blume-1825) 
Target node label   |   Ficus variegata Blume, 1825 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott1050104 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   N/A

**Comment by mtholder** [comment]
It's coming in from NCBI that way. will fix.
