### ISSUE TITLE
Aliceathrips is a thrip, not a grass

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#532]
Classified wrongly in GBIF (see URL)

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott6021346/Aliceathrips](https://tree.opentreeoflife.org/opentree/opentree13.4@ott6021346/Aliceathrips) 
Target node label   |   Aliceathrips 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott6021346 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.gbif.org/species/119419778

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/a4ebd1db4d62616d99dc080fdb3d47ecfa03212d
