### ISSUE TITLE
Acanthocepola is a fish genus

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#533]
Duplicated in the tree. The correct genus is at https://tree.opentreeoflife.org/opentree/argus/ottol@872895/Acanthocepola-genus-in-Deuterostomia-

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott7973657/Acanthocepola](https://tree.opentreeoflife.org/opentree/opentree13.4@ott7973657/Acanthocepola) 
Target node label   |   Acanthocepola 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott7973657 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.fishbase.de/identification/SpeciesList.php?genus=Acanthocepola

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/2881f7e464b2d01d1cac837a8b898f24eed86362
