### ISSUE TITLE
Eugenia is only a plant genus, not a dipteran

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#534]
This genus is a duplicate of the plant genus Eugenia (https://tree.opentreeoflife.org/opentree/argus/ottol@1001998/Eugenia-genus-in-kingdom-Archaeplastida-). As far as I can see, there is no dipteran genus of that name. The instance in GBIF, nested in the diptera (https://www.gbif.org/species/1470783), contains entirely plants:

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/ottol@4387124/Eugenia-genus-in-Opisthokonta-](https://tree.opentreeoflife.org/opentree/argus/ottol@4387124/Eugenia-genus-in-Opisthokonta-) 
Target node label   |   Eugenia 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott4387124 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   N/A

**Comment by mtholder** [comment]
looks like 2 species fugax and silvatica are flies and the rest are plants.
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/13aff870adef14749c0398601007386f5e943179
