### ISSUE TITLE
Cervus timoriensis is a synonym of Rusa timoriensis

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#539]
Synonym of https://tree.opentreeoflife.org/opentree/argus/ottol@1069421/Rusa-timorensis

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott7655648/Cervus-timoriensis](https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott7655648/Cervus-timoriensis) 
Target node label   |   Cervus timoriensis 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott7655648 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://animaldiversity.org/accounts/Rusa_timorensis/

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/abb0b298d02684a10e1245449be5455ad7899328
