### ISSUE TITLE
Subspecies of Cervus Nippon

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#540]
Should be Cervus nippon subsp. mandarinus Milne-Edwards, 1871

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott7655636/Cervus-mandarinus](https://tree.opentreeoflife.org/opentree/opentree13.4@ott7655636/Cervus-mandarinus) 
Target node label   |   Cervus mandarinus 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott7655636 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.gbif.org/species/4262359

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/e1a4e78b4e86e6e2d7b86141083e4b4c6b5ef71e
