### ISSUE TITLE
Synonym of Rusa timorensis

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#541]
According to ITIS, citing Grubb and Groves (1983)

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott7655645/Cervus-tavistocki](https://tree.opentreeoflife.org/opentree/opentree13.4@ott7655645/Cervus-tavistocki) 
Target node label   |   Cervus tavistocki 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott7655645 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=898214

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/b310052bad2600d4a88276517638f21c88dc1e9b
