### ISSUE TITLE
Galidictis ornatus an obsolete name now deleted in GBIF

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#543]
Deleted from GBIF (the only source) as of March 2021, see provided URL.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott7656112/Galidictis-ornatus](https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott7656112/Galidictis-ornatus) 
Target node label   |   Galidictis ornatus 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott7656112 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.gbif.org/species/8927576

**Comment by acornmonkey** [comment]
http://treatment.plazi.org/id/D51587EFFFED9A35F5D41567FD44F8A8

_Galidictis ornatus_ is a synonym of _Galidictis fasciata striata_.

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/06913205fab9ab7d9a916d765a78e0c5a624212f thanks
