### ISSUE TITLE
Majasphaeridium is extinct...

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#55]
...but appears in the synthetic tree
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [hyanwong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/otol.draft.22@846803/Majasphaeridium](http://tree.opentreeoflife.org/opentree/otol.draft.22@846803/Majasphaeridium) |
| Target node label | Majasphaeridium |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 846803 |
| Source tree id(s) | if:585158,gbif:4908209,irmng:1090915 |
| Open Tree Taxonomy id | 4116060 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
fixed in ott 2.9draft12
