### ISSUE TITLE
Ibis pagana is actually Gerandibis pagana

### ISSUE THREAD

**Issue by acornmonkey** [OpenTreeOfLife/feedback#554]
And Ibis is no longer used as a genus.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [None](https://github.com/acornmonkey) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott7657824/Ibis-pagana](https://tree.opentreeoflife.org/opentree/opentree13.4@ott7657824/Ibis-pagana) 
Target node label   |   Ibis pagana 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott7657824 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Gerandibis

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/e31a0b72d9a8a7bb3d75dd6c0425c39931a25f1a thanks
