### ISSUE TITLE
Ibis is no longer used as a genus

### ISSUE THREAD

**Issue by acornmonkey** [OpenTreeOfLife/feedback#555]
Also, it's polyphyletic since both a flamingo and an ibis are placed here.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [None](https://github.com/acornmonkey) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott7657822/Ibis](https://tree.opentreeoflife.org/opentree/opentree13.4@ott7657822/Ibis) 
Target node label   |   Ibis 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott7657822 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/e31a0b72d9a8a7bb3d75dd6c0425c39931a25f1a thanks
