### ISSUE TITLE
Ibidae is no longer used as a family

### ISSUE THREAD

**Issue by acornmonkey** [OpenTreeOfLife/feedback#556]
It is now Threskiornithidae

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [None](https://github.com/acornmonkey) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott6151015/Ibididae](https://tree.opentreeoflife.org/opentree/opentree13.4@ott6151015/Ibididae) 
Target node label   |   Ibididae 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott6151015 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Threskiornithidae

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/e31a0b72d9a8a7bb3d75dd6c0425c39931a25f1a thanks
