### ISSUE TITLE
Cryolophosaurus is actually a theropod

### ISSUE THREAD

**Issue by acornmonkey** [OpenTreeOfLife/feedback#557]
Please remove it from Hadrosauridae

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [None](https://github.com/acornmonkey) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree13.4@ott4947919/Cryolophosaurus](https://tree.opentreeoflife.org/opentree/opentree13.4@ott4947919/Cryolophosaurus) 
Target node label   |   Cryolophosaurus 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott4947919 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Cryolophosaurus

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/9c0a504446fda67d854f5966f90493e04d89ae3f thanks
