### ISSUE TITLE
Adding species doesn't work

### ISSUE THREAD

**Issue by acornmonkey** [OpenTreeOfLife/feedback#558]
I added a species ["Coelophysis" kayentakatae](https://tree.opentreeoflife.org/taxonomy/browse?id=6520432) so that I could map it to Syntarsus kayentakatae in [Langer M.C., 2011](https://tree.opentreeoflife.org/curator/study/view/ot_1335?tab=otu-mapping).

When can I expect the species to show up in the tree and to work like any other taxon?

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [None](https://github.com/acornmonkey) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/curator/study/view/ot_1335?tab=otu-mapping](https://tree.opentreeoflife.org/curator/study/view/ot_1335?tab=otu-mapping) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by mtholder** [comment]
there is definitely an unpredictable lag based on how often we build the synthetic tree. That taxon is present now, so I'll close this issue.
