### ISSUE TITLE
Extinct taxon

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#56]
I have added this to https://github.com/OpenTreeOfLife/reference-taxonomy/issues/116
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [hyanwong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/otol.draft.22@3061087/Killikaike-blakei](http://tree.opentreeoflife.org/opentree/otol.draft.22@3061087/Killikaike-blakei) |
| Target node label | Killikaike blakei |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 3061087 |
| Source tree id(s) | gbif:4974674 |
| Open Tree Taxonomy id | 3607932 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Shows as extinct in 2.9draft12
