### ISSUE TITLE
Name resolution with NCBI taxonomy ID

### ISSUE THREAD

**Issue by CuriousTim** [OpenTreeOfLife/feedback#568]
Is it possible to do node lookups on the synthetic tree using NCBI taxonomy IDs? I find that it is difficult to resolve ambiguities using the TNRS because I have to manually inspect the results. I see that the tree browser already has NCBI taxonomy ID information, but I don't see anything about this in the API documentation.

**Comment by snacktavish** [comment]
Hi!

We don't have a call to do that directly, but there are a couple of options that get there in 2 steps.
You can get the ott_id for an ncbi id using the api call taxon_info, with the argument 'source_id' and then 'ncbi:NCBI_ID
e.g.
'```curl -X POST https://api.opentreeoflife.org/v3/taxonomy/taxon_info -H 'content-type:application/json' -d '{"source_id":"ncbi:4237"}'

There is also a python wrapper for this call in python-opentree
e.g.
https://opentree.readthedocs.io/en/latest/running_examples.html#taxon-information
There's probably a call for it  in R rotl too.

Or, you can do bulk TNRS interactively, but just in one step by uploading a textfile with all the names to https://tree.opentreeoflife.org/curator/tnrs/
You can then map them all pretty quickly, and then download a CSV with all the opentree ott ids.

I'm happy to follow up with more details about any of these if they seem like they would help!

**Comment by CuriousTim** [comment]
Thank you for your help! The API call strategy will do the trick, though it is unfortunate that I have to request one ID at a time.

The interactive TNRS does not allow me to easily compare the NCIB taxonomy ID's between my nodes and the Open Tree of Life node so it is not as useful in this case, but it is a neat resource that I didn't know about. I will probably use it in the future when I only have names.
