### ISSUE TITLE
Resnova in wrong subfamily

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#57]
Resnova belongs in the Massonieae of Hyacinthaceae (Asparagaceae). It is closely related to Ledebouria and Drimiopsis.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Cody](mailto:cchoward@ufl.edu) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/otol.draft.22@3664088/Resnova](http://tree.opentreeoflife.org/opentree/otol.draft.22@3664088/Resnova) |
| Target node label | Resnova |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 3664088 |
| Source tree id(s) | ncbi:208146,gbif:2767728,irmng:1268802 |
| Open Tree Taxonomy id | 85201 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
The reference seems to be http://dx.doi.org/10.1002/fedr.19971080106

**Comment by jar398** [comment]
Looked at draftversion4 in tree browser and Resnova appears to be in Massonieae.
