### ISSUE TITLE
Acinonyx pardinensis is extinct

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#578]
E.g. see refs in https://en.wikipedia.org/wiki/Acinonyx_pardinensis

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/opentree14.9@ott7656114/Acinonyx-pardinensis](https://tree.opentreeoflife.org/opentree/argus/opentree14.9@ott7656114/Acinonyx-pardinensis) 
Target node label   |   Acinonyx pardinensis 
Synthetic tree id   |   opentree14.9 
Synthetic tree node id   |   ott7656114 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://doi.org/10.1016%2Fj.quascirev.2011.05.024

**Comment by davidebbo** [comment]
Doing some further analysis (and working with @hyanwong), there is a large number of species (11651) that are marked as extinct in Wikidata, but not in OpenTree Taxonomy. I have dumped the full list [here](https://gist.githubusercontent.com/davidebbo/16dbd906ed91b2569a5dd38f1036c0f3/raw/ade6cef8a700b41813375aa295360d0d7fc32e8b/Incorrect%2520extinct). Each row has the Wikdata ID, the OTT and the species name.

While we cannot be sure that Wikidata is correct, many do appear to be.

**Comment by mtholder** [comment]
Thanks for providing that list of IDs @davidebbo 
This should be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/c063ba01876156120edc4f655998114343ce3b23 when we deploy the next taxonomy.

**Comment by mtholder** [comment]
https://github.com/OpenTreeOfLife/edOTTs/commit/4006d126e0a288e521f495bc8ee5f54169edb9cb is the commit that will deal with the 11,651 taxa

**Comment by davidebbo** [comment]
Great, thank you @mtholder!
