### ISSUE TITLE
coelacanths are alive

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#584]
They are!

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Emily Jane McTavish](https://github.com/snacktavish) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/opentree14.9@mrcaott773491ott6142863/Latimeria--Latimeroidea](https://tree.opentreeoflife.org/opentree/argus/opentree14.9@mrcaott773491ott6142863/Latimeria--Latimeroidea) 
Target node label   |   [Latimeria + Latimeroidea] 
Synthetic tree id   |   opentree14.9 
Synthetic tree node id   |   mrcaott773491ott6142863 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://en.wikipedia.org/wiki/Latimeria

**Comment by mtholder** [comment]
will be fixed in next OTT (testing now)
