### ISSUE TITLE
Louse genera in passerine tree?

### ISSUE THREAD

**Issue by barke042** [OpenTreeOfLife/feedback#585]
Hi, just browsing the tree and noticed two genera (Cinclosomatiellum and Harpactiacus) that appear to be bird louse genera actually classified within passerrine birds.This would appear to be a problem.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Keith Barker](https://github.com/barke042) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/opentree14.9@mrcaott246ott44866/Polioptila--Harpactiacus](https://tree.opentreeoflife.org/opentree/argus/opentree14.9@mrcaott246ott44866/Polioptila--Harpactiacus) 
Target node label   |   [Polioptila + Harpactiacus] 
Synthetic tree id   |   opentree14.9 
Synthetic tree node id   |   mrcaott246ott44866 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://treatment.plazi.org/id/BF0287A2-FFE2-3A20-09E8-FDAB9524ACC5

**Comment by mtholder** [comment]
thanks. this will be fixed in the next version of the taxonomy by https://github.com/OpenTreeOfLife/edOTTs/commit/94b227460a7bbd3fedf5274e1516f79672dc92c1
