### ISSUE TITLE
More louse issues...

### ISSUE THREAD

**Issue by barke042** [OpenTreeOfLife/feedback#587]
Looks like a bunch more louse genera are showing up here. Probably one or more louse trees got ingested with host names at the tips rather than the louse taxa themselves...

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Keith Barker](https://github.com/barke042) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/opentree14.9@mrcaott246ott5929/Polioptila--Tropidorhynchus](https://tree.opentreeoflife.org/opentree/opentree14.9@mrcaott246ott5929/Polioptila--Tropidorhynchus) 
Target node label   |   [Polioptila + Tropidorhynchus] 
Synthetic tree id   |   opentree14.9 
Synthetic tree node id   |   mrcaott246ott5929 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://treatment.plazi.org/id/BF0287A2FFFD3A3809E8F8D79428AE04/6

**Comment by mtholder** [comment]
will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/6aa3914330b3783918bc4368120c9fb12df7f2cb in the next taxonomy build.
