### ISSUE TITLE
Glomeromycota missing from tree, supposedly due to conflict, but not according to the "conflicting" paper

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#589]
Currently Glomeromycota is marked as non monophyletic:

https://tree.opentreeoflife.org/opentree/argus/ottol@385878/Glomeromycota

But the study that purportedly "breaks" the monophyly seems to suggest a monophyletic Glomeromycota:

https://tree.opentreeoflife.org/curator/study/view/ot_2052/?tab=home

(image from the paper below)

<img width="1083" alt="Screenshot 2024-05-07 at 16 42 08" src="https://github.com/OpenTreeOfLife/feedback/assets/4699014/97133691-ace2-4dc3-a0f6-8e6f9d6e25e4">

I'm wondering if there's a funny taxon mapping mistake here, but I'm not skilled enough in OpenTree-fu to figure out what's going on exactly. It seems weird that the Acaulosporaceae is still at the top level of fungi in the OpenTree, when this study places them sensibly, however.

**Comment by mtholder** [comment]
the tree in the Open Tree curator was incorrectly rooted. I have fixed that. So this should be resolved when we build the next synthesis. I'm hoping to start that today.
