### ISSUE TITLE
be good to have a way to designate fossils

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#59]
Timothyia trinervis   = fossil
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | Doug Soltis |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/otol.draft.22@3204412/Timothyia-trinervis](https://tree.opentreeoflife.org/opentree/otol.draft.22@3204412/Timothyia-trinervis) |
| Target node label | Timothyia trinervis |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 3204412 |
| Source tree id(s) | gbif:4940828 |
| Open Tree Taxonomy id | 3867108 |
| Intended scope |  |

**Comment by jar398** [comment]
All of Timothyia is extinct.  This is fixed in ott2.9draft9
