### ISSUE TITLE
count number of descendent taxa in synthetic tree

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/feedback#60]
Got the following query via email:

"Is there a way to get an estimate of the number of microbial eukaryote nodes in Open Tree? Even a rough estimate would be helpful."

There is probably a way to use the count() method in smasher to ask about OTT, but the synthetic tree would require a new API method. There might be a way in peyotl or dendropy? @mtholder or @jar398 ?

**Comment by josephwb** [comment]
The treemachine service [`node_info`](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#node_info) returns the number of tips for a query node.

**Comment by kcranston** [comment]
Thanks, @josephwb ! So, the num_synth_children refers to the synthetic tree, not to the whole graph?

**Comment by josephwb** [comment]
It reports both:
1. "num_tips": the number of descendant tips in the graph
2.  "num_synth_children" (soon to be ["num_synth_tips"](https://github.com/OpenTreeOfLife/treemachine/commit/ba02cf6fa5e5fec0668b6c72d805e9f1e436a94c)): the number of descendant tips in the synthetic tree
These numbers _could_ theoretically be different (in the earlier implementation) if the structure of the graph and ranks are such that some taxa could not be reached by in synthesis. But generally the numbers are identical.

**Comment by diatomsRcool** [comment]
Hello
I'm the one who sent the email query. How would I run the num_synth_children function? Should I just comment with a list of node names and then some one can run the query for me?

**Comment by josephwb** [comment]
You can do it over curl, e.g. for "Trochilidae":

``` bash
curl -X POST http://api.opentreeoflife.org/v2/graph/node_info -H "content-type:application/json" -d '{"ott_id":810751}'
```

Result:

``` json
{
  "synth_sources" : [ {
    "study_id" : "pg_2853",
    "git_sha" : "a2c48df995ddc9fd208986c3d4225112550c8452",
    "tree_id" : "6624"
  }, {
    "study_id" : "taxonomy",
    "git_sha" : "",
    "tree_id" : ""
  }, {
    "study_id" : "pg_420",
    "git_sha" : "a2c48df995ddc9fd208986c3d4225112550c8452",
    "tree_id" : "522"
  } ],
  "in_synth_tree" : true,
  "rank" : "family",
  "in_graph" : true,
  "name" : "Trochilidae",
  "num_tips" : 371,
  "ott_id" : 810751,
  "num_synth_children" : 371,
  "tax_source" : "ncbi:9242,gbif:5289,irmng:104628",
  "tree_sources" : [ {
    "study_id" : "pg_2853",
    "git_sha" : "a2c48df995ddc9fd208986c3d4225112550c8452",
    "tree_id" : "6624"
  }, {
    "study_id" : "taxonomy",
    "git_sha" : "",
    "tree_id" : ""
  }, {
    "study_id" : "pg_420",
    "git_sha" : "a2c48df995ddc9fd208986c3d4225112550c8452",
    "tree_id" : "522"
  } ],
  "node_id" : 3021732
}
```

The tricky part is only getting the appropriate `ott_id`.

**Comment by josephwb** [comment]
The current synthetic tree uses the taxonomy "ott2.8", which you can get [here](http://files.opentreeoflife.org/ott/). The first column in the "taxonomy.tsv" files is the ott_id for the taxon.

**Comment by jar398** [comment]
You can also get OTT ids by navigating to the taxon in the open tree
browser. The id will show up in the pane on the right under "Reference
taxonomy".

**Comment by kcranston** [comment]
@diatomsRcool  - is this sufficient for me to close this issue, or do you still have questions about how to go find this information?

**Comment by diatomsRcool** [comment]
oh yes, this can close. I was able to get what I needed. Thanks!

On 3/19/2015 12:24 PM, Karen Cranston wrote:

> @diatomsRcool https://github.com/diatomsRcool - is this sufficient 
> for me to close this issue, or do you still have questions about how 
> to go find this information?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OpenTreeOfLife/feedback/issues/60#issuecomment-83650525.

## 

Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185
