### ISSUE TITLE
inconsistent behavior for NEXUS file when requesting tree that doesn't exist from a study

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#61]
When requesting a tree that doesn't exist from a study, the API returns an empty NEXUS file while requesting all other formats return an error:

```
$ curl -X GET http://api.opentreeoflife.org/v2/study/2647/tree/tree999.nex
#NEXUS
BEGIN TAXA;
    Dimensions NTax = 0;
    TaxLabels  ;
END;
BEGIN TREES;

END;
```

```
$  curl -X GET http://api.opentreeoflife.org/v2/study/2647/tree/tree999.json
subresource "tree/tree999" not found in study "2647"

$ curl -X GET http://api.opentreeoflife.org/v2/study/2647/tree/tree999.tre
subresource "tree/tree999"
```

**Comment by mtholder** [comment]
Thanks, @fmichonneau 
This will be fixed when we merge https://github.com/OpenTreeOfLife/peyotl/pull/123 and deploy that fix to the server. i'll leave this open until then.

**Comment by fmichonneau** [comment]
Great, thanks!

**Comment by jar398** [comment]
curl -X GET http://api.opentreeoflife.org/v2/study/2647/tree/tree999.nex
subresource "tree/tree999" not found in study "2647"bash-3.2$
