### ISSUE TITLE
"Sorry, there was an error checking for taxon status."

### ISSUE THREAD

**Issue by LookoutRanch** [OpenTreeOfLife/feedback#615]
Upon attempting to open the web site, ToL errors out with the following message:

"Sorry, there was an error checking for taxon status."

Tried current release builds of Brave, Chrome, Brave, Firefox, and Edge all fail in the same manner.

![foo](https://github.com/user-attachments/assets/1d262392-5568-4b3d-b6f6-9f7d2c06e844)

**Comment by mtholder** [comment]
Thanks for the report. Some of the services had gone offline. They are back now.

**Comment by LookoutRanch** [comment]
Thank you!
