### ISSUE TITLE
Improve documentation of studies/properties endpoint

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#62]
Trees and studies can be searched according to several parameters returned by the studies/properties endpoint as documented here: https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#properties

However, it is not always clear what these terms mean and what possible values they can take. It would be great if those could be documented (or if they already are, to include a link to the definitions in the API documentation).

Thanks!

**Comment by fmichonneau** [comment]
We are preparing the re-submission of our manuscript describing the R package that provides an interface to the API.

One of the reviewers pointed out that having a documentation of the properties would be useful. Is there a documentation for the tree and study properties now? I can't seem to find it on the wiki.

Thanks!

**Comment by kcranston** [comment]
The current NeXSON documentation is here: https://github.com/OpenTreeOfLife/phylesystem-api/wiki/NexSON. Does that give you what you (and your reviewer) wants?

**Comment by fmichonneau** [comment]
thanks! Yes, that looks good.
