### ISSUE TITLE
Plagiomene is a fossil taxon

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#64]
This is mistakenly appearing in the synthetic tree
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [hyanwong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@787278/Plagiomene](https://tree.opentreeoflife.org/opentree/opentree3.0@787278/Plagiomene) |
| Target node label | Plagiomene |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 787278 |
| Source tree id(s) | gbif:4974857 |
| Open Tree Taxonomy id | 3607469 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
Fixed in 2.9draft9
