### ISSUE TITLE
Worlandia is a fossil taxon

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#65]
Should not appear in the synthetic tree
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [hyanwong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@787276/Worlandia](https://tree.opentreeoflife.org/opentree/opentree3.0@787276/Worlandia) |
| Target node label | Worlandia |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 787276 |
| Source tree id(s) | gbif:4974852 |
| Open Tree Taxonomy id | 3607471 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
Fixed in OTT 2.9draft9
