### ISSUE TITLE
Warn users of API changes?

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#66]
The latest deployment of the API led to some changes in the names of the output.

For instance, in `/tree_of_life/induced_subtree` one of the keys changed from `subtree` to `newick`.

These changes broke the R package. I only noticed them because I'm currently actively working on it.

Do you have a mechanism in place to warn users of the API of such changes?

**Comment by jar398** [comment]
Here's the culprit:
https://github.com/OpenTreeOfLife/treemachine/commit/cb36de438ac26a58bebb7f10aa8d3a1609da0dde

No, we don't have a mechanism, and obviously we should. I wonder what would
be appropriate? We have the opentreeoflife google group, would it make
sense to announce changes there?

We should also add tests for this and anything else you use, so that we at
least get alerts during development.

Thanks for reporting this!
Jonathan

**Comment by jimallman** [comment]
Indeed. I just discovered this change [while working on peyotl](https://github.com/OpenTreeOfLife/peyotl/commit/b080b6c44716783d2177ef75911848b92d5c0971) yesterday. 

I updated the unit tests, but I didn't think to sound the alarm about API changes. :grimacing: 

+1 for automated API testing, perhaps from a cron job?

**Comment by jar398** [comment]
We have the tests in the germinator repo (test.sh), and even though they're
minimal, they've been very helpful.
Running them from a cron job is not a bad idea.

**Comment by kcranston** [comment]
Made a [new issue in the germinator repo](https://github.com/OpenTreeOfLife/germinator/issues/22) to run tests as a cron job. 

Open to suggestions for the best way to notify users of API changes.

**Comment by jar398** [comment]
obvious choices are opentree group, opentree-software group, some new
group.  problem for users is clutter.

maybe new group opentree-announce?

**Comment by fmichonneau** [comment]
+1 for an opentree-announce list.

I don't know your procedure for release, but at least from the perspective of the R package, it would be ideal if changes could be announced 1 month before deployment to production. Indeed, the gate keepers on CRAN don't like when packages get updated more than once a month.

Thanks!

**Comment by jar398** [comment]
This issue is becoming highly relevant (v3).

**Comment by kcranston** [comment]
We've already given folks a heads up on the [mailing list](https://groups.google.com/forum/#!topic/opentreeoflife/wb45BnOmip0), and I've notified both rotl and phylotastic. I don't want to make another official announcement until the docs are finished, i.e. until we stop making changes.

**Comment by jar398** [comment]
@fmichonneau So we have finished the v3 update, and the question is whether you received adequate notification and documentation.  Were the announcements, release notes, and documentation adequate?

**Comment by fmichonneau** [comment]
Yes, we received enough information about the changes. thanks!
