### ISSUE TITLE
Bug with `/studies/find_trees`?

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#67]
The example given in the API documentation for `/studies/find_trees` used to return several studies/trees but now doesn't return anything:

```
curl -X POST http://api.opentreeoflife.org/v2/studies/find_trees \
-H "content-type:application/json" -d \
'{"property":"ot:ottTaxonName","value":"Garcinia"}'
```

**Comment by jar398** [comment]
The v3 documentation has an example that returns one study, so at least we no longer have a documentation error.

But I don't think that's what you were really concerned about. Unfortunately the search-on-taxon-name feature is broken and is unavailable until further notice.

**Comment by mtholder** [comment]
fixed (v3 not v2)
