### ISSUE TITLE
Retrieve higher taxonomy from a tree

### ISSUE THREAD

**Issue by fmichonneau** [OpenTreeOfLife/feedback#69]
@mwpennell was wondering if it would be possible to extract the higher classification from species included in a study: https://gist.github.com/mwpennell/5e4fcfd5e92407b6a9d6

I don't think it's currently possible with the API. It seems that it would be generally useful. So maybe it would be worth considering implementing a way of doing it?

**Comment by jar398** [comment]
Not sure what you mean, can you clarify, or give an example?
Do you mean the phylogenetic tree over those species (induced_tree method)? I thought that had interior nodes labeled, but maybe it doesn't.
Or the taxonomy over those species (it might be 'induced_taxonomy' if we had such a thing)?

**Comment by fmichonneau** [comment]
The idea here would be to retrieve the taxonomy over the species, so yes something like `induced_taxonomy`.

From what I can tell, there is no way with the API to see what is the taxonomic parent of a given node. Maybe if the API could provide the parent node for a given taxon, it would be possible to recursively query the parent to obtain the taxonomic rank and names up to the root to obtain the full classification of a given taxon.

**Comment by pmidford** [comment]
The taxon service already provides parameter to return the path back to
root
(https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#taxon).

**Comment by fmichonneau** [comment]
Thanks! I had missed that.
