### ISSUE TITLE
Misspelling 

### ISSUE THREAD

**Issue by dhibbett** [OpenTreeOfLife/feedback#7]
In: Fungi --> Dikarya --> Basidiomycota --> Agaricomycotina 

Dacrymycetales is misspelled as Dacrymecetales

**Comment by jar398** [comment]
Actually they both seem to be in the taxonomy. E is the parent of Y, but
only has one child (Y). So I will just splice out E, putting Y under
whatever E's parent is.

**Comment by dhibbett** [comment]
Thanks, Jonathan.

The correct classification and spelling for this clade, as far as I know, is Dacrymycetes (class), Dacrymycetales (order).

Cheers,

David

## 

David S. Hibbett
Biology Department
Lasry Center for Bioscience
Clark University
950 Main Street
Worcester MA 01610 USA
http://hibbettlablog.wordpress.com/

**Comment by jar398** [comment]
After looking at this carefully I have decided to rename 'Dacrymecetales' to be 'Dacrymycetes'. This preserves the topology.

**Comment by jar398** [comment]
Should be fixed in next taxonomy build.

**Comment by dhibbett** [comment]
Thanks, Jonathan!
 --
David S. Hibbett
Biology Department
Cathy '83 and Marc '81 Lasry Center for Bioscience
Clark University
950 Main Street
Worcester MA 01610
Tel: (508) 793-7332
Lab news: http://hibbettlablog.wordpress.com/
MassMyco 10/11/14: http://massmyco.wordpress.com/
