### ISSUE TITLE
TEST Here's a bug report

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/feedback#70]
And some more detail
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jim Allman](https://github.com/jimallman) |
| Upvotes | 0 |
| URL | [devtree.opentreeoflife.org/opentree/argus/opentree3.0@1](http://devtree.opentreeoflife.org/opentree/argus/opentree3.0@1) |
| Target node label | cellular organisms |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 1 |
| Source tree id(s) | ncbi:131567 |
| Open Tree Taxonomy id | 93302 |
| Intended scope |  |

**Comment by jimallman** [comment]
Here's a response to me!

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Jim Allman](https://github.com/jimallman) |
| Upvotes | 0 |

**Comment by kcranston** [comment]
Resolving test comment.

**Comment by jimallman** [comment]
Thanks @kcranston :grimacing:

**Comment by jimallman** [comment]
This is a test comment (testing API calls for curator profile page)
