### ISSUE TITLE
Incertae sedis?

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/feedback#71]
I thought we were suppressing OTT taxa named "Incertae Sedis"? 
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Karen Cranston](https://github.com/kcranston) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@3448063/Incertae-Sedis](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@3448063/Incertae-Sedis) |
| Target node label | Incertae Sedis |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 3448063 |
| Source tree id(s) | silva:L37037/#2 |
| Open Tree Taxonomy id | 5268476 |
| Intended scope |  |

**Comment by jar398** [comment]
This is a known bug in OTT 2.8 (missing incertae_sedis flag when the
container comes from SILVA).  It has already been fixed in OTT 2.9.

**Comment by jar398** [comment]
These are all gone from the synthetic tree. Three of them still show up in the TNRS, but that's a separate issue ( https://github.com/OpenTreeOfLife/reference-taxonomy/issues/175 ).
