### ISSUE TITLE
Fossil spp

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#72]
This is a fossil sp
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@976681/Myeladaphus](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@976681/Myeladaphus) |
| Target node label | Myeladaphus |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 976681 |
| Source tree id(s) | gbif:4964598 |
| Open Tree Taxonomy id | 3595436 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
fixed in ott 2.9 draft 12
