### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#73]
This is a misspelling of Asymmetron which is also in the tree (as a sister)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@740068/Assymetron](https://tree.opentreeoflife.org/opentree/opentree3.0@740068/Assymetron) |
| Target node label | Assymetron |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 740068 |
| Source tree id(s) | gbif:2473294 |
| Open Tree Taxonomy id | 3647396 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
The synonymy now comes in via WoRMS, so no particular action is required to fix this in OTT 2.9.

**Comment by jar398** [comment]
Fixed in ott 2.9 draft 12
Assymetron  |   3647396 |       |   Assymetron (synonym for Asymmetron) |
