### ISSUE TITLE
Misplaced snail

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#74]
This seems to be a typo for Lymnaea acuminata which is freshwater snail, not a shark!
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@978884/Lymnea](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@978884/Lymnea) |
| Target node label | Lymnea |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 978884 |
| Source tree id(s) | irmng:1317416 |
| Open Tree Taxonomy id | 5327187 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
IRMNG seems to have gotten the species record from this source:
http://collections.museumvictoria.com.au/search?query=Lymnea&sort=relevance
which provides very little information (not authority or other citation, no
image, etc.).

For the genus, IRMNG says "Unavailable name (nomen nudum). See Noelius
Rafinesque 1815. Nomen. Zool.). Not available, name only; perhaps an
incorrect subsequent spelling of Lamna. Rafinesque changed name from Lymnea
to Noelius in "Additions et Corrections" on p. 220 without explanation.
(Eschmeyer)."

I would be inclined to simply delete the species and genus from OTT.

**Comment by jar398** [comment]
Species removed, not present in OTT 2.9draft12.
