### ISSUE TITLE
Embryophyta

### ISSUE THREAD

**Issue by zbolander** [OpenTreeOfLife/feedback#8]
land plants, Embryophyta, are un-named in most recent tree

**Comment by jar398** [comment]
You will have to fight this one out with Bryan Drew. Here is his email from March 13:

One thing I noticed that should probably be changed is that Streptophytina should be eliminated as a designation, and the three main clades within Streptophytina (Charophyceae, Embryophyta, Coleochaetophyceae) should be collapsed back to Streptophyta. 

I'm basing this claim off of the recent paper:

Ruhfel BR, Gitzendanner MA, Soltis PS, Soltis DE, Burleigh JG (2014) From algae to angiosperms–inferring the phylogeny of green plants (Viridiplantae) from 360 plastid genomes. BMC Evolutionary Biology 14: 23. 

doi:10.1186/1471-2148-14-23

I ccd Doug on this in case I am misinterpreting this.

See https://github.com/OpenTreeOfLife/reference-taxonomy/issues/24

**Comment by josephwb** [comment]
Doesn't ("Brian Drew" == @zbolander)?

**Comment by jar398** [comment]
I have no idea. I did a bunch of searches and couldn't figure out who it
was.

**Comment by zbolander** [comment]
yeah, @zbolander = Bryan Drew

Did I contradict myself with my feedback comment yesterday?

**Comment by jar398** [comment]
Yes, you did. Please fight it out with yourself and let me know who wins...

**Comment by zbolander** [comment]
So Streptophytina should be collapsed as indicated, but Embryophyta should
not have lost its name in that process?

**Comment by blackrim** [comment]
This is likely due to parfrey 2011 which is not included in future versions. Hasn't been updated but when it does this should be corrected.

**Comment by jar398** [comment]
This is 2.8draft4:

grep " Embryophyta     " tax/ott/taxonomy.tsv 
5342313 |       916750  |       Embryophyta     |       no rank |       ncbi:3193       |               |               |
