### ISSUE TITLE
unable to retrieve studies in database

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/feedback#81]
I got the same error when trying to access few studies from the database.
![screen shot 2015-08-24 at 12 42 58 pm](https://cloud.githubusercontent.com/assets/6391539/9446122/d71e7182-4a5d-11e5-961f-b4c3a3681a3f.png)

Romina

**Comment by jimallman** [comment]
This was apparently due to treemachine failure (running but hung and not responding). A forced restart of treemachine has restored all systems, but we'll need to dig to find the real cause. See also https://github.com/OpenTreeOfLife/opentree/issues/714
