### ISSUE TITLE
Fossil sp

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#82]
Tarsius thailandica is a fossil spp, but not marked as such in the synth tree
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@778244/Tarsius-thailandica](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@778244/Tarsius-thailandica) |
| Target node label | Tarsius thailandica |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 778244 |
| Source tree id(s) | gbif:4974776 |
| Open Tree Taxonomy id | 3607737 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
Fixed in ott 2.9 draft 12
3607737 |   339047  |   Tarsius thailandica |   species |   gbif:4974776    |       |   extinct |
