### ISSUE TITLE
Genus change

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#83]
Tarsius syrichta is now in genus Carlito 
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@778265/Tarsius-syrichta](https://tree.opentreeoflife.org/opentree/opentree3.0@778265/Tarsius-syrichta) |
| Target node label | Tarsius syrichta |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 778265 |
| Source tree id(s) | ncbi:9478,gbif:2436484,irmng:11036404 |
| Open Tree Taxonomy id | 339031 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
I'm going to rename the species, but I am going to be lazy and won't create the monotypic genus. (we are not too keen on monotypic taxa around here.)  Let's hope a future NCBI update straightens this out.

**Comment by jar398** [comment]
Half-fixed in OTT 2.9 draft 12
Tarsius syrichta    |   339031  |       |   Tarsius syrichta (synonym for Carlito syrichta) |
