### ISSUE TITLE
Genus change

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#84]
Tarsius bancanus is now in genus Cephalopachus
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@778259/Tarsius-bancanus](https://tree.opentreeoflife.org/opentree/opentree3.0@778259/Tarsius-bancanus) |
| Target node label | Tarsius bancanus |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 778259 |
| Source tree id(s) | ncbi:9477,gbif:2436487,irmng:10597023 |
| Open Tree Taxonomy id | 339050 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
Name changed, no genus introduced
Tarsius bancanus    |   339050  |       |   Tarsius bancanus (synonym for Cephalopachus bancanus)   |  
Will wait to create the genus until we get a good up to date mammal list.
