### ISSUE TITLE
Synonymous species not identified in genus Silene

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#85]
It seems that the genera Lychnis, Gastrolychnis and Melandrium are correctly placed in the genus Silene, but the synonymy of species names is not taken into account. E.g. Silene drummondii is represented 3 more times, as Lychnis drummondii, Gastrolychnis drummondii and Melandrium drummondii ; these species are however recognized as synonyms on the IRMNG website, where your information comes from. I haven't checked other genera, but suspect this issue arises elsewhere as well.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [jos](mailto:jos.kaefer@gmail.com) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@616131/Silene](https://tree.opentreeoflife.org/opentree/opentree3.0@616131/Silene) |
| Target node label | Silene |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 616131 |
| Source tree id(s) | ncbi:3573,gbif:3085897,irmng:1350117 |
| Open Tree Taxonomy id | 842205 |
| Intended scope | Re: OTT taxon |

**Comment by snacktavish** [comment]
Looks like this problem is already fixed in OTT2.9

**Comment by hyanwong** [comment]
Can this be closed now?
