### ISSUE TITLE
This is a fossil taxon

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#86]
This is a fossil taxon but not identified as such
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@981931/Gillocystis](https://tree.opentreeoflife.org/opentree/opentree3.0@981931/Gillocystis) |
| Target node label | Gillocystis |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 981931 |
| Source tree id(s) | gbif:4871524,irmng:1205398 |
| Open Tree Taxonomy id | 4148264 |
| Intended scope | Re: OTT taxon |

**Comment by hyanwong** [comment]
Now gone from synth tree 4.0

**Comment by jar398** [comment]
But it's still in the taxonomy:
4148264 |   3658790 |   Gillocystis |   genus   |   gbif:4871524,irmng:1205398  |       |   major_rank_conflict_inherited   |
