### ISSUE TITLE
Probably reclassified

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#87]
http://tolweb.org/Somasteroidea/24272 says 'The extant Platasterias latiradiata was subsequently reclassified by D. B. Blake (1982) and was placed in the Asteroidea'. Either way, this taxon belongs within Asterozoa, not at the base of the Echinoderms
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@981936/Platasteriidae](https://tree.opentreeoflife.org/opentree/opentree3.0@981936/Platasteriidae) |
| Target node label | Platasteriidae |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 981936 |
| Source tree id(s) | gbif:5622,irmng:110243 |
| Open Tree Taxonomy id | 3658523 |
| Intended scope | Re: source tree |

**Comment by jar398** [comment]
Platasteriidae  |   3658523 |       |   Platasteriidae (synonym for Luidiidae)  |  
3658523 |   658406  |   Luidiidae   |   family  |   ncbi:60582,worms:123129,gbif:5622,gbif:9474,irmng:110243,irmng:101560   |       |   sibling_higher  |  
658406  |   134762  |   Paxillosida |   order   |   ncbi:55648,worms:123088,gbif:808,irmng:11968,irmng:11764    |       |       |  
134762  |   451009  |   Valvatacea  |   superorder  |   ncbi:41243,worms:582528 |       |   sibling_higher  |  
451009  |   5292796 |   Asteroidea  |   class   |   ncbi:7588,worms:123080,gbif:214,irmng:1362  |       |       |
