### ISSUE TITLE
Probably misplaced

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#88]
I have seen no evidence online which classifies Acanthokara outside the true onychophorans (Euonychophora), so I don't know where this deep placement is coming from.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree3.0@1279271/Acanthokara](https://tree.opentreeoflife.org/opentree/argus/opentree3.0@1279271/Acanthokara) |
| Target node label | Acanthokara |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 1279271 |
| Source tree id(s) | ncbi:62872,gbif:2235526,irmng:1337153 |
| Open Tree Taxonomy id | 3583375 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
Thanks for reporting this, as it surfaces a bug in the code that generates OTT.

NCBI doesn't want to commit to any particular placement of this genus; it puts it in ['unclassified Onychophora'](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=62871&lvl=3&lin=f&keep=1&srchmode=1&unlock). So NCBI is why OTT doesn't put it in any sub-phylum taxon (e.g. Peripatopsidae, which is where GBIF puts it).  But OTT should either accept the NCBI incertae-sedis status for the genus, or it should accept GBIF's placement; it does neither, taking it to be a direct non-incertae-sedis child of Onychophora. That's wrong.

**Comment by jar398** [comment]
I spoke too soon, I don't think there is a bug in the code. The genus is placed in Peripatopsidae, and this information comes from GBIF, which gets it from The Catalogue of Life, 3rd January 2011. The current CoL has pretty much the same information. NCBI has the genus as unclassified. Neither source has a Euonychophora taxon, so saying it goes there is not of much use.

Can you give a URL for an Onychophora taxonomy source that you think reflects current understanding?

**Comment by hyanwong** [comment]
On 15 Sep 2015, at 17:34, Jonathan A Rees notifications@github.com wrote:

> I spoke too soon, I don't think there is a bug in the code. The genus is placed in Peripatopsidae, and this information comes from GBIF, which gets it from The Catalogue of Life, 3rd January 2011. The current CoL has pretty much the same information. NCBI has the genus as unclassified. Neither source has a Euonychophora taxon, so saying it goes there is not of much use.
> 
> Can you give a URL for an Onychophora taxonomy source that you think reflects current understanding?

No, sorry. But odd that it�s only this species that has problems. What is causing all the other Peripatopsidae taxa to be placed within Euonychophora. And if GBIF puts the taxon in Peripatopsidae, why isn�t it in https://tree.opentreeoflife.org/opentree/opentree3.0@1278831/Peripatopsidae ?

**Comment by jar398** [comment]
Oh I see, I misread a digit... in OTT 2.8, the NCBI classification has precedence, and NCBI has it as unclassified. It ought to be suppressed but for reasons I won't track down it's put as a direct child of Onychophora. The merge algorithm got smarter (?) for OTT 2.9, and OTT 2.9 puts the genus in Peripatopsidae, where GBIF has it.

The NCBI taxonomy curators must have had a reason for not putting it in its customary location, but as usual they don't say why they do what they do.

If there are so many Onychophora sequences in NCBI, perhaps one could do a phylogenetic analysis to figure out where the genus should go...  I found this study by poking around genbank, but unfortunately it doesn't sample Acanthokara: http://rspb.royalsocietypublishing.org/content/281/1775/20132648.short
The paper for which Acanthokara was sampled is very interesting, but it's a broad-scale phylogenetic analysis looking at Hox genes, and doesn't resolve within the phylum.

The higher classification of the phylum (Euonychophora and so on) comes from IRMNG, not GBIF.

Anyhow, it should be in Peripatopsidae the next time we do a synthesis, so I'm not taking any action.

**Comment by hyanwong** [comment]
On 15 Sep 2015, at 19:39, Jonathan A Rees notifications@github.com wrote:

> If there are so many Onychophora sequences in NCBI, perhaps one could do a phylogenetic analysis to figure out where the genus should go... I found this study by poking around genbank, but unfortunately it doesn't sample Acanthokara: http://rspb.royalsocietypublishing.org/content/281/1775/20132648.short

Hmm. Is the era of automated phylogenetic analysis via genbank coming?

> The paper for which Acanthokara was sampled is very interesting, but it's a broad-scale phylogenetic analysis looking at Hox genes, and doesn't resolve within the phylum.

OpenTree is lacking high level arthropod etc phylogenies (see my recent post to the mailing list). perhaps this is a good one to add.

> Anyhow, it should be in Peripatopsidae the next time we do a synthesis, so I'm not taking any action.

Yep - seems the most sensible. Thanks.

Yan

**Comment by jar398** [comment]
Acanthokara is in Peripatopsidae in OTT 2.9 draft 12
