### ISSUE TITLE
Pan paniscus vs Pan troglodytes verus

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#89]
Why are Pan paniscus and Pan troglodytes verus placed together as subspecies of Pan. As far as I can see, the references does not support this, .
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Björn Hedman](mailto:jomoman57@hotmail.com) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@3848794/Pan-paniscus--Pan-troglodytes-verus](https://tree.opentreeoflife.org/opentree/opentree3.0@3848794/Pan-paniscus--Pan-troglodytes-verus) |
| Target node label | [Pan paniscus + Pan troglodytes verus] |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 3848794 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Intended scope | Re: synthetic tree |

**Comment by mtholder** [comment]
Hi, I agree that that relationship is not discussed in the paper nor is it shown in Figure 2 of that paper. Interestingly though, that grouping is shown in the TreeBase version of the tree labeled "Fig. 2". See http://treebase.org/treebase-web/search/study/trees.html?id=12186 The tree in the open tree curator app (https://tree.opentreeoflife.org/curator/study/view/pg_1600?tab=trees&tree=tree3231 ) comes from TreeBase. I'm not sure whether the figure in the paper or the treebase record is in error.  Thanks for bringing this up!

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Mark T. Holder](https://github.com/mtholder) |
| Upvotes | 0 |

**Comment by kcranston** [comment]
Thanks for the feedback! I've added a comment to the study about the mismatch and emailed the authors.
