### ISSUE TITLE
Synthesis issues in Fungi

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/feedback#9]
I think these are synthesis probems, not taxonomy problems, so I am moving the issue here.  Please see

https://github.com/OpenTreeOfLife/reference-taxonomy/issues/34

The deep relationships look ok for the Fungi.

BUT

Within Ascomycota, many genera are directly rooted to the super-class 'Leotiomyceta' even though they have a classification based on IF
example: Oreophylla and Cercospora both are classified as

Mycosphaerellaceae, Capnodiales, Dothideomycetidae, Dothideomycetes, Pezizomycotina, Ascomycota, Fungi

but appear rooted directly to the Leotiomyceta

There is also a family: Antennulariellaceae, Capnodiales, Dothideomycetidae, Dothideomycetes, Pezizomycotina, Ascomycota, Fungi

but appears rooted directly to the Leotiomyceta

The following classes should be part of the 'Leotiomyceta' node (besides the ones already there)
Dothideomycetes
Eurotiomycetes
Sordariomycetes
Lichinomycetes
Geoglossomycetes
Coniocybomycetes
Leotiomycetes
Laboulbeniomycetes

The classes are present in the tree but seems to be hidden within other nodes, I wonder if this is because the taxonomy I gave you Hibbett 2007 updated had non-formal internal nodes such as superclass or subclasses? or is this a results of input phylogenies?

Thanks,

Romina

**Comment by blackrim** [comment]
Will keep this in mind with the next synth. We can track down what is
causing this but the taxonomy has changed so best to wait until the new
synth
On Fri, Apr 04, 2014 at 02:34:39PM -0700, Jonathan A Rees wrote:

> I think these are synthesis probems, not taxonomy problems, so I am moving the issue here.  Please see
> 
> https://github.com/OpenTreeOfLife/reference-taxonomy/issues/34
> 
> The deep relationships look ok for the Fungi.
> 
> BUT
> 
> Within Ascomycota, many genera are directly rooted to the super-class 'Leotiomyceta' even though they have a classification based on IF
> example: Oreophylla and Cercospora both are classified as
> 
> Mycosphaerellaceae, Capnodiales, Dothideomycetidae, Dothideomycetes, Pezizomycotina, Ascomycota, Fungi
> 
> but appear rooted directly to the Leotiomyceta
> 
> There is also a family: Antennulariellaceae, Capnodiales, Dothideomycetidae, Dothideomycetes, Pezizomycotina, Ascomycota, Fungi
> 
> but appears rooted directly to the Leotiomyceta
> 
> The following classes should be part of the 'Leotiomyceta' node (besides the ones already there)
> Dothideomycetes
> Eurotiomycetes
> Sordariomycetes
> Lichinomycetes
> Geoglossomycetes
> Coniocybomycetes
> Leotiomycetes
> Laboulbeniomycetes
> 
> The classes are present in the tree but seems to be hidden within other nodes, I wonder if this is because the taxonomy I gave you Hibbett 2007 updated had non-formal internal nodes such as superclass or subclasses? or is this a results of input phylogenies?
> 
> Thanks,
> 
> Romina
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenTreeOfLife/feedback/issues/9

## 

Dr. Stephen A. Smith
http://blackrim.org
Assistant Professor, Dept. Ecology and Evolutionary Biology
University of Michigan
2071A Kraus Natural Science Building
830 North University
Ann Arbor, MI 48109-1048

**Comment by jar398** [comment]
The taxonomy has changed very little. I spot-checked the taxonomy for a
number of the cases that Romina gives but the taxonomy seems fine. So I
think these are real conflicts between what the input phylogenies say and
the preferred result.

**Comment by blackrim** [comment]
sounds good. once we get the trees in the queue in there we can push and
see what the issue is. I will try and investigate before that is done so
that the next synth might solve them but we will see
On Mon, Apr 07, 2014 at 07:23:07AM -0700, Jonathan A Rees wrote:

> The taxonomy has changed very little. I spot-checked the taxonomy for a
> number of the cases that Romina gives but the taxonomy seems fine. So I
> think these are real conflicts between what the input phylogenies say and
> the preferred result.
> 
> On Mon, Apr 7, 2014 at 9:52 AM, Stephen Smith notifications@github.comwrote:
> 
> > Will keep this in mind with the next synth. We can track down what is
> > causing this but the taxonomy has changed so best to wait until the new
> > synth
> > On Fri, Apr 04, 2014 at 02:34:39PM -0700, Jonathan A Rees wrote:
> > 
> > > I think these are synthesis probems, not taxonomy problems, so I am
> > > moving the issue here. Please see
> > > 
> > > https://github.com/OpenTreeOfLife/reference-taxonomy/issues/34
> > > 
> > > The deep relationships look ok for the Fungi.
> > > 
> > > BUT
> > > 
> > > Within Ascomycota, many genera are directly rooted to the super-class
> > > 'Leotiomyceta' even though they have a classification based on IF
> > > example: Oreophylla and Cercospora both are classified as
> > > 
> > > Mycosphaerellaceae, Capnodiales, Dothideomycetidae, Dothideomycetes,
> > > Pezizomycotina, Ascomycota, Fungi
> > > 
> > > but appear rooted directly to the Leotiomyceta
> > > 
> > > There is also a family: Antennulariellaceae, Capnodiales,
> > > Dothideomycetidae, Dothideomycetes, Pezizomycotina, Ascomycota, Fungi
> > > 
> > > but appears rooted directly to the Leotiomyceta
> > > 
> > > The following classes should be part of the 'Leotiomyceta' node (besides
> > > the ones already there)
> > > Dothideomycetes
> > > Eurotiomycetes
> > > Sordariomycetes
> > > Lichinomycetes
> > > Geoglossomycetes
> > > Coniocybomycetes
> > > Leotiomycetes
> > > Laboulbeniomycetes
> > > 
> > > The classes are present in the tree but seems to be hidden within other
> > > nodes, I wonder if this is because the taxonomy I gave you Hibbett 2007
> > > updated had non-formal internal nodes such as superclass or subclasses? or
> > > is this a results of input phylogenies?
> > > 
> > > Thanks,
> > > 
> > > Romina
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/OpenTreeOfLife/feedback/issues/9
> > 
> > ## 
> > 
> > Dr. Stephen A. Smith
> > http://blackrim.org
> > Assistant Professor, Dept. Ecology and Evolutionary Biology
> > University of Michigan
> > 2071A Kraus Natural Science Building
> > 830 North University
> > Ann Arbor, MI 48109-1048
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/OpenTreeOfLife/feedback/issues/9#issuecomment-39731904
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenTreeOfLife/feedback/issues/9#issuecomment-39735903

## 

Dr. Stephen A. Smith
http://blackrim.org
Assistant Professor, Dept. Ecology and Evolutionary Biology
University of Michigan
2071A Kraus Natural Science Building
830 North University
Ann Arbor, MI 48109-1048

**Comment by blackrim** [comment]
I think this is because of Parfrey et al 2011 which is a deep eukaryote phylogeny that is going to be removed for the next synth at the request of Laura because it doesn't reflect any consensus. So hopefully that will resolve this.

**Comment by blackrim** [comment]
Nope, it was 240. Think it is fixed, and will close if so.

**Comment by blackrim** [comment]
This fixed that issue.
