### ISSUE TITLE
Misplaced fossil species of Helix (in Bryozoa/Gymnolaemata, should be in Gastropoda)

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#90]
Helix evanstonensis is misplaced
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Phil Bock](mailto:philbock1@gmail.com) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@1073831/Helix](https://tree.opentreeoflife.org/opentree/opentree3.0@1073831/Helix) |
| Target node label | Helix |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 1073831 |
| Source tree id(s) | gbif:3267997,irmng:1285021 |
| Open Tree Taxonomy id | 4953561 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
This species (and the genus) is not present in the latest release.  I think it disappeared when I changed the rules for selecting which GBIF taxa to include in the taxonomy.  Maybe it will come back when/if we do a proper import of paleodb.
